export const SETTINGS_TRIGGERS_ACTIONS = {
	GET_TRIGGERS: 'GET_TRIGGERS',
	GET_TRIGGERS_RESPONSE: 'GET_TRIGGERS_RESPONSE',
	CREATE_TRIGGERS: 'CREATE_TRIGGERS',
	CREATE_TRIGGERS_RESPONSE: 'CREATE_TRIGGERS_RESPONSE',
	UPDATE_TRIGGERS: 'UPDATE_TRIGGERS',
	UPDATE_TRIGGERS_RESPONSE: 'UPDATE_TRIGGERS_RESPONSE',
	DELETE_TRIGGERS: 'DELETE_TRIGGERS',
	DELETE_TRIGGERS_RESPONSE: 'DELETE_TRIGGERS_RESPONSE'
};
