export const COMPANY_IMPORT_EXPORT_ACTIONS = {
    EXPORT_REQUEST: 'EXPORT_REQUEST',
    EXPORT_RESPONSE: 'EXPORT_RESPONSE',
    IMPORT_REQUEST: 'IMPORT_REQUEST',
    IMPORT_RESPONSE: 'IMPORT_RESPONSE',
    COMPANY_IMPORT_EXPORT_RESET: 'COMPANY_IMPORT_EXPORT_RESET'
};
