export const SETTINGS_PERMISSION_ACTIONS = {
    GET_PERMISSIONS: 'GET_PERMISSIONS',
    GET_PERMISSIONS_RESPONSE: 'GET_PERMISSIONS_RESPONSE',
    UPDATE_PERMISSIONS: 'UPDATE_PERMISSIONS',
    UPDATE_PERMISSIONS_RESPONSE: 'UPDATE_PERMISSIONS_RESPONSE'
};
