export const SETTINGS_PERMISSION_ACTIONS = {
    GET_USERS_WITH_COMPANY_PERMISSIONS: 'GET_USERS_WITH_COMPANY_PERMISSIONS',
    GET_USERS_WITH_COMPANY_PERMISSIONS_RESPONSE: 'GET_USERS_WITH_COMPANY_PERMISSIONS_RESPONSE',
};
