export const SETTINGS_DISCOUNT_ACTIONS = {
    GET_DISCOUNT: 'GET_DISCOUNT',
    GET_DISCOUNT_RESPONSE: 'GET_DISCOUNT_RESPONSE',
    CREATE_DISCOUNT: 'CREATE_DISCOUNT',
    CREATE_DISCOUNT_RESPONSE: 'CREATE_DISCOUNT_RESPONSE',
    UPDATE_DISCOUNT: 'UPDATE_DISCOUNT',
    UPDATE_DISCOUNT_RESPONSE: 'UPDATE_DISCOUNT_RESPONSE',
    DELETE_DISCOUNT: 'DELETE_DISCOUNT',
    DELETE_DISCOUNT_RESPONSE: 'DELETE_DISCOUNT_RESPONSE'
};
