export const IMPORT_EXCEL = {
  UPLOAD_FILE_REQUEST: 'UPLOAD_FILE_REQUEST',
  UPLOAD_FILE_RESPONSE: 'UPLOAD_FILE_RESPONSE',
  PROCESS_IMPORT_REQUEST: 'PROCESS_IMPORT_REQUEST',
  PROCESS_IMPORT_RESPONSE: 'PROCESS_IMPORT_RESPONSE',
};
