services:

    angular:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - '80:80'
  
    cypress:
      build:
        context: .
        dockerfile: Dockerfile-cypress
      depends_on:
        - angular
      network_mode: 'host'