export const SETTINGS_TAXES_ACTIONS = {
    CREATE_TAX: 'CREATE_TAX',
    CREATE_TAX_RESPONSE: 'CREATE_TAX_RESPONSE',
    UPDATE_TAX: 'UPDATE_TAX',
    UPDATE_TAX_RESPONSE: 'UPDATE_TAX_RESPONSE',
    DELETE_TAX: 'DELETE_TAX',
    DELETE_TAX_RESPONSE: 'DELETE_TAX_RESPONSE',
    GET_TAX: 'GET_TAX',
    GET_TAX_RESPONSE: 'GET_TAX_RESPONSE',
    RESET_TAX_RESPONSE: 'RESET_TAX_RESPONSE',
    GET_TAX_AUTHORITY: 'GET_TAX_AUTHORITY',
    GET_TAX_AUTHORITY_RESPONSE: 'GET_TAX_AUTHORITY_RESPONSE',
};
