export const PROFORMA_ACTIONS = {
    GET_ALL_PROFORMA_REQUEST: 'GET_ALL_PROFORMA_REQUEST',
    GET_ALL_PROFORMA_RESPONSE: 'GET_ALL_PROFORMA_RESPONSE',
    GET_PROFORMA_DETAILS_REQUEST: 'GET_PROFORMA_DETAILS_REQUEST',
    GET_PROFORMA_DETAILS_RESPONSE: 'GET_PROFORMA_DETAILS_RESPONSE',
    DELETE_PROFORMA_REQUEST: 'DELETE_PROFORMA_REQUEST',
    DELETE_PROFORMA_RESPONSE: 'DELETE_PROFORMA_RESPONSE',
    UPDATE_PROFORMA_REQUEST: 'UPDATE_PROFORMA_REQUEST',
    UPDATE_PROFORMA_RESPONSE: 'UPDATE_PROFORMA_RESPONSE',
    GENERATE_PROFORMA_REQUEST: 'GENERATE_PROFORMA_REQUEST',
    GENERATE_PROFORMA_RESPONSE: 'GENERATE_PROFORMA_RESPONSE',
    UPDATE_PROFORMA_ACTION: 'UPDATE_PROFORMA_ACTION',
    UPDATE_PROFORMA_ACTION_RESPONSE: 'UPDATE_PROFORMA_ACTION_RESPONSE',

    GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES: 'GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES',
    GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES_RESPONSE: 'GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES_RESPONSE',

    GENERATE_PROFORMA_FROM_ESTIMATE: 'GENERATE_PROFORMA_FROM_ESTIMATE',
    GENERATE_PROFORMA_FROM_ESTIMATE_RESPONSE: 'GENERATE_PROFORMA_FROM_ESTIMATE_RESPONSE',

    GET_ESTIMATE_VERSIONS: 'GET_ESTIMATE_VERSIONS',
    GET_ESTIMATE_VERSIONS_RESPONSE: 'GET_ESTIMATE_VERSIONS_RESPONSE',
    SEND_EMAIL: 'SEND_EMAIL',
    SEND_EMAIL_RESPONSE: 'SEND_EMAIL_RESPONSE',

    SET_VOUCHER_FOR_DETAILS: 'SET_VOUCHER_FOR_DETAILS',
    RESET_VOUCHER_FOR_DETAILS: 'RESET_VOUCHER_FOR_DETAILS',

    RESET_ACTIVE_VOUCHER: 'RESET_ACTIVE_VOUCHER'
};
