export enum InventoryStatusCategory {
    Open = "OPEN",
    InProgress = "IN_PROGRESS",
    Completed = "COMPLETED"
}

export enum BusinessDocumentType {
    DeliveryChallan = "DC"
}

export interface InventoryLookupOption {
    value: string;
    label: string;
}

export interface VoucherAutomationSettings {
    autoCreateOppositeOnDcRc: boolean;
    inventoryViaBusinessDocument: boolean;
    autoGenerateDcOnInvoice: boolean;
    autoGenerateRcOnBill: boolean;
}

export interface BatchManagementSettings {
    enabled: boolean;
    numberFormat: string;
    allocationMethod: string;
    expiryAlertDays: number;
    mandatoryBatchOnOutward: boolean;
    allowNegativeBatchStock: boolean;
}

export interface InventoryStatusStages {
    OPEN: string[];
    IN_PROGRESS: string[];
    COMPLETED: string[];
}

export interface InventoryStatusFlow {
    stages: InventoryStatusStages;
    defaultOnCreate: string;
    autoCloseWhen: string;
    allowSkipStages: boolean;
    autoCloseAfterDays: number;
}

export interface InventorySettingsLookups {
    autoCloseWhen: InventoryLookupOption[];
    batchNumberFormat: InventoryLookupOption[];
    batchAllocationMethod: InventoryLookupOption[];
}

export interface InventorySettingsResponse {
    voucherAutomation: VoucherAutomationSettings;
    batchManagement: BatchManagementSettings;
    deliveryChallanStatusFlow: InventoryStatusFlow;
    receiptNoteStatusFlow: InventoryStatusFlow;
    lookups: InventorySettingsLookups;
}

export interface InventoryStatusFlowUpdate {
    stages: string[];
    defaultOnCreate: string;
    autoCloseWhen: string;
    allowSkipStages: boolean;
    autoCloseAfterDays: number;
}

export interface InventorySettingsUpdateRequest {
    voucherAutomation: VoucherAutomationSettings;
    batchManagement: BatchManagementSettings;
    deliveryChallanStatusFlow: InventoryStatusFlowUpdate;
    receiptNoteStatusFlow: InventoryStatusFlowUpdate;
}

export interface BusinessDocumentStatus {
    documentType: BusinessDocumentType;
    statusCode: string;
    statusName: string;
    statusCategory: string;
    defaultStatusCategory: InventoryStatusCategory;
    isDefault: boolean;
    flowRole: string;
    selectableInFlow: boolean;
}
