/** Categories for inventory document status stages. */
export enum InventoryStatusCategory {
    Start = "START",
    InProgress = "IN_PROGRESS",
    End = "END"
}

/** Supported business document types for inventory. */
export enum BusinessDocumentType {
    DeliveryChallan = "DC",
    ReceiptNote = "RN"
}

/** Dropdown/lookup option with value and display label. */
export interface InventoryLookupOption {
    value: string;
    label: string;
}

/** Settings that control automatic voucher creation behaviour. */
export interface VoucherAutomationSettings {
    inventoryViaBusinessDocument: boolean;
    autoGenerateDcOnInvoice: boolean;
    autoGenerateRcOnBill: boolean;
}

/** Settings for batch/lot-based stock tracking. */
export interface BatchManagementSettings {
    enabled: boolean;
    numberFormat: string;
    allocationMethod: string;
    expiryAlertDays: number;
    mandatoryBatchOnOutward: boolean;
    allowNegativeBatchStock: boolean;
}

/** Status flow configuration for a document type. */
export interface InventoryStatusFlow {
    start: string[];
    inProgress: string[];
    end: string[];
    defaultOnCreate: string;
    autoCloseWhen: string;
    allowSkipStages: boolean;
    autoCloseAfterDays: number;
}

/** Lookup options used by inventory settings dropdowns. */
export interface InventorySettingsLookups {
    autoCloseWhen: InventoryLookupOption[];
    batchNumberFormat: InventoryLookupOption[];
    batchAllocationMethod: InventoryLookupOption[];
    defaultReportNature: InventoryLookupOption[];
}

/** Full inventory settings payload returned by the API. */
export interface InventorySettingsResponse {
    voucherAutomation: VoucherAutomationSettings;
    autoCreateOppositeOnDcRc: boolean;
    batchManagement: BatchManagementSettings;
    deliveryChallanStatusFlow: InventoryStatusFlow;
    receiptNoteStatusFlow: InventoryStatusFlow;
    defaultReportNature: string;
    lookups: InventorySettingsLookups;
}

/** Payload shape used when updating a document status flow. */
export interface InventoryStatusFlowUpdate {
    start: string[];
    inProgress: string[];
    end: string[];
    defaultOnCreate: string;
    autoCloseWhen: string;
    allowSkipStages: boolean;
    autoCloseAfterDays: number;
}

/** Request body for updating inventory settings. */
export interface InventorySettingsUpdateRequest {
    voucherAutomation: VoucherAutomationSettings;
    autoCreateOppositeOnDcRc: boolean;
    batchManagement: Pick<BatchManagementSettings, "enabled">;
}

/** Status definition for a business document in the inventory flow. */
export interface BusinessDocumentStatus {
    documentType: BusinessDocumentType;
    statusCode: string;
    statusName: string;
    statusCategory: string;
    defaultStatusCategory: InventoryStatusCategory;
    isDefault: boolean;
    flowRole: string;
    selectableInFlow: boolean;
}
