import { ChangeDetectionStrategy, Component, DestroyRef, OnInit, inject, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormControl, FormGroup, ReactiveFormsModule } from "@angular/forms";
import { MatButtonModule } from "@angular/material/button";
import { MatSlideToggleModule } from "@angular/material/slide-toggle";
import { forkJoin, of } from "rxjs";
import { catchError, finalize, take } from "rxjs/operators";
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { TranslateDirectiveModule } from "../../../theme/translate/translate.directive.module";
import { GiddhPageLoaderModule } from "../../../shared/giddh-page-loader/giddh-page-loader.module";
import { InventoryService } from "../../../services/inventory.service";
import { CommonService } from "../../../services/common.service";
import { ToasterService } from "../../../services/toaster.service";
import { InventoryModuleName, ReportNature } from "../../inventory.enum";
import {
    InventorySettingsResponse,
    InventorySettingsUpdateRequest,
    VoucherAutomationSettings
} from "../../../models/api-models/InventorySettings";

interface InventorySettingsLocale {
    title: string;
    subtitle: string;
    voucher_automation: string;
    auto_create_opposite: string;
    auto_create_opposite_description: string;
    inventory_via_business_document: string;
    inventory_via_business_document_description: string;
    auto_generate_dc: string;
    auto_generate_dc_description: string;
    auto_generate_rc: string;
    auto_generate_rc_description: string;
    cancel: string;
    save_settings: string;
    settings_updated: string;
    load_error: string;
    reports: string;
    report_as_per: string;
    report_as_per_description: string;
    books: string;
    inventory: string;
}

/** Modules that share the Books/Inventory reportNature preference */
const REPORT_NATURE_MODULES: string[] = [
    InventoryModuleName.group,
    InventoryModuleName.stock,
    InventoryModuleName.variant
];

@Component({
    selector: "inventory-settings",
    templateUrl: "./inventory-settings.component.html",
    styleUrls: ["./inventory-settings.component.scss"],
    changeDetection: ChangeDetectionStrategy.OnPush,
    standalone: true,
    imports: [
        CommonModule,
        ReactiveFormsModule,
        MatButtonModule,
        MatSlideToggleModule,
        TranslateDirectiveModule,
        GiddhPageLoaderModule
    ]
})
export class InventorySettingsComponent implements OnInit {
    /** Inventory API service. */
    private readonly inventoryService = inject(InventoryService);
    /** Common API service for report nature preference. */
    private readonly commonService = inject(CommonService);
    /** Toast notification service. */
    private readonly toaster = inject(ToasterService);
    /** Component destruction reference. */
    private readonly destroyRef = inject(DestroyRef);
    /** Localized labels for this page. */
    public readonly localeData = signal<InventorySettingsLocale>({} as InventorySettingsLocale);
    /** True while initial settings are loading. */
    public readonly isLoading = signal<boolean>(true);
    /** True while settings are being saved. */
    public readonly isSaving = signal<boolean>(false);
    /** Last settings response used by the cancel action. */
    private readonly originalSettings = signal<InventorySettingsResponse | null>(null);
    /** Last saved report nature used by the cancel action. */
    private readonly originalReportAsPerInventory = signal<boolean>(false);
    /** Strongly typed inventory settings form. */
    public readonly settingsForm = new FormGroup({
        voucherAutomation: new FormGroup({
            autoCreateOppositeOnDcRc: new FormControl(false, { nonNullable: true }),
            inventoryViaBusinessDocument: new FormControl(false, { nonNullable: true }),
            autoGenerateDcOnInvoice: new FormControl(false, { nonNullable: true }),
            autoGenerateRcOnBill: new FormControl(false, { nonNullable: true })
        }),
        reports: new FormGroup({
            reportAsPerInventory: new FormControl(false, { nonNullable: true })
        })
    });

    /**
     * Loads inventory settings and report nature preference.
     *
     * @memberof InventorySettingsComponent
     */
    public ngOnInit(): void {
        this.loadSettings();
    }

    /**
     * Stores translated page labels.
     *
     * @param {InventorySettingsLocale} translations Page translations
     * @memberof InventorySettingsComponent
     */
    public setLocaleData(translations: InventorySettingsLocale): void {
        this.localeData.set(translations);
    }

    /**
     * Restores the last settings loaded from the API.
     *
     * @memberof InventorySettingsComponent
     */
    public cancelChanges(): void {
        const settings = this.originalSettings();
        if (settings) {
            this.patchForm(settings);
            this.settingsForm.controls.reports.patchValue({
                reportAsPerInventory: this.originalReportAsPerInventory()
            });
            this.settingsForm.markAsPristine();
        }
    }

    /**
     * Saves the current inventory settings.
     *
     * @memberof InventorySettingsComponent
     */
    public saveSettings(): void {
        if (this.settingsForm.invalid || this.isSaving()) {
            return;
        }
        const payload = this.buildUpdatePayload();
        const reportNature = this.settingsForm.controls.reports.controls.reportAsPerInventory.value ? ReportNature.Inventory : ReportNature.Books;
        this.isSaving.set(true);
        forkJoin({
            // take(1): HandleCatch emits without complete, which would hang forkJoin
            settingsResponse: this.inventoryService.updateInventorySettings(payload).pipe(
                take(1),
                catchError((error) => of(error))
            ),
            reportResponse: forkJoin(
                REPORT_NATURE_MODULES.map((module) =>
                    this.commonService.saveSelectedTableColumns({ module, reportNature }).pipe(
                        take(1),
                        catchError(() => of(null))
                    )
                )
            ).pipe(
                catchError(() => of([]))
            )
        }).pipe(
            takeUntilDestroyed(this.destroyRef),
            finalize(() => this.isSaving.set(false))
        ).subscribe({
            next: ({ settingsResponse, reportResponse }) => {
                this.isSaving.set(false);
                const settingsSuccess = settingsResponse?.status === "success";
                const reportSuccess = Array.isArray(reportResponse)
                    && reportResponse.some((response) => response?.status === "success");

                if (settingsSuccess) {
                    this.captureCurrentSettings();
                }
                if (reportSuccess) {
                    this.originalReportAsPerInventory.set(this.settingsForm.controls.reports.controls.reportAsPerInventory.value);
                }
                if (settingsSuccess || reportSuccess) {
                    this.settingsForm.markAsPristine();
                }

                if (settingsSuccess && reportSuccess) {
                    this.toaster.showSnackBar("success", this.localeData().settings_updated);
                } else if (!settingsSuccess && settingsResponse?.message) {
                    this.toaster.showSnackBar("error", settingsResponse.message);
                } else if (!reportSuccess) {
                    const reportError = Array.isArray(reportResponse)
                        ? reportResponse.find((response) => response?.message)?.message
                        : null;
                    if (reportError) {
                        this.toaster.showSnackBar("error", reportError);
                    }
                } else if (reportSuccess) {
                    this.toaster.showSnackBar("success", this.localeData().settings_updated);
                }
            },
            error: (error) => {
                this.isSaving.set(false);
                this.toaster.showSnackBar("error", error?.message || this.localeData().load_error);
            }
        });
    }

    /**
     * Loads settings and last saved report nature in parallel.
     *
     * @memberof InventorySettingsComponent
     */
    private loadSettings(): void {
        this.isLoading.set(true);
        forkJoin({
            settings: this.inventoryService.getInventorySettings().pipe(
                take(1),
                catchError((error) => of(error))
            ),
            reportNature: this.commonService.getSelectedTableColumns(InventoryModuleName.stock).pipe(
                take(1),
                catchError(() => of(null))
            )
        }).pipe(
            takeUntilDestroyed(this.destroyRef),
            finalize(() => this.isLoading.set(false))
        ).subscribe(({ settings, reportNature }) => {
            if (settings?.status !== "success" || !settings.body) {
                this.toaster.showSnackBar("error", settings?.message || this.localeData().load_error);
                return;
            }
            this.originalSettings.set(settings.body);
            this.patchForm(settings.body);
            const reportAsPerInventory = reportNature?.status === "success" && reportNature?.body?.reportNature === ReportNature.Inventory;
            this.originalReportAsPerInventory.set(reportAsPerInventory);
            this.settingsForm.controls.reports.patchValue({ reportAsPerInventory });
        });
    }

    /**
     * Prefills the settings form from an API response.
     *
     * @param {InventorySettingsResponse} settings Inventory settings
     * @memberof InventorySettingsComponent
     */
    private patchForm(settings: InventorySettingsResponse): void {
        this.settingsForm.controls.voucherAutomation.patchValue({
            ...settings.voucherAutomation,
            inventoryViaBusinessDocument: settings.voucherAutomation.inventoryViaBusinessDocument ?? false
        });
    }

    /**
     * Builds the update API payload from the form.
     *
     * @returns {InventorySettingsUpdateRequest} Update request
     * @memberof InventorySettingsComponent
     */
    private buildUpdatePayload(): InventorySettingsUpdateRequest {
        const value = this.settingsForm.getRawValue();
        return {
            voucherAutomation: value.voucherAutomation as VoucherAutomationSettings
        };
    }

    /**
     * Stores the saved form state for subsequent cancel actions.
     *
     * @memberof InventorySettingsComponent
     */
    private captureCurrentSettings(): void {
        const current = this.originalSettings();
        const value = this.settingsForm.getRawValue();
        if (!current) {
            return;
        }
        this.originalSettings.set({
            ...current,
            voucherAutomation: value.voucherAutomation
        });
    }
}
