export const PURCHASE_INVOICE_ACTIONS = {
    SET_TAXES_FOR_COMPANY: 'SET_TAXES_FOR_COMPANY',
    SEND_GSTR3B_EMAIL: 'SEND_GSTR3B_EMAIL',
    SEND_GSTR3B_EMAIL_RESPONSE: 'SEND_GSTR3B_EMAIL_RESPONSE'
};

export const GST_RETURN_ACTIONS = {
    FILE_JIO_GST: 'FILE_JIO_GST',
    FILE_JIO_GST_RESPONSE: 'FILE_JIO_GST_RESPONSE',
    FILE_GSTR3B: 'FILE_GSTR3B',
    FILE_GSTR3B_RESPONSE: 'FILE_GSTR3B_RESPONSE',
};
