export const SETTINGS_FINANCIAL_YEAR_ACTIONS = {
    GET_ALL_FINANCIAL_YEARS: 'GET_ALL_FINANCIAL_YEARS',
    GET_ALL_FINANCIAL_YEARS_RESPONSE: 'GET_ALL_FINANCIAL_YEARS_RESPONSE',
    LOCK_FINANCIAL_YEAR: 'LOCK_FINANCIAL_YEAR',
    LOCK_FINANCIAL_YEAR_RESPONSE: 'LOCK_FINANCIAL_YEAR_RESPONSE',
    UNLOCK_FINANCIAL_YEAR: 'UNLOCK_FINANCIAL_YEAR',
    UNLOCK_FINANCIAL_YEAR_RESPONSE: 'UNLOCK_FINANCIAL_YEAR_RESPONSE',
    SWITCH_FINANCIAL_YEAR: 'SWITCH_FINANCIAL_YEAR',
    SWITCH_FINANCIAL_YEAR_RESPONSE: 'SWITCH_FINANCIAL_YEAR_RESPONSE',
    ADD_FINANCIAL_YEAR: 'ADD_FINANCIAL_YEAR',
    ADD_FUTURE_FINANCIAL_YEAR: 'ADD_FUTURE_FINANCIAL_YEAR',
    ADD_FINANCIAL_YEAR_RESPONSE: 'ADD_FINANCIAL_YEAR_RESPONSE',
    UPDATE_FINANCIAL_YEAR_PERIOD: 'UPDATE_FINANCIAL_YEAR_PERIOD',
    UPDATE_FINANCIAL_YEAR_PERIOD_RESPONSE: 'UPDATE_FINANCIAL_YEAR_PERIOD_RESPONSE'
};
