export const SETTINGS_FINANCIAL_YEAR_ACTIONS = {
    GET_FINANCIAL_YEAR: 'GET_FINANCIAL_YEAR',
    GET_FINANCIAL_YEAR_RESPONSE: 'GET_FINANCIAL_YEAR_RESPONSE',
    UPDATE_FINANCIAL_YEAR: 'UPDATE_FINANCIAL_YEAR',
    UPDATE_FINANCIAL_YEAR_RESPONSE: 'UPDATE_FINANCIAL_YEAR_RESPONSE',
    CREATE_FINANCIAL_YEAR: 'CREATE_FINANCIAL_YEAR',
    CREATE_FINANCIAL_YEAR_RESPONSE: 'CREATE_FINANCIAL_YEAR_RESPONSE',
    GET_FINANCIAL_YEAR_LIMITS_RESPONSE: 'GET_FINANCIAL_YEAR_LIMITS_RESPONSE'
};
