    /** Interface for country data */
export interface Country {
    /** Country name in English */
        name: string;
    /** ISO 3166-1 alpha-2 country code */
        code: string;
    /** International dialing code */
        dialCode: string;
    /** Unicode flag emoji */
        flag: string;
    /** Path to flag image */
    flagImage?: string;
    /** Country name in native language */
        nativeName: string;
    /** Regex pattern for mobile number validation */
        pattern: RegExp;
    /** Placeholder text for input field */
        placeholder: string;
    /** Minimum number length */
        minLength: number;
    /** Maximum number length */
        maxLength: number;
    }
    /** Comprehensive list of all countries with their telephone data */
export const COUNTRIES_DATA: Country[] = [
    {
        name: 'United States',
        code: 'US',
        dialCode: '+1',
        flag: '🇺🇸',
        flagImage: 'assets/images/flags/us.png',
        nativeName: 'United States',
        pattern: /^[2-9]\d{2}[2-9]\d{6}$/,
        placeholder: 'Enter 10-digit phone number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'United Kingdom',
        code: 'GB',
        dialCode: '+44',
        flag: '🇬🇧',
        flagImage: 'assets/images/flags/gb.png',
        nativeName: '+44',
        pattern: /^([1-9]\d{8,9})$/,
        placeholder: 'Enter UK phone number',
        minLength: 9,
        maxLength: 10
    },
    // A
    {
        name: 'Afghanistan',
        code: 'AF',
        dialCode: '+93',
        flag: '🇦🇫',
        flagImage: 'assets/images/flags/af.png',
        nativeName: 'افغانستان',
        pattern: /^7\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Albania',
        code: 'AL',
        dialCode: '+355',
        flag: '🇦🇱',
        flagImage: 'assets/images/flags/af.png',
        nativeName: '+355',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Algeria',
        code: 'DZ',
        dialCode: '+213',
        flag: '🇩🇿',
        flagImage: 'assets/images/flags/dz.png',
        nativeName: '+213',
        pattern: /^[567]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'American Samoa',
        code: 'AS',
        dialCode: '+1684',
        flag: '🇦🇸',
        flagImage: 'assets/images/flags/as.png',
        nativeName: '+1684',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Andorra',
        code: 'AD',
        dialCode: '+376',
        flag: '🇦🇩',
        flagImage: 'assets/images/flags/ad.png',
        nativeName: '+376',
        pattern: /^[36]\d{5}$/,
        placeholder: 'Enter 6-digit mobile number',
        minLength: 6,
        maxLength: 6
    },
    {
        name: 'Angola',
        code: 'AO',
        dialCode: '+244',
        flag: '🇦🇴',
        flagImage: 'assets/images/flags/ao.png',
        nativeName: '+244',
        pattern: /^9\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Anguilla',
        code: 'AI',
        dialCode: '+1264',
        flag: '🇦🇮',
        flagImage: 'assets/images/flags/ai.png',
        nativeName: '+1264',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Antigua and Barbuda',
        code: 'AG',
        dialCode: '+1268',
        flag: '🇦🇬',
        flagImage: 'assets/images/flags/ag.png',
        nativeName: '+1268',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Argentina',
        code: 'AR',
        dialCode: '+54',
        flag: '🇦🇷',
        flagImage: 'assets/images/flags/ar.png',
        nativeName: '+54',
        pattern: /^9\d{8,10}$/,
        placeholder: 'Enter 9-11 digit mobile number',
        minLength: 9,
        maxLength: 11
    },
    {
        name: 'Armenia',
        code: 'AM',
        dialCode: '+374',
        flag: '🇦🇲',
        flagImage: 'assets/images/flags/am.png',
        nativeName: '+374',
        pattern: /^[479]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Aruba',
        code: 'AW',
        dialCode: '+297',
        flag: '🇦🇼',
        flagImage: 'assets/images/flags/aw.png',
        nativeName: '+297',
        pattern: /^[569]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Australia',
        code: 'AU',
        dialCode: '+61',
        flag: '🇦🇺',
        flagImage: 'assets/images/flags/au.png',
        nativeName: '+61',
        pattern: /^[2-478]\d{8}$/,
        placeholder: 'Enter 9-digit phone number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Austria',
        code: 'AT',
        dialCode: '+43',
        flag: '🇦🇹',
        flagImage: 'assets/images/flags/at.png',
        nativeName: '+43',
        pattern: /^6\d{8,12}$/,
        placeholder: 'Enter 9-13 digit mobile number',
        minLength: 9,
        maxLength: 13
    },
    {
        name: 'Azerbaijan',
        code: 'AZ',
        dialCode: '+994',
        flag: '🇦🇿',
        flagImage: 'assets/images/flags/az.png',
        nativeName: '+994',
        pattern: /^[4567]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // B
    {
        name: 'Bahamas',
        code: 'BS',
        dialCode: '+1242',
        flag: '🇧🇸',
        flagImage: 'assets/images/flags/bs.png',
        nativeName: '+1242',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Bahrain',
        code: 'BH',
        dialCode: '+973',
        flag: '🇧🇭',
        flagImage: 'assets/images/flags/bh.png',
        nativeName: '+973',
        pattern: /^[3679]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Bangladesh',
        code: 'BD',
        dialCode: '+880',
        flag: '🇧🇩',
        flagImage: 'assets/images/flags/bd.png',
        nativeName: '+880',
        pattern: /^1[3-9]\d{8}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Barbados',
        code: 'BB',
        dialCode: '+1246',
        flag: '🇧🇧',
        flagImage: 'assets/images/flags/bb.png',
        nativeName: '+1246',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Belarus',
        code: 'BY',
        dialCode: '+375',
        flag: '🇧🇾',
        flagImage: 'assets/images/flags/by.png',
        nativeName: '+375',
        pattern: /^[2-4]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Belgium',
        code: 'BE',
        dialCode: '+32',
        flag: '🇧🇪',
        flagImage: 'assets/images/flags/be.png',
        nativeName: '+32',
        pattern: /^4\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Belize',
        code: 'BZ',
        dialCode: '+501',
        flag: '🇧🇿',
        flagImage: 'assets/images/flags/bz.png',
        nativeName: '+501',
        pattern: /^6\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Benin',
        code: 'BJ',
        dialCode: '+229',
        flag: '🇧🇯',
        flagImage: 'assets/images/flags/bj.png',
        nativeName: '+229',
        pattern: /^[679]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Bermuda',
        code: 'BM',
        dialCode: '+1441',
        flag: '🇧🇲',
        flagImage: 'assets/images/flags/bm.png',
        nativeName: '+1441',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Bhutan',
        code: 'BT',
        dialCode: '+975',
        flag: '🇧🇹',
        flagImage: 'assets/images/flags/bt.png',
        nativeName: '+975',
        pattern: /^[17]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Bolivia',
        code: 'BO',
        dialCode: '+591',
        flag: '🇧🇴',
        flagImage: 'assets/images/flags/bo.png',
        nativeName: '+591',
        pattern: /^[67]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Bosnia and Herzegovina',
        code: 'BA',
        dialCode: '+387',
        flag: '🇧🇦',
        flagImage: 'assets/images/flags/ba.png',
        nativeName: '+387',
        pattern: /^6\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Botswana',
        code: 'BW',
        dialCode: '+267',
        flag: '🇧🇼',
        flagImage: 'assets/images/flags/bw.png',
        nativeName: '+267',
        pattern: /^7\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Brazil',
        code: 'BR',
        dialCode: '+55',
        flag: '🇧🇷',
        flagImage: 'assets/images/flags/br.png',
        nativeName: '+55',
        pattern: /^([1-9]\d{8,10})$/,
        placeholder: 'Enter Brazilian phone number',
        minLength: 9,
        maxLength: 11
    },
    {
        name: 'British Virgin Islands',
        code: 'VG',
        dialCode: '+1284',
        flag: '🇻🇬',
        flagImage: 'assets/images/flags/vg.png',
        nativeName: 'British Virgin Islands',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Brunei',
        code: 'BN',
        dialCode: '+673',
        flag: '🇧🇳',
        flagImage: 'assets/images/flags/bn.png',
        nativeName: '+673',
        pattern: /^[78]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Bulgaria',
        code: 'BG',
        dialCode: '+359',
        flag: '🇧🇬',
        flagImage: 'assets/images/flags/bg.png',
        nativeName: '+359',
        pattern: /^[89]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Burkina Faso',
        code: 'BF',
        dialCode: '+226',
        flag: '🇧🇫',
        flagImage: 'assets/images/flags/bf.png',
        nativeName: '+226',
        pattern: /^[67]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Burundi',
        code: 'BI',
        dialCode: '+257',
        flag: '🇧🇮',
        flagImage: 'assets/images/flags/bi.png',
        nativeName: '+257',
        pattern: /^[267]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    // C
    {
        name: 'Cambodia',
        code: 'KH',
        dialCode: '+855',
        flag: '🇰🇭',
        flagImage: 'assets/images/flags/kh.png',
        nativeName: '+855',
        pattern: /^[1-9]\d{7,8}$/,
        placeholder: 'Enter 8-9 digit mobile number',
        minLength: 8,
        maxLength: 9
    },
    {
        name: 'Cameroon',
        code: 'CM',
        dialCode: '+237',
        flag: '🇨🇲',
        flagImage: 'assets/images/flags/cm.png',
        nativeName: '+237',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Canada',
        code: 'CA',
        dialCode: '+1',
        flag: '🇨🇦',
        flagImage: 'assets/images/flags/ca.png',
        nativeName: 'Canada',
        pattern: /^[2-9]\d{2}[2-9]\d{6}$/,
        placeholder: 'Enter 10-digit phone number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Cape Verde',
        code: 'CV',
        dialCode: '+238',
        flag: '🇨🇻',
        flagImage: 'assets/images/flags/cv.png',
        nativeName: '+238',
        pattern: /^[59]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Cayman Islands',
        code: 'KY',
        dialCode: '+1345',
        flag: '🇰🇾',
        flagImage: 'assets/images/flags/ky.png',
        nativeName: '+1345',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Central African Republic',
        code: 'CF',
        dialCode: '+236',
        flag: '🇨🇫',
        flagImage: 'assets/images/flags/cf.png',
        nativeName: '+236',
        pattern: /^7\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Chad',
        code: 'TD',
        dialCode: '+235',
        flag: '🇹🇩',
        flagImage: 'assets/images/flags/td.png',
        nativeName: '+235',
        pattern: /^[679]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Chile',
        code: 'CL',
        dialCode: '+56',
        flag: '🇨🇱',
        flagImage: 'assets/images/flags/cl.png',
        nativeName: '+56',
        pattern: /^9\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'China',
        code: 'CN',
        dialCode: '+86',
        flag: '🇨🇳',
        flagImage: 'assets/images/flags/cn.png',
        nativeName: '+86',
        pattern: /^1[3-9]\d{9}$/,
        placeholder: 'Enter 11-digit mobile number',
        minLength: 11,
        maxLength: 11
    },
    {
        name: 'Colombia',
        code: 'CO',
        dialCode: '+57',
        flag: '🇨🇴',
        flagImage: 'assets/images/flags/co.png',
        nativeName: '+57',
        pattern: /^3\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Comoros',
        code: 'KM',
        dialCode: '+269',
        flag: '🇰🇲',
        flagImage: 'assets/images/flags/km.png',
        nativeName: '+269',
        pattern: /^[379]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Congo',
        code: 'CG',
        dialCode: '+242',
        flag: '🇨🇬',
        flagImage: 'assets/images/flags/cg.png',
        nativeName: '+242',
        pattern: /^0[467]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Democratic Republic of the Congo',
        code: 'CD',
        dialCode: '+243',
        flag: '🇨🇩',
        flagImage: 'assets/images/flags/cd.png',
        nativeName: '+243',
        pattern: /^[89]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Cook Islands',
        code: 'CK',
        dialCode: '+682',
        flag: '🇨🇰',
        flagImage: 'assets/images/flags/ck.png',
        nativeName: '+682',
        pattern: /^\d{5}$/,
        placeholder: 'Enter 5-digit mobile number',
        minLength: 5,
        maxLength: 5
    },
    {
        name: 'Costa Rica',
        code: 'CR',
        dialCode: '+506',
        flag: '🇨🇷',
        flagImage: 'assets/images/flags/cr.png',
        nativeName: '+506',
        pattern: /^[678]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Croatia',
        code: 'HR',
        dialCode: '+385',
        flag: '🇭🇷',
        flagImage: 'assets/images/flags/hr.png',
        nativeName: '+385',
        pattern: /^9\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Cuba',
        code: 'CU',
        dialCode: '+53',
        flag: '🇨🇺',
        flagImage: 'assets/images/flags/cu.png',
        nativeName: '+53',
        pattern: /^5\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Cyprus',
        code: 'CY',
        dialCode: '+357',
        flag: '🇨🇾',
        flagImage: 'assets/images/flags/cy.png',
        nativeName: '+357',
        pattern: /^9\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Czech Republic',
        code: 'CZ',
        dialCode: '+420',
        flag: '🇨🇿',
        flagImage: 'assets/images/flags/cz.png',
        nativeName: '+420',
        pattern: /^[67]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // D
    {
        name: 'Denmark',
        code: 'DK',
        dialCode: '+45',
        flag: '🇩🇰',
        flagImage: 'assets/images/flags/dk.png',
        nativeName: '+45',
        pattern: /^[2-9]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Djibouti',
        code: 'DJ',
        dialCode: '+253',
        flag: '🇩🇯',
        flagImage: 'assets/images/flags/dj.png',
        nativeName: '+253',
        pattern: /^77\d{6}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Dominica',
        code: 'DM',
        dialCode: '+1767',
        flag: '🇩🇲',
        flagImage: 'assets/images/flags/dm.png',
        nativeName: '+1767',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Dominican Republic',
        code: 'DO',
        dialCode: '+1809',
        flag: '🇩🇴',
        flagImage: 'assets/images/flags/do.png',
        nativeName: '+1',
        pattern: /^\d{10}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    // E
    {
        name: 'Ecuador',
        code: 'EC',
        dialCode: '+593',
        flag: '🇪🇨',
        flagImage: 'assets/images/flags/ec.png',
        nativeName: '+593',
        pattern: /^9\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Egypt',
        code: 'EG',
        dialCode: '+20',
        flag: '🇪🇬',
        flagImage: 'assets/images/flags/eg.png',
        nativeName: '+20',
        pattern: /^1[0125]\d{8}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'El Salvador',
        code: 'SV',
        dialCode: '+503',
        flag: '🇸🇻',
        flagImage: 'assets/images/flags/sv.png',
        nativeName: '+503',
        pattern: /^[67]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Equatorial Guinea',
        code: 'GQ',
        dialCode: '+240',
        flag: '🇬🇶',
        flagImage: 'assets/images/flags/gq.png',
        nativeName: '+240',
        pattern: /^[26]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Eritrea',
        code: 'ER',
        dialCode: '+291',
        flag: '🇪🇷',
        flagImage: 'assets/images/flags/er.png',
        nativeName: '+291',
        pattern: /^[17]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Estonia',
        code: 'EE',
        dialCode: '+372',
        flag: '🇪🇪',
        flagImage: 'assets/images/flags/ee.png',
        nativeName: '+372',
        pattern: /^5\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Ethiopia',
        code: 'ET',
        dialCode: '+251',
        flag: '🇪🇹',
        flagImage: 'assets/images/flags/et.png',
        nativeName: '+251',
        pattern: /^9\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // F
    {
        name: 'Falkland Islands',
        code: 'FK',
        dialCode: '+500',
        flag: '🇫🇰',
        flagImage: 'assets/images/flags/fk.png',
        nativeName: 'Falkland Islands',
        pattern: /^\d{5}$/,
        placeholder: 'Enter 5-digit mobile number',
        minLength: 5,
        maxLength: 5
    },
    {
        name: 'Faroe Islands',
        code: 'FO',
        dialCode: '+298',
        flag: '🇫🇴',
        flagImage: 'assets/images/flags/fo.png',
        nativeName: '+298',
        pattern: /^\d{6}$/,
        placeholder: 'Enter 6-digit mobile number',
        minLength: 6,
        maxLength: 6
    },
    {
        name: 'Fiji',
        code: 'FJ',
        dialCode: '+679',
        flag: '🇫🇯',
        flagImage: 'assets/images/flags/fj.png',
        nativeName: '+679',
        pattern: /^[79]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Finland',
        code: 'FI',
        dialCode: '+358',
        flag: '🇫🇮',
        flagImage: 'assets/images/flags/fi.png',
        nativeName: '+358',
        pattern: /^4\d{8,9}$/,
        placeholder: 'Enter 9-10 digit mobile number',
        minLength: 9,
        maxLength: 10
    },
    {
        name: 'France',
        code: 'FR',
        dialCode: '+33',
        flag: '🇫🇷',
        flagImage: 'assets/images/flags/fr.png',
        nativeName: '+33',
        pattern: /^[67]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'French Guiana',
        code: 'GF',
        dialCode: '+594',
        flag: '🇬🇫',
        flagImage: 'assets/images/flags/gf.png',
        nativeName: '+594',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'French Polynesia',
        code: 'PF',
        dialCode: '+689',
        flag: '🇵🇫',
        flagImage: 'assets/images/flags/pf.png',
        nativeName: '+689',
        pattern: /^8\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    // G
    {
        name: 'Gabon',
        code: 'GA',
        dialCode: '+241',
        flag: '🇬🇦',
        flagImage: 'assets/images/flags/ga.png',
        nativeName: '+241',
        pattern: /^0[67]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Gambia',
        code: 'GM',
        dialCode: '+220',
        flag: '🇬🇲',
        flagImage: 'assets/images/flags/gm.png',
        nativeName: '+220',
        pattern: /^[379]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Georgia',
        code: 'GE',
        dialCode: '+995',
        flag: '🇬🇪',
        flagImage: 'assets/images/flags/ge.png',
        nativeName: '+995',
        pattern: /^5\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Germany',
        code: 'DE',
        dialCode: '+49',
        flag: '🇩🇪',
        flagImage: 'assets/images/flags/de.png',
        nativeName: '+49',
        pattern: /^1[5-7]\d{8,9}$/,
        placeholder: 'Enter 10-11 digit mobile number',
        minLength: 10,
        maxLength: 11
    },
    {
        name: 'Ghana',
        code: 'GH',
        dialCode: '+233',
        flag: '🇬🇭',
        flagImage: 'assets/images/flags/gh.png',
        nativeName: '+233',
        pattern: /^[25]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Gibraltar',
        code: 'GI',
        dialCode: '+350',
        flag: '🇬🇮',
        flagImage: 'assets/images/flags/gi.png',
        nativeName: '+350',
        pattern: /^[56]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Greece',
        code: 'GR',
        dialCode: '+30',
        flag: '🇬🇷',
        flagImage: 'assets/images/flags/gr.png',
        nativeName: '+30',
        pattern: /^69\d{8}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Greenland',
        code: 'GL',
        dialCode: '+299',
        flag: '🇬🇱',
        flagImage: 'assets/images/flags/gl.png',
        nativeName: '+299',
        pattern: /^\d{6}$/,
        placeholder: 'Enter 6-digit mobile number',
        minLength: 6,
        maxLength: 6
    },
    {
        name: 'Grenada',
        code: 'GD',
        dialCode: '+1473',
        flag: '🇬🇩',
        flagImage: 'assets/images/flags/gd.png',
        nativeName: '+1473',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Guadeloupe',
        code: 'GP',
        dialCode: '+590',
        flag: '🇬🇵',
        flagImage: 'assets/images/flags/gp.png',
        nativeName: '+590',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Guam',
        code: 'GU',
        dialCode: '+1671',
        flag: '🇬🇺',
        flagImage: 'assets/images/flags/gu.png',
        nativeName: 'Guam',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Guatemala',
        code: 'GT',
        dialCode: '+502',
        flag: '🇬🇹',
        flagImage: 'assets/images/flags/gt.png',
        nativeName: '+502',
        pattern: /^[45]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Guernsey',
        code: 'GG',
        dialCode: '+44',
        flag: '🇬🇬',
        flagImage: 'assets/images/flags/gg.png',
        nativeName: '+44',
        pattern: /^7\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Guinea',
        code: 'GN',
        dialCode: '+224',
        flag: '🇬🇳',
        flagImage: 'assets/images/flags/gn.png',
        nativeName: '+224',
        pattern: /^6\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Guinea-Bissau',
        code: 'GW',
        dialCode: '+245',
        flag: '🇬🇼',
        flagImage: 'assets/images/flags/gw.png',
        nativeName: '+245',
        pattern: /^[67]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Guyana',
        code: 'GY',
        dialCode: '+592',
        flag: '🇬🇾',
        flagImage: 'assets/images/flags/gy.png',
        nativeName: '+592',
        pattern: /^6\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    // H
    {
        name: 'Haiti',
        code: 'HT',
        dialCode: '+509',
        flag: '🇭🇹',
        flagImage: 'assets/images/flags/ht.png',
        nativeName: '+509',
        pattern: /^[34]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Honduras',
        code: 'HN',
        dialCode: '+504',
        flag: '🇭🇳',
        flagImage: 'assets/images/flags/hn.png',
        nativeName: '+504',
        pattern: /^[389]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Hong Kong',
        code: 'HK',
        dialCode: '+852',
        flag: '🇭🇰',
        flagImage: 'assets/images/flags/hk.png',
        nativeName: '+852',
        pattern: /^[5-9]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Hungary',
        code: 'HU',
        dialCode: '+36',
        flag: '🇭🇺',
        flagImage: 'assets/images/flags/hu.png',
        nativeName: '+36',
        pattern: /^[1-9]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // I
    {
        name: 'Iceland',
        code: 'IS',
        dialCode: '+354',
        flag: '🇮🇸',
        flagImage: 'assets/images/flags/is.png',
        nativeName: '+354',
        pattern: /^[6-9]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'India',
        code: 'IN',
        dialCode: '+91',
        flag: '🇮🇳',
        flagImage: 'assets/images/flags/in.png',
        nativeName: '+91',
        pattern: /^[6-9]\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Indonesia',
        code: 'ID',
        dialCode: '+62',
        flag: '🇮🇩',
        flagImage: 'assets/images/flags/id.png',
        nativeName: '+62',
        pattern: /^8\d{9,11}$/,
        placeholder: 'Enter 10-12 digit mobile number',
        minLength: 10,
        maxLength: 12
    },
    {
        name: 'Iran',
        code: 'IR',
        dialCode: '+98',
        flag: '🇮🇷',
        flagImage: 'assets/images/flags/ir.png',
        nativeName: '+98',
        pattern: /^9\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Iraq',
        code: 'IQ',
        dialCode: '+964',
        flag: '🇮🇶',
        flagImage: 'assets/images/flags/iq.png',
        nativeName: '+964',
        pattern: /^7[5-9]\d{8}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Ireland',
        code: 'IE',
        dialCode: '+353',
        flag: '🇮🇪',
        flagImage: 'assets/images/flags/ie.png',
        nativeName: '+353',
        pattern: /^8[356789]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Isle of Man',
        code: 'IM',
        dialCode: '+44',
        flag: '🇮🇲',
        flagImage: 'assets/images/flags/im.png',
        nativeName: '+44',
        pattern: /^7\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Israel',
        code: 'IL',
        dialCode: '+972',
        flag: '🇮🇱',
        flagImage: 'assets/images/flags/il.png',
        nativeName: '+972',
        pattern: /^5[0-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Italy',
        code: 'IT',
        dialCode: '+39',
        flag: '🇮🇹',
        flagImage: 'assets/images/flags/it.png',
        nativeName: '+39',
        pattern: /^3\d{8,9}$/,
        placeholder: 'Enter 9-10 digit mobile number',
        minLength: 9,
        maxLength: 10
    },
    {
        name: 'Ivory Coast',
        code: 'CI',
        dialCode: '+225',
        flag: '🇨🇮',
        flagImage: 'assets/images/flags/ci.png',
        nativeName: 'Côte d\'Ivoire',
        pattern: /^[0-9]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    // J
    {
        name: 'Jamaica',
        code: 'JM',
        dialCode: '+1876',
        flag: '🇯🇲',
        flagImage: 'assets/images/flags/jm.png',
        nativeName: '+1876',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Japan',
        code: 'JP',
        dialCode: '+81',
        flag: '🇯🇵',
        flagImage: 'assets/images/flags/jp.png',
        nativeName: '+81',
        pattern: /^[789]0\d{8}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Jersey',
        code: 'JE',
        dialCode: '+44',
        flag: '🇯🇪',
        flagImage: 'assets/images/flags/je.png',
        nativeName: '+44',
        pattern: /^7\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Jordan',
        code: 'JO',
        dialCode: '+962',
        flag: '🇯🇴',
        flagImage: 'assets/images/flags/jo.png',
        nativeName: '+962',
        pattern: /^7[789]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // K
    {
        name: 'Kazakhstan',
        code: 'KZ',
        dialCode: '+7',
        flag: '🇰🇿',
        flagImage: 'assets/images/flags/kz.png',
        nativeName: '+7',
        pattern: /^7\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Kenya',
        code: 'KE',
        dialCode: '+254',
        flag: '🇰🇪',
        flagImage: 'assets/images/flags/ke.png',
        nativeName: '+254',
        pattern: /^7\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Kiribati',
        code: 'KI',
        dialCode: '+686',
        flag: '🇰🇮',
        flagImage: 'assets/images/flags/ki.png',
        nativeName: '+686',
        pattern: /^\d{5}$/,
        placeholder: 'Enter 5-digit mobile number',
        minLength: 5,
        maxLength: 5
    },
    {
        name: 'Kosovo',
        code: 'XK',
        dialCode: '+383',
        flag: '🇽🇰',
        flagImage: 'assets/images/flags/xk.png',
        nativeName: '+383',
        pattern: /^4[3-9]\d{6}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Kuwait',
        code: 'KW',
        dialCode: '+965',
        flag: '🇰🇼',
        flagImage: 'assets/images/flags/kw.png',
        nativeName: '+965',
        pattern: /^[569]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Kyrgyzstan',
        code: 'KG',
        dialCode: '+996',
        flag: '🇰🇬',
        flagImage: 'assets/images/flags/kg.png',
        nativeName: '+996',
        pattern: /^[57]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // L
    {
        name: 'Laos',
        code: 'LA',
        dialCode: '+856',
        flag: '🇱🇦',
        flagImage: 'assets/images/flags/la.png',
        nativeName: '+856',
        pattern: /^20\d{8}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Latvia',
        code: 'LV',
        dialCode: '+371',
        flag: '🇱🇻',
        flagImage: 'assets/images/flags/lv.png',
        nativeName: '+371',
        pattern: /^2\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Lebanon',
        code: 'LB',
        dialCode: '+961',
        flag: '🇱🇧',
        flagImage: 'assets/images/flags/lb.png',
        nativeName: '+961',
        pattern: /^[37]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Lesotho',
        code: 'LS',
        dialCode: '+266',
        flag: '🇱🇸',
        flagImage: 'assets/images/flags/ls.png',
        nativeName: '+266',
        pattern: /^[56]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Liberia',
        code: 'LR',
        dialCode: '+231',
        flag: '🇱🇷',
        flagImage: 'assets/images/flags/lr.png',
        nativeName: '+231',
        pattern: /^[4-9]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Libya',
        code: 'LY',
        dialCode: '+218',
        flag: '🇱🇾',
        flagImage: 'assets/images/flags/ly.png',
        nativeName: '+218',
        pattern: /^9[1-6]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Liechtenstein',
        code: 'LI',
        dialCode: '+423',
        flag: '🇱🇮',
        flagImage: 'assets/images/flags/li.png',
        nativeName: '+423',
        pattern: /^[67]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Lithuania',
        code: 'LT',
        dialCode: '+370',
        flag: '🇱🇹',
        flagImage: 'assets/images/flags/lt.png',
        nativeName: '+370',
        pattern: /^6\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Luxembourg',
        code: 'LU',
        dialCode: '+352',
        flag: '🇱🇺',
        flagImage: 'assets/images/flags/lu.png',
        nativeName: '+352',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // M
    {
        name: 'Macau',
        code: 'MO',
        dialCode: '+853',
        flag: '🇲🇴',
        flagImage: 'assets/images/flags/mo.png',
        nativeName: '+853',
        pattern: /^6\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Madagascar',
        code: 'MG',
        dialCode: '+261',
        flag: '🇲🇬',
        flagImage: 'assets/images/flags/mg.png',
        nativeName: '+261',
        pattern: /^3[234]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Malawi',
        code: 'MW',
        dialCode: '+265',
        flag: '🇲🇼',
        flagImage: 'assets/images/flags/mw.png',
        nativeName: '+265',
        pattern: /^[89]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Malaysia',
        code: 'MY',
        dialCode: '+60',
        flag: '🇲🇾',
        flagImage: 'assets/images/flags/my.png',
        nativeName: '+60',
        pattern: /^1[0-9]\d{7,8}$/,
        placeholder: 'Enter 9-10 digit mobile number',
        minLength: 9,
        maxLength: 10
    },
    {
        name: 'Maldives',
        code: 'MV',
        dialCode: '+960',
        flag: '🇲🇻',
        flagImage: 'assets/images/flags/mv.png',
        nativeName: '+960',
        pattern: /^[79]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Mali',
        code: 'ML',
        dialCode: '+223',
        flag: '🇲🇱',
        flagImage: 'assets/images/flags/ml.png',
        nativeName: '+223',
        pattern: /^[679]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Malta',
        code: 'MT',
        dialCode: '+356',
        flag: '🇲🇹',
        flagImage: 'assets/images/flags/mt.png',
        nativeName: '+356',
        pattern: /^[79]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Marshall Islands',
        code: 'MH',
        dialCode: '+692',
        flag: '🇲🇭',
        flagImage: 'assets/images/flags/mh.png',
        nativeName: '+692',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Martinique',
        code: 'MQ',
        dialCode: '+596',
        flag: '🇲🇶',
        flagImage: 'assets/images/flags/mq.png',
        nativeName: '+596',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Mauritania',
        code: 'MR',
        dialCode: '+222',
        flag: '🇲🇷',
        flagImage: 'assets/images/flags/mr.png',
        nativeName: '+222',
        pattern: /^[2-4]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Mauritius',
        code: 'MU',
        dialCode: '+230',
        flag: '🇲🇺',
        flagImage: 'assets/images/flags/mu.png',
        nativeName: '+230',
        pattern: /^5\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Mayotte',
        code: 'YT',
        dialCode: '+262',
        flag: '🇾🇹',
        flagImage: 'assets/images/flags/yt.png',
        nativeName: '+262',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Mexico',
        code: 'MX',
        dialCode: '+52',
        flag: '🇲🇽',
        flagImage: 'assets/images/flags/mx.png',
        nativeName: '+52',
        pattern: /^1\d{10}$/,
        placeholder: 'Enter 11-digit mobile number',
        minLength: 11,
        maxLength: 11
    },
    {
        name: 'Micronesia',
        code: 'FM',
        dialCode: '+691',
        flag: '🇫🇲',
        flagImage: 'assets/images/flags/fm.png',
        nativeName: '+691',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Moldova',
        code: 'MD',
        dialCode: '+373',
        flag: '🇲🇩',
        flagImage: 'assets/images/flags/md.png',
        nativeName: '+373',
        pattern: /^[67]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Monaco',
        code: 'MC',
        dialCode: '+377',
        flag: '🇲🇨',
        flagImage: 'assets/images/flags/mc.png',
        nativeName: '+377',
        pattern: /^[46]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Mongolia',
        code: 'MN',
        dialCode: '+976',
        flag: '🇲🇳',
        flagImage: 'assets/images/flags/mn.png',
        nativeName: '+976',
        pattern: /^[89]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Montenegro',
        code: 'ME',
        dialCode: '+382',
        flag: '🇲🇪',
        flagImage: 'assets/images/flags/me.png',
        nativeName: '+382',
        pattern: /^6\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Montserrat',
        code: 'MS',
        dialCode: 'MS',
        flag: '🇲🇸',
        flagImage: 'assets/images/flags/ms.png',
        nativeName: '+1664',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Morocco',
        code: 'MA',
        dialCode: '+212',
        flag: '🇲🇦',
        flagImage: 'assets/images/flags/ma.png',
        nativeName: '+212',
        pattern: /^[67]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Mozambique',
        code: 'MZ',
        dialCode: '+258',
        flag: '🇲🇿',
        flagImage: 'assets/images/flags/mz.png',
        nativeName: '+258',
        pattern: /^8[2-7]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Myanmar',
        code: 'MM',
        dialCode: '+95',
        flag: '🇲🇲',
        flagImage: 'assets/images/flags/mm.png',
        nativeName: '+95',
        pattern: /^9\d{8,9}$/,
        placeholder: 'Enter 9-10 digit mobile number',
        minLength: 9,
        maxLength: 10
    },
    // N
    {
        name: 'Namibia',
        code: 'NA',
        dialCode: '+264',
        flag: '🇳🇦',
        flagImage: 'assets/images/flags/na.png',
        nativeName: '+264',
        pattern: /^8[125]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Nauru',
        code: 'NR',
        dialCode: '+674',
        flag: '🇳🇷',
        flagImage: 'assets/images/flags/nr.png',
        nativeName: '+674',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Nepal',
        code: 'NP',
        dialCode: '+977',
        flag: '🇳🇵',
        flagImage: 'assets/images/flags/np.png',
        nativeName: '+977',
        pattern: /^98\d{8}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Netherlands',
        code: 'NL',
        dialCode: '+31',
        flag: '🇳🇱',
        flagImage: 'assets/images/flags/nl.png',
        nativeName: '+31',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'New Caledonia',
        code: 'NC',
        dialCode: '+687',
        flag: '🇳🇨',
        flagImage: 'assets/images/flags/nc.png',
        nativeName: '+687',
        pattern: /^\d{6}$/,
        placeholder: 'Enter 6-digit mobile number',
        minLength: 6,
        maxLength: 6
    },
    {
        name: 'New Zealand',
        code: 'NZ',
        dialCode: '+64',
        flag: '🇳🇿',
        flagImage: 'assets/images/flags/nz.png',
        nativeName: '+64',
        pattern: /^2[0-9]\d{7,8}$/,
        placeholder: 'Enter 9-10 digit mobile number',
        minLength: 9,
        maxLength: 10
    },
    {
        name: 'Nicaragua',
        code: 'NI',
        dialCode: '+505',
        flag: '🇳🇮',
        flagImage: 'assets/images/flags/ni.png',
        nativeName: '+505',
        pattern: /^[58]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Niger',
        code: 'NE',
        dialCode: '+227',
        flag: '🇳🇪',
        flagImage: 'assets/images/flags/ne.png',
        nativeName: '+227',
        pattern: /^[89]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Nigeria',
        code: 'NG',
        dialCode: '+234',
        flag: '🇳🇬',
        flagImage: 'assets/images/flags/ng.png',
        nativeName: '+234',
        pattern: /^[789]\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Niue',
        code: 'NU',
        dialCode: '+683',
        flag: '🇳🇺',
        flagImage: 'assets/images/flags/nu.png',
        nativeName: '+683',
        pattern: /^\d{4}$/,
        placeholder: 'Enter 4-digit mobile number',
        minLength: 4,
        maxLength: 4
    },
    {
        name: 'Norfolk Island',
        code: 'NF',
        dialCode: '+672',
        flag: '🇳🇫',
        flagImage: 'assets/images/flags/nf.png',
        nativeName: '+672',
        pattern: /^\d{6}$/,
        placeholder: 'Enter 6-digit mobile number',
        minLength: 6,
        maxLength: 6
    },
    {
        name: 'North Korea',
        code: 'KP',
        dialCode: '+850',
        flag: '🇰🇵',
        flagImage: 'assets/images/flags/kp.png',
        nativeName: '+850',
        pattern: /^19\d{8}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'North Macedonia',
        code: 'MK',
        dialCode: 'MK',
        flag: '🇲🇰',
        flagImage: 'assets/images/flags/mk.png',
        nativeName: '+389',
        pattern: /^7[0-9]\d{6}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Northern Mariana Islands',
        code: 'MP',
        dialCode: 'MP',
        flag: '🇲🇵',
        flagImage: 'assets/images/flags/mp.png',
        nativeName: '+1670',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Norway',
        code: 'NO',
        dialCode: '+47',
        flag: '🇳🇴',
        flagImage: 'assets/images/flags/no.png',
        nativeName: '+47',
        pattern: /^[49]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    // O
    {
        name: 'Oman',
        code: 'OM',
        dialCode: '+968',
        flag: '🇴🇲',
        flagImage: 'assets/images/flags/om.png',
        nativeName: '+968',
        pattern: /^[79]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    // P
    {
        name: 'Pakistan',
        code: 'PK',
        dialCode: '+92',
        flag: '🇵🇰',
        flagImage: 'assets/images/flags/pk.png',
        nativeName: '+92',
        pattern: /^3\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Palau',
        code: 'PW',
        dialCode: '+680',
        flag: '🇵🇼',
        flagImage: 'assets/images/flags/pw.png',
        nativeName: '+680',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Palestine',
        code: 'PS',
        dialCode: '+970',
        flag: '🇵🇸',
        flagImage: 'assets/images/flags/ps.png',
        nativeName: '+970',
        pattern: /^5[69]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Panama',
        code: 'PA',
        dialCode: '+507',
        flag: '🇵🇦',
        flagImage: 'assets/images/flags/pa.png',
        nativeName: '+507',
        pattern: /^[67]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Papua New Guinea',
        code: 'PG',
        dialCode: '+675',
        flag: '🇵🇬',
        flagImage: 'assets/images/flags/pg.png',
        nativeName: '+675',
        pattern: /^[789]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Paraguay',
        code: 'PY',
        dialCode: '+595',
        flag: '🇵🇾',
        flagImage: 'assets/images/flags/py.png',
        nativeName: '+595',
        pattern: /^9[6789]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Peru',
        code: 'PE',
        dialCode: '+51',
        flag: '🇵🇪',
        flagImage: 'assets/images/flags/pe.png',
        nativeName: '+51',
        pattern: /^9\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Philippines',
        code: 'PH',
        dialCode: '+63',
        flag: '🇵🇭',
        flagImage: 'assets/images/flags/ph.png',
        nativeName: '+63',
        pattern: /^9\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Pitcairn',
        code: 'PN',
        dialCode: '+64',
        flag: '🇵🇳',
        flagImage: 'assets/images/flags/pn.png',
        nativeName: '+64',
        pattern: /^\d{9}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Poland',
        code: 'PL',
        dialCode: '+48',
        flag: '🇵🇱',
        flagImage: 'assets/images/flags/pl.png',
        nativeName: '+48',
        pattern: /^[5-9]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Portugal',
        code: 'PT',
        dialCode: '+351',
        flag: '🇵🇹',
        flagImage: 'assets/images/flags/pt.png',
        nativeName: '+351',
        pattern: /^9[1236]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Puerto Rico',
        code: 'PR',
        dialCode: 'PR',
        flag: '🇵🇷',
        flagImage: 'assets/images/flags/pr.png',
        nativeName: '+1',
        pattern: /^\d{10}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    // Q
    {
        name: 'Qatar',
        code: 'QA',
        dialCode: '+974',
        flag: '🇶🇦',
        flagImage: 'assets/images/flags/qa.png',
        nativeName: '+974',
        pattern: /^[3567]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    // R
    {
        name: 'Réunion',
        code: 'RE',
        dialCode: '+262',
        flag: '🇷🇪',
        flagImage: 'assets/images/flags/re.png',
        nativeName: '+262',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Romania',
        code: 'RO',
        dialCode: '+40',
        flag: '🇷🇴',
        flagImage: 'assets/images/flags/ro.png',
        nativeName: '+40',
        pattern: /^7\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Russia',
        code: 'RU',
        dialCode: '+7',
        flag: '🇷🇺',
        flagImage: 'assets/images/flags/ru.png',
        nativeName: '+7',
        pattern: /^9\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Rwanda',
        code: 'RW',
        dialCode: '+250',
        flag: '🇷🇼',
        flagImage: 'assets/images/flags/rw.png',
        nativeName: '+250',
        pattern: /^7[238]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // S
    {
        name: 'Saint Helena',
        code: 'SH',
        dialCode: '+290',
        flag: '🇸🇭',
        flagImage: 'assets/images/flags/sh.png',
        nativeName: '+290',
        pattern: /^\d{4}$/,
        placeholder: 'Enter 4-digit mobile number',
        minLength: 4,
        maxLength: 4
    },
    {
        name: 'Saint Kitts and Nevis',
        code: 'KN',
        dialCode: '+1869',
        flag: '🇰🇳',
        flagImage: 'assets/images/flags/kn.png',
        nativeName: '+1869',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Saint Lucia',
        code: 'LC',
        dialCode: '+1758',
        flag: '🇱🇨',
        flagImage: 'assets/images/flags/lc.png',
        nativeName: '+1758',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Saint Pierre and Miquelon',
        code: 'PM',
        dialCode: '+508',
        flag: '🇵🇲',
        flagImage: 'assets/images/flags/pm.png',
        nativeName: '+508',
        pattern: /^\d{6}$/,
        placeholder: 'Enter 6-digit mobile number',
        minLength: 6,
        maxLength: 6
    },
    {
        name: 'Saint Vincent and the Grenadines',
        code: 'VC',
        dialCode: '+1784',
        flag: '🇻🇨',
        flagImage: 'assets/images/flags/vc.png',
        nativeName: '+1784',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Samoa',
        code: 'WS',
        dialCode: '+685',
        flag: '🇼🇸',
        flagImage: 'assets/images/flags/ws.png',
        nativeName: '+685',
        pattern: /^[27]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'San Marino',
        code: 'SM',
        dialCode: '+378',
        flag: '🇸🇲',
        flagImage: 'assets/images/flags/sm.png',
        nativeName: '+378',
        pattern: /^6\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'São Tomé and Príncipe',
        code: 'ST',
        dialCode: '+239',
        flag: '🇸🇹',
        flagImage: 'assets/images/flags/st.png',
        nativeName: '+239',
        pattern: /^9\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Saudi Arabia',
        code: 'SA',
        dialCode: '+966',
        flag: '🇸🇦',
        flagImage: 'assets/images/flags/sa.png',
        nativeName: '+966',
        pattern: /^5\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Senegal',
        code: 'SN',
        dialCode: '+221',
        flag: '🇸🇳',
        flagImage: 'assets/images/flags/sn.png',
        nativeName: '+221',
        pattern: /^7[0678]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Serbia',
        code: 'RS',
        dialCode: '+381',
        flag: '🇷🇸',
        flagImage: 'assets/images/flags/rs.png',
        nativeName: '+381',
        pattern: /^6\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Seychelles',
        code: 'SC',
        dialCode: '+248',
        flag: '🇸🇨',
        flagImage: 'assets/images/flags/sc.png',
        nativeName: '+248',
        pattern: /^2[5-7]\d{5}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Sierra Leone',
        code: 'SL',
        dialCode: '+232',
        flag: '🇸🇱',
        flagImage: 'assets/images/flags/sl.png',
        nativeName: '+232',
        pattern: /^[2-9]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Singapore',
        code: 'SG',
        dialCode: '+65',
        flag: '🇸🇬',
        flagImage: 'assets/images/flags/sg.png',
        nativeName: '+65',
        pattern: /^[89]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Sint Maarten',
        code: 'SX',
        dialCode: '+1721',
        flag: '🇸🇽',
        flagImage: 'assets/images/flags/sx.png',
        nativeName: '+1721',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Slovakia',
        code: 'SK',
        dialCode: '+421',
        flag: '🇸🇰',
        flagImage: 'assets/images/flags/sk.png',
        nativeName: '+421',
        pattern: /^9\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Slovenia',
        code: 'SI',
        dialCode: '+386',
        flag: '🇸🇮',
        flagImage: 'assets/images/flags/si.png',
        nativeName: '+386',
        pattern: /^[3-7]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Solomon Islands',
        code: 'SB',
        dialCode: '+677',
        flag: '🇸🇧',
        flagImage: 'assets/images/flags/sb.png',
        nativeName: '+677',
        pattern: /^[7-9]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Somalia',
        code: 'SO',
        dialCode: '+252',
        flag: '🇸🇴',
        flagImage: 'assets/images/flags/so.png',
        nativeName: '+252',
        pattern: /^[67]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'South Africa',
        code: 'ZA',
        dialCode: '+27',
        flag: '🇿🇦',
        flagImage: 'assets/images/flags/za.png',
        nativeName: '+27',
        pattern: /^[6-8]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'South Korea',
        code: 'KR',
        dialCode: '+82',
        flag: '🇰🇷',
        flagImage: 'assets/images/flags/kr.png',
        nativeName: '+82',
        pattern: /^1[0-9]\d{7,8}$/,
        placeholder: 'Enter Korean phone number',
        minLength: 9,
        maxLength: 10
    },
    {
        name: 'South Sudan',
        code: 'SS',
        dialCode: '+211',
        flag: '🇸🇸',
        flagImage: 'assets/images/flags/ss.png',
        nativeName: '+211',
        pattern: /^9\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Spain',
        code: 'ES',
        dialCode: '+34',
        flag: '🇪🇸',
        flagImage: 'assets/images/flags/es.png',
        nativeName: '+34',
        pattern: /^[67]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Sri Lanka',
        code: 'LK',
        dialCode: '+94',
        flag: '🇱🇰',
        flagImage: 'assets/images/flags/lk.png',
        nativeName: '+94',
        pattern: /^7[0-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Sudan',
        code: 'SD',
        dialCode: '+249',
        flag: '🇸🇩',
        flagImage: 'assets/images/flags/sd.png',
        nativeName: '+249',
        pattern: /^9[0-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Suriname',
        code: 'SR',
        dialCode: '+597',
        flag: '🇸🇷',
        flagImage: 'assets/images/flags/sr.png',
        nativeName: '+597',
        pattern: /^[67]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Svalbard and Jan Mayen',
        code: 'SJ',
        dialCode: '+47',
        flag: '🇸🇯',
        flagImage: 'assets/images/flags/sj.png',
        nativeName: '+47',
        pattern: /^[49]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Swaziland',
        code: 'SZ',
        dialCode: '+268',
        flag: '🇸🇿',
        flagImage: 'assets/images/flags/sz.png',
        nativeName: '+268',
        pattern: /^[67]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Sweden',
        code: 'SE',
        dialCode: '+46',
        flag: '🇸🇪',
        flagImage: 'assets/images/flags/se.png',
        nativeName: '+46',
        pattern: /^7[0-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Switzerland',
        code: 'CH',
        dialCode: '+41',
        flag: '🇨🇭',
        flagImage: 'assets/images/flags/ch.png',
        nativeName: '+41',
        pattern: /^7[5-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Syria',
        code: 'SY',
        dialCode: '+963',
        flag: '🇸🇾',
        flagImage: 'assets/images/flags/sy.png',
        nativeName: '+963',
        pattern: /^9[3-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // T
    {
        name: 'Taiwan',
        code: 'TW',
        dialCode: '+886',
        flag: '🇹🇼',
        flagImage: 'assets/images/flags/tw.png',
        nativeName: '+886',
        pattern: /^9\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Tajikistan',
        code: 'TJ',
        dialCode: '+992',
        flag: '🇹🇯',
        flagImage: 'assets/images/flags/tj.png',
        nativeName: '+992',
        pattern: /^[39]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Tanzania',
        code: 'TZ',
        dialCode: '+255',
        flag: '🇹🇿',
        flagImage: 'assets/images/flags/tz.png',
        nativeName: '+255',
        pattern: /^[67]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Thailand',
        code: 'TH',
        dialCode: '+66',
        flag: '🇹🇭',
        flagImage: 'assets/images/flags/th.png',
        nativeName: '+66',
        pattern: /^[689]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Timor-Leste',
        code: 'TL',
        dialCode: '+670',
        flag: '🇹🇱',
        flagImage: 'assets/images/flags/tl.png',
        nativeName: '+670',
        pattern: /^7[7-9]\d{6}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Togo',
        code: 'TG',
        dialCode: '+228',
        flag: '🇹🇬',
        flagImage: 'assets/images/flags/tg.png',
        nativeName: '+228',
        pattern: /^9[0-9]\d{6}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Tokelau',
        code: 'TK',
        dialCode: '+690',
        flag: '🇹🇰',
        flagImage: 'assets/images/flags/tk.png',
        nativeName: '+690',
        pattern: /^\d{4}$/,
        placeholder: 'Enter 4-digit mobile number',
        minLength: 4,
        maxLength: 4
    },
    {
        name: 'Tonga',
        code: 'TO',
        dialCode: '+676',
        flag: '🇹🇴',
        flagImage: 'assets/images/flags/to.png',
        nativeName: '+676',
        pattern: /^[78]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Trinidad and Tobago',
        code: 'TT',
        dialCode: '+1868',
        flag: '🇹🇹',
        flagImage: 'assets/images/flags/tt.png',
        nativeName: '+1868',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Tunisia',
        code: 'TN',
        dialCode: '+216',
        flag: '🇹🇳',
        flagImage: 'assets/images/flags/tn.png',
        nativeName: '+216',
        pattern: /^[2459]\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Turkey',
        code: 'TR',
        dialCode: '+90',
        flag: '🇹🇷',
        flagImage: 'assets/images/flags/tr.png',
        nativeName: '+90',
        pattern: /^5\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Turkmenistan',
        code: 'TM',
        dialCode: '+993',
        flag: '🇹🇲',
        flagImage: 'assets/images/flags/tm.png',
        nativeName: '+993',
        pattern: /^6\d{7}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'Turks and Caicos Islands',
        code: 'TC',
        dialCode: 'TC',
        flag: '🇹🇨',
        flagImage: 'assets/images/flags/tc.png',
        nativeName: '+1649',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Tuvalu',
        code: 'TV',
        dialCode: '+688',
        flag: '🇹🇻',
        flagImage: 'assets/images/flags/tv.png',
        nativeName: '+688',
        pattern: /^\d{6}$/,
        placeholder: 'Enter 6-digit mobile number',
        minLength: 6,
        maxLength: 6
    },
    // U
    {
        name: 'Uganda',
        code: 'UG',
        dialCode: '+256',
        flag: '🇺🇬',
        flagImage: 'assets/images/flags/ug.png',
        nativeName: '+256',
        pattern: /^7[0-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Ukraine',
        code: 'UA',
        dialCode: '+380',
        flag: '🇺🇦',
        flagImage: 'assets/images/flags/ua.png',
        nativeName: '+380',
        pattern: /^[3-9]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'United Arab Emirates',
        code: 'AE',
        dialCode: '+971',
        flag: '🇦🇪',
        flagImage: 'assets/images/flags/ae.png',
        nativeName: '+971',
        pattern: /^5[0-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // { // Move this in top
    //     name: 'United Kingdom',
    //     code: 'GB',
    //     dialCode: '+44',
    //     flag: '🇬🇧',
    //     flagImage: 'assets/images/flags/gb.png',
    //     nativeName: '+44',
    //     pattern: /^7\d{9}$/,
    //     placeholder: 'Enter 10-digit mobile number',
    //     minLength: 10,
    //     maxLength: 10
    // },
    // { // Move this in top
    //     name: 'United States',
    //     code: 'US',
    //     dialCode: '+1',
    //     flag: '🇺🇸',
    //     flagImage: 'assets/images/flags/us.png',
    //     nativeName: '+1',
    //     pattern: /^\d{10}$/,
    //     placeholder: 'Enter 10-digit mobile number',
    //     minLength: 10,
    //     maxLength: 10
    // },
    {
        name: 'Uruguay',
        code: 'UY',
        dialCode: '+598',
        flag: '🇺🇾',
        flagImage: 'assets/images/flags/uy.png',
        nativeName: '+598',
        pattern: /^9[1-9]\d{6}$/,
        placeholder: 'Enter 8-digit mobile number',
        minLength: 8,
        maxLength: 8
    },
    {
        name: 'US Virgin Islands',
        code: 'VI',
        dialCode: 'VI',
        flag: '🇻🇮',
        flagImage: 'assets/images/flags/vi.png',
        nativeName: '+1340',
        pattern: /^\d{7}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Uzbekistan',
        code: 'UZ',
        dialCode: '+998',
        flag: '🇺🇿',
        flagImage: 'assets/images/flags/uz.png',
        nativeName: '+998',
        pattern: /^9[0-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // V
    {
        name: 'Vanuatu',
        code: 'VU',
        dialCode: '+678',
        flag: '🇻🇺',
        flagImage: 'assets/images/flags/vu.png',
        nativeName: '+678',
        pattern: /^[57]\d{6}$/,
        placeholder: 'Enter 7-digit mobile number',
        minLength: 7,
        maxLength: 7
    },
    {
        name: 'Vatican City',
        code: 'VA',
        dialCode: '+39',
        flag: '🇻🇦',
        flagImage: 'assets/images/flags/va.png',
        nativeName: '+39',
        pattern: /^3\d{8,9}$/,
        placeholder: 'Enter 9-10 digit mobile number',
        minLength: 9,
        maxLength: 10
    },
    {
        name: 'Venezuela',
        code: 'VE',
        dialCode: '+58',
        flag: '🇻🇪',
        flagImage: 'assets/images/flags/ve.png',
        nativeName: '+58',
        pattern: /^4\d{9}$/,
        placeholder: 'Enter 10-digit mobile number',
        minLength: 10,
        maxLength: 10
    },
    {
        name: 'Vietnam',
        code: 'VN',
        dialCode: '+84',
        flag: '🇻🇳',
        flagImage: 'assets/images/flags/vn.png',
        nativeName: '+84',
        pattern: /^[35789]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // W
    {
        name: 'Wallis and Futuna',
        code: 'WF',
        dialCode: '+681',
        flag: '🇼🇫',
        flagImage: 'assets/images/flags/wf.png',
        nativeName: '+681',
        pattern: /^\d{6}$/,
        placeholder: 'Enter 6-digit mobile number',
        minLength: 6,
        maxLength: 6
    },
    {
        name: 'Western Sahara',
        code: 'EH',
        dialCode: '+212',
        flag: '🇪🇭',
        flagImage: 'assets/images/flags/eh.png',
        nativeName: '+212',
        pattern: /^[67]\d{8}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // Y
    {
        name: 'Yemen',
        code: 'YE',
        dialCode: '+967',
        flag: '🇾🇪',
        flagImage: 'assets/images/flags/ye.png',
        nativeName: '+967',
        pattern: /^7[0137]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    // Z
    {
        name: 'Zambia',
        code: 'ZM',
        dialCode: '+260',
        flag: '🇿🇲',
        flagImage: 'assets/images/flags/zm.png',
        nativeName: '+260',
        pattern: /^9[567]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
    {
        name: 'Zimbabwe',
        code: 'ZW',
        dialCode: '+263',
        flag: '🇿🇼',
        flagImage: 'assets/images/flags/zw.png',
        nativeName: '+263',
        pattern: /^7[1-9]\d{7}$/,
        placeholder: 'Enter 9-digit mobile number',
        minLength: 9,
        maxLength: 9
    },
];
