export const HOME = {
    GET_RATIO_ANALYSIS: 'GET_RATIO_ANALYSIS',
    GET_RATIO_ANALYSIS_RESPONSE: 'GET_RATIO_ANALYSIS_RESPONSE',
    RESET_HOME_STATE: 'RESET_HOME_STATE',
    GET_REVENUE_GRAPH_TYPES: 'GET_REVENUE_GRAPH_TYPES',
    GET_REVENUE_GRAPH_TYPES_RESPONSE: 'GET_REVENUE_GRAPH_TYPES_RESPONSE'
};