export const SETTINGS_LINKED_ACCOUNTS_ACTIONS = {
    GET_LINKED_ACCOUNTS: 'GET_LINKED_ACCOUNTS',
    GET_LINKED_ACCOUNTS_RESPONSE: 'GET_LINKED_ACCOUNTS_RESPONSE',
    LINK_ACCOUNT: 'LINK_ACCOUNT',
    LINK_ACCOUNT_RESPONSE: 'LINK_ACCOUNT_RESPONSE',
    UNLINK_ACCOUNT: 'UNLINK_ACCOUNT',
    UNLINK_ACCOUNT_RESPONSE: 'UNLINK_ACCOUNT_RESPONSE'
};
