export const SETTINGS_PROFILE_ACTIONS = {
 GET_PROFILE_INFO: 'GET_PROFILE_INFO',
 GET_PROFILE_RESPONSE: 'GET_PROFILE_RESPONSE',
 UPDATE_PROFILE: 'UPDATE_PROFILE',
 UPDATE_PROFILE_RESPONSE: 'UPDATE_PROFILE_RESPONSE'
};
