const lodash = (window as any)._;
const {
    cloneDeep, each, reject, orderBy, isNull, flatten, sortBy, indexOf, remove, forEach, toArray, groupBy, difference, isUndefined, differenceBy, flattenDeep, union, omit, clone, without, isString, find, range, includes, uniq, isEmpty, isNumber, findIndex, concat, unionBy, last, sumBy, isArray, isEqual, uniqBy, some, intersection, forIn, pick, startsWith, get, debounce, isObject, slice, keys, set, has, values, merge, throttle, keyBy, countBy, minBy, maxBy, endsWith, map, filter
} = lodash;

export {
    cloneDeep,
    each,
    reject,
    orderBy,
    isNull,
    flatten,
    sortBy,
    indexOf,
    remove,
    forEach,
    toArray,
    groupBy,
    difference,
    isUndefined,
    differenceBy,
    flattenDeep,
    union,
    omit,
    clone,
    without,
    isString,
    find,
    range,
    includes,
    uniq,
    isEmpty,
    isNumber,
    findIndex,
    concat,
    unionBy,
    last,
    sumBy,
    isArray,
    isEqual,
    uniqBy,
    some,
    intersection,
    forIn,
    pick,
    startsWith,
    get,
    debounce,
    isObject,
    slice,
    keys,
    set,
    has,
    values,
    merge,
    throttle,
    keyBy,
    countBy,
    minBy,
    maxBy,
    endsWith,
    map,
    filter
};
