/* tslint:disable */
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/build-env.js for environment: local
// Generated at: 2025-12-31T07:36:30.232Z

import { ApplicationRef, NgModuleRef } from '@angular/core';
import { enableDebugTools } from '@angular/platform-browser';
import { Environment } from './model';

Error.stackTraceLimit = Infinity;

export const environment: Environment = {
    production: false,
    showDevModule: true,
    AppUrl: 'http://localhost:3000/',
    ApiUrl: 'https://apitest.giddh.com/',
    UkApiUrl: 'https://gbapi.giddh.com/',
    isElectron: false,
    APP_FOLDER: '',
    PORTAL_URL: 'https://master.d2n1i21e52r793.amplifyapp.com/',
    GOOGLE_CLIENT_ID: '641015054140-uj0d996itggsesgn4okg09jtn8mp0omu.apps.googleusercontent.com',
    GOOGLE_CLIENT_SECRET: '8htr7iQVXfZp_n87c99-jm7a',
    OTP_WIDGET_ID: '326a63733354393830313330',
    OTP_TOKEN_AUTH: '205968TmXguUAwoD633af103P1',
    RAZORPAY_KEY: 'rzp_test_aWNTpuTtWRMJ9u',
    PRODUCTION_ENV: false,
    STAGING_ENV: false,
    LOCAL_ENV: true,
    TEST_ENV: false,
    /** Angular debug tools in the dev console
     * https://github.com/angular/angular/blob/86405345b781a9dc2438c0fbe3e9409245647019/TOOLS_JS.md
     * @param modRef
     * @return {any}
     */
    decorateModuleRef(modRef: NgModuleRef<any>) {
        const appRef = modRef.injector.get(ApplicationRef);
        const cmpRef = appRef.components[0];

        let _ng = (<any>window).ng;
        enableDebugTools(cmpRef);
        (<any>window).ng.probe = _ng.probe;
        (<any>window).ng.coreTokens = _ng.coreTokens;
        return modRef;
    },
    ENV_PROVIDERS: []
};

// Set global variables for backward compatibility
(window as any).PRODUCTION_ENV = environment.production;
(window as any).STAGING_ENV = false;
(window as any).LOCAL_ENV = true;
(window as any).TEST_ENV = false;
(window as any).AppUrl = environment.AppUrl;
(window as any).ApiUrl = environment.ApiUrl;
(window as any).isElectron = environment.isElectron;
