export const INVOICE_ACTIONS = {
  GET_ALL_INVOICES: 'GET_ALL_INVOICES',
  GET_ALL_INVOICES_RESPONSE: 'GET_ALL_INVOICES_RESPONSE',
  GET_ALL_LEDGERS_FOR_INVOICE: 'GET_ALL_LEDGERS_FOR_INVOICE',
  GET_ALL_LEDGERS_FOR_INVOICE_RESPONSE: 'GET_ALL_LEDGERS_FOR_INVOICE_RESPONSE',
  PREVIEW_AND_GENERATE_INVOICE: 'PREVIEW_AND_GENERATE_INVOICE',
  PREVIEW_AND_GENERATE_INVOICE_RESPONSE: 'PREVIEW_AND_GENERATE_INVOICE_RESPONSE',
  GET_TEMPLATE_DETAILS: 'GET_TEMPLATE_DETAILS',
  GET_TEMPLATE_DETAILS_RESPONSE: 'GET_TEMPLATE_DETAILS_RESPONSE',
  GENERATE_BULK_INVOICE: 'GENERATE_BULK_INVOICE',
  GENERATE_BULK_INVOICE_RESPONSE: 'GENERATE_BULK_INVOICE_RESPONSE',
  ACTION_ON_INVOICE: 'ACTION_ON_INVOICE',
  ACTION_ON_INVOICE_RESPONSE: 'ACTION_ON_INVOICE_RESPONSE',
  SEND_MAIL: 'SEND_MAIL',
  SEND_MAIL_RESPONSE: 'SEND_MAIL_RESPONSE'
};
