export const INVOICE = {
  TEMPLATE: {
    SELECT_TEMPLATE: 'SELECT_TEMPLATE',
    GET_USER_TEMPLATES: 'GET_USER_TEMPLATES',
    SELECT_TEMPLATE_STATE: 'SELECT_TEMPLATE_STATE',
  },
  CONTENT: {
    SET_HEADING: 'SET_HEADING',
    SET_COLUMN_WIDTH: 'SET_COLUMN_WIDTH',
    SET_GSTIN: 'SET_GSTIN'
  }
};
