export const MANUFACTURING_ACTIONS = {
    MF_REPORT: 'MF_REPORT',
    MF_REPORT_RESPONSE: 'MF_REPORT_RESPONSE',
    GET_MF_ITEM_DETAILS: 'GET_MF_ITEM_DETAILS',
    GET_MF_ITEM_DETAILS_RESPONSE: 'GET_MF_ITEM_DETAILS_RESPONSE',
    CREATE_MF_ITEM: 'CREATE_MF_ITEM',
    CREATE_MF_ITEM_RESPONSE: 'CREATE_MF_ITEM_RESPONSE',
    UPDATE_MF_ITEM: 'UPDATE_MF_ITEM',
    UPDATE_MF_ITEM_RESPONSE: 'UPDATE_MF_ITEM_RESPONSE',
    DELETE_MF_ITEM: 'DELETE_MF_ITEM',
    DELETE_MF_ITEM_RESPONSE: 'DELETE_MF_ITEM_RESPONSE',
    GET_STOCK_WITH_RATE: 'GET_STOCK_WITH_RATE',
    GET_STOCK_WITH_RATE_RESPONSE: 'GET_STOCK_WITH_RATE_RESPONSE',
    SET_MF_ITEM_UNIQUENAME_IN_STORE: 'SET_MF_ITEM_UNIQUENAME_IN_STORE',
    REMOVE_MF_ITEM_UNIQUENAME_FROM_STORE: 'REMOVE_MF_ITEM_UNIQUENAME_FROM_STORE'
};
