export const SETTINGS_PROFILE_ACTIONS = {
    GET_PROFILE_INFO: 'GET_PROFILE_INFO',
    GET_PROFILE_RESPONSE: 'GET_PROFILE_RESPONSE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_RESPONSE: 'UPDATE_PROFILE_RESPONSE',
    PATCH_PROFILE: 'PATCH_PROFILE',
    RESET_PATCH_PROFILE: 'RESET_PATCH_PROFILE',
    PATCH_PROFILE_RESPONSE: 'PATCH_PROFILE_RESPONSE',
    GET_INVENTORY_INFO: 'GET_INVENTORY_INFO',
    GET_INVENTORY_RESPONSE: 'GET_INVENTORY_RESPONSE',
    UPDATE_INVENTORY: 'UPDATE_INVENTORY',
    UPDATE_INVENTORY_RESPONSE: 'UPDATE_INVENTORY_RESPONSE'
};
