export const GST_RECONCILE_ACTIONS = {
    GST_RECONCILE_OTP_REQUEST: 'GST_RECONCILE_OTP_REQUEST',
    GST_RECONCILE_OTP_RESPONSE: 'GST_RECONCILE_OTP_RESPONSE',
    GST_RECONCILE_INVOICE_REQUEST: 'GST_RECONCILE_INVOICE_REQUEST',
    GST_RECONCILE_INVOICE_RESPONSE: 'GST_RECONCILE_INVOICE_RESPONSE',
    GST_RECONCILE_VERIFY_OTP_REQUEST: 'GST_RECONCILE_VERIFY_OTP_REQUEST',
    GST_RECONCILE_VERIFY_OTP_RESPONSE: 'GST_RECONCILE_VERIFY_OTP_RESPONSE'
};

export const GSTR_ACTIONS = {
    GET_GSTR1_OVERVIEW: 'GET_GSTR1_OVERVIEW',
    GET_GSTR1_OVERVIEW_RESPONSE: 'GET_GSTR1_OVERVIEW_RESPONSE',
    GET_GSTR2_OVERVIEW: 'GET_GSTR2_OVERVIEW',
    GET_GSTR2_OVERVIEW_RESPONSE: 'GET_GSTR2_OVERVIEW_RESPONSE',
    GET_GSTR3B_OVERVIEW: 'GET_GSTR3B_OVERVIEW',
    GET_GSTR3B_OVERVIEW_RESPONSE: 'GET_GSTR3B_OVERVIEW_RESPONSE',
    GET_SUMMARY_TRANSACTIONS: 'GET_SUMMARY_TRANSACTIONS',
    GET_SUMMARY_TRANSACTIONS_RESPONSE: 'GET_SUMMARY_TRANSACTIONS_RESPONSE',
    GET_GSTR1_SUMMARY_DETAILS: 'GET_GSTR1_SUMMARY_DETAILS',
    GET_GSTR1_SUMMARY_DETAILS_RESPONSE: 'GET_GSTR1_SUMMARY_DETAILS_RESPONSE',
    SET_ACTIVE_COMPANY_GSTIN: 'SET_ACTIVE_COMPANY_GSTIN',
    DOWNLOAD_GSTR_SHEET: 'DOWNLOAD_GSTR_SHEET',
    DOWNLOAD_GSTR_SHEET_RESPONSE: 'DOWNLOAD_GSTR_SHEET_RESPONSE',
    CURRENT_PERIOD: 'CURRENT_PERIOD',
    GST_SAVE_GSP_SESSION: 'GST_SAVE_GSP_SESSION',
    GST_SAVE_GSP_SESSION_RESPONSE: 'GST_SAVE_GSP_SESSION_RESPONSE',
    GST_SAVE_GSP_SESSION_WITH_OTP: 'GST_SAVE_GSP_SESSION_WITH_OTP',
    GST_SAVE_GSP_SESSION_WITH_OTP_RESPONSE: 'GST_SAVE_GSP_SESSION_WITH_OTP_RESPONSE',
    GST_RESET_ASIDE_FLAGS: 'GST_RESET_ASIDE_FLAGS',
    FILE_GSTR1: 'FILE_GSTR1',
    FILE_GSTR1_RESPONSE: 'FILE_GSTR1_RESPONSE',
    GST_GET_GSP_SESSION: 'GST_GET_GSP_SESSION',
    GST_GET_GSP_SESSION_RESPONSE: 'GST_GET_GSP_SESSION_RESPONSE',
    RESET_GSTR3B_OVERVIEW_RESPONSE: 'RESET_GSTR3B_OVERVIEW_RESPONSE',
    RESET_GSTR1_OVERVIEW_RESPONSE: 'RESET_GSTR1_OVERVIEW_RESPONSE',
    RESET_GSTR2_OVERVIEW_RESPONSE: 'RESET_GSTR2_OVERVIEW_RESPONSE'
};
