export const SALES_ACTIONS = {
    GET_ACCOUNT_DETAILS: 'GET_ACCOUNT_DETAILS',
    GET_ACCOUNT_DETAILS_RESPONSE: 'GET_ACCOUNT_DETAILS_RESPONSE',
    ADD_ACCOUNT_DETAILS: 'ADD_ACCOUNT_DETAILS',
    ADD_ACCOUNT_DETAILS_RESPONSE: 'ADD_ACCOUNT_DETAILS_RESPONSE',
    UPDATE_ACCOUNT_DETAILS: 'UPDATE_ACCOUNT_DETAILS',
    UPDATE_ACCOUNT_DETAILS_RESPONSE: 'UPDATE_ACCOUNT_DETAILS_RESPONSE',
    STOCK_AC_SUCCESS: 'STOCK_AC_SUCCESS',
    RESET_ACCOUNT_DETAILS: 'RESET_ACCOUNT_DETAILS'
};
