export const SALES_ACTIONS = {
    GET_ACCOUNT_DETAILS: 'GET_ACCOUNT_DETAILS',
    GET_ACCOUNT_DETAILS_RESPONSE: 'GET_ACCOUNT_DETAILS_RESPONSE',
    ADD_ACCOUNT_DETAILS: 'ADD_ACCOUNT_DETAILS',
    ADD_ACCOUNT_DETAILS_RESPONSE: 'ADD_ACCOUNT_DETAILS_RESPONSE',
    UPDATE_ACCOUNT_DETAILS: 'UPDATE_ACCOUNT_DETAILS',
    UPDATE_ACCOUNT_DETAILS_RESPONSE: 'UPDATE_ACCOUNT_DETAILS_RESPONSE',
    GET_HIERARCHICAL_STOCK_GROUPS: 'GET_HIERARCHICAL_STOCK_GROUPS',
    GET_HIERARCHICAL_STOCK_GROUPS_RESPONSE: 'GET_HIERARCHICAL_STOCK_GROUPS_RESPONSE',
    GET_PURCHASE_AC_LIST: 'GET_PURCHASE_AC_LIST',
    GET_PURCHASE_AC_LIST_RESPONSE: 'GET_PURCHASE_AC_LIST_RESPONSE',
    GET_SALES_AC_LIST: 'GET_SALES_AC_LIST',
    GET_SALES_AC_LIST_RESPONSE: 'GET_SALES_AC_LIST_RESPONSE',
    STOCK_GROUP_SUCCESS: 'STOCK_GROUP_SUCCESS',
    STOCK_AC_SUCCESS: 'STOCK_AC_SUCCESS',
    SERVICE_AC_SUCCESS: 'SERVICE_AC_SUCCESS',
    SALES_FLATTEN_AC_STORED: 'SALES_FLATTEN_AC_STORED',
    RESET_ACCOUNT_DETAILS: 'RESET_ACCOUNT_DETAILS'
};
