export const SETTINGS_INTEGRATION_ACTIONS = {
  GET_SMS_KEY: 'GET_SMS_KEY',
  GET_SMS_KEY_RESPONSE: 'GET_SMS_KEY_RESPONSE',
  CREATE_SMS_KEY: 'CREATE_SMS_KEY',
  CREATE_SMS_KEY_RESPONSE: 'CREATE_SMS_KEY_RESPONSE',
  GET_EMAIL_KEY: 'GET_EMAIL_KEY',
  GET_EMAIL_KEY_RESPONSE: 'GET_EMAIL_KEY_RESPONSE',
  CREATE_EMAIL_KEY: 'CREATE_EMAIL_KEY',
  CREATE_EMAIL_KEY_RESPONSE: 'CREATE_EMAIL_KEY_RESPONSE',
  GET_RAZOR_PAY_DETAILS: 'GET_RAZOR_PAY_DETAILS',
  GET_RAZOR_PAY_DETAILS_RESPONSE: 'GET_RAZOR_PAY_DETAILS_RESPONSE',
  SAVE_RAZOR_PAY_DETAILS: 'SAVE_RAZOR_PAY_DETAILS',
  SAVE_RAZOR_PAY_DETAILS_RESPONSE: 'SAVE_RAZOR_PAY_DETAILS_RESPONSE',
  UPDATE_RAZOR_PAY_DETAILS: 'UPDATE_RAZOR_PAY_DETAILS',
  UPDATE_RAZOR_PAY_DETAILS_RESPONSE: 'UPDATE_RAZOR_PAY_DETAILS_RESPONSE',
  DELETE_RAZOR_PAY_DETAILS: 'DELETE_RAZOR_PAY_DETAILS',
  DELETE_RAZOR_PAY_DETAILS_RESPONSE: 'DELETE_RAZOR_PAY_DETAILS_RESPONSE'
};
