export const SETTINGS_INTEGRATION_ACTIONS = {
 GET_SMS_KEY: 'GET_SMS_KEY',
 GET_SMS_KEY_RESPONSE: 'GET_SMS_KEY_RESPONSE',
 CREATE_SMS_KEY: 'CREATE_SMS_KEY',
 CREATE_SMS_KEY_RESPONSE: 'CREATE_SMS_KEY_RESPONSE',
 GET_EMAIL_KEY: 'GET_EMAIL_KEY',
 GET_EMAIL_KEY_RESPONSE: 'GET_EMAIL_KEY_RESPONSE',
 CREATE_EMAIL_KEY: 'CREATE_EMAIL_KEY',
 CREATE_EMAIL_KEY_RESPONSE: 'CREATE_EMAIL_KEY_RESPONSE'
};
