export const AUDIT_LOGS_ACTIONS = {
    GET_LOGS: 'GET_LOGS',
    GET_LOGS_RESPONSE: 'GET_LOGS_RESPONSE',
    LOAD_MORE_LOGS: 'LOAD_MORE_LOGS',
    LOAD_MORE_LOGS_RESPONSE: 'LOAD_MORE_LOGS_RESPONSE',
    AUDIT_LOGS_RESET: 'AUDIT_LOGS_RESET'
};
