export const AUDIT_LOGS_ACTIONS = {
    GET_LOGS: 'GET_LOGS',
    GET_LOGS_RESPONSE: 'GET_LOGS_RESPONSE',
    LOAD_MORE_LOGS: 'LOAD_MORE_LOGS',
    LOAD_MORE_LOGS_RESPONSE: 'LOAD_MORE_LOGS_RESPONSE',
    AUDIT_LOGS_RESET: 'AUDIT_LOGS_RESET'
};

/** Audit logs version 2 constants for action  */
export const AUDIT_LOGS_ACTIONS_V2 = {
    GET_LOGS_REQUEST: 'GET_LOGS_REQUEST',
    GET_LOGS_RESPONSE_V2: 'GET_LOGS_RESPONSE_V2',
    AUDIT_LOGS_RESET_V2: 'AUDIT_LOGS_RESET_V2'
};
