export interface IContriesWithCodes {
    value: string;
    countryName: string;
    countryflag: string;
}

export const contriesWithCodes: IContriesWithCodes[] = [
    { value: '93', countryName: 'Afghanistan', countryflag: 'AF' },
    { value: '355', countryName: 'Albania', countryflag: 'AL' },
    { value: '213', countryName: 'Algeria', countryflag: 'DZ' },
    { value: '1684', countryName: 'American Samoa', countryflag: 'AS' },
    { value: '376', countryName: 'Andorra', countryflag: 'AD' },
    { value: '244', countryName: 'Angola', countryflag: 'AO' },
    { value: '1264', countryName: 'Anguilla', countryflag: 'AI' },
    { value: '672', countryName: 'Antarctica', countryflag: 'AQ' },
    { value: '1268', countryName: 'Antigua and Barbuda', countryflag: 'AG' },
    { value: '54', countryName: 'Argentina', countryflag: 'AR' },
    { value: '374', countryName: 'Armenia', countryflag: 'AM' },
    { value: '297', countryName: 'Aruba', countryflag: 'AW' },
    { value: '61', countryName: 'Australia', countryflag: 'AU' },
    { value: '43', countryName: 'Austria', countryflag: 'AT' },
    { value: '994', countryName: 'Azerbaijan', countryflag: 'AZ' },
    { value: '1242', countryName: 'Bahamas', countryflag: 'BS' },
    { value: '973', countryName: 'Bahrain', countryflag: 'BH' },
    { value: '880', countryName: 'Bangladesh', countryflag: 'BD' },
    { value: '1246', countryName: 'Barbados', countryflag: 'BB' },
    { value: '375', countryName: 'Belarus', countryflag: 'BY' },
    { value: '32', countryName: 'Belgium', countryflag: 'BE' },
    { value: '501', countryName: 'Belize', countryflag: 'BZ' },
    { value: '229', countryName: 'Benin', countryflag: 'BJ' },
    { value: '1441', countryName: 'Bermuda', countryflag: 'BM' },
    { value: '975', countryName: 'Bhutan', countryflag: 'BT' },
    { value: '591', countryName: 'Bolivia', countryflag: 'BO' },
    { value: '387', countryName: 'Bosnia and Herzegovina', countryflag: 'BA' },
    { value: '267', countryName: 'Botswana', countryflag: 'BW' },
    { value: '55', countryName: 'Brazil', countryflag: 'BR' },
    { value: '246', countryName: 'British Indian Ocean Territory', countryflag: 'IO' },
    { value: '1284', countryName: 'British Virgin Islands', countryflag: 'VG' },
    { value: '673', countryName: 'Brunei', countryflag: 'BN' },
    { value: '359', countryName: 'Bulgaria', countryflag: 'BG' },
    { value: '226', countryName: 'Burkina Faso', countryflag: 'BF' },
    { value: '95', countryName: 'Burma (Myanmar)', countryflag: 'MM' },
    { value: '257', countryName: 'Burundi', countryflag: 'BI' },
    { value: '855', countryName: 'Cambodia', countryflag: 'KH' },
    { value: '237', countryName: 'Cameroon', countryflag: 'CM' },
    { value: '1', countryName: 'Canada', countryflag: 'CA' },
    { value: '238', countryName: 'Cape Verde', countryflag: 'CV' },
    { value: '1345', countryName: 'Cayman Islands', countryflag: 'KY' },
    { value: '236', countryName: 'Central African Republic', countryflag: 'CF' },
    { value: '235', countryName: 'Chad', countryflag: 'TD' },
    { value: '56', countryName: 'Chile', countryflag: 'CL' },
    { value: '86', countryName: 'China', countryflag: 'CN' },
    { value: '61', countryName: 'Christmas Island', countryflag: 'CX' },
    { value: '61', countryName: 'Cocos (Keeling) Islands', countryflag: 'CC' },
    { value: '57', countryName: 'Colombia', countryflag: 'CO' },
    { value: '269', countryName: 'Comoros', countryflag: 'KM' },
    { value: '682', countryName: 'Cook Islands', countryflag: 'CK' },
    { value: '506', countryName: 'Costa Rica', countryflag: 'CR' },
    { value: '385', countryName: 'Croatia', countryflag: 'HR' },
    { value: '53', countryName: 'Cuba', countryflag: 'CU' },
    { value: '357', countryName: 'Cyprus', countryflag: 'CY' },
    { value: '420', countryName: 'Czech Republic', countryflag: 'CZ' },
    { value: '243', countryName: 'Democratic Republic of the Congo', countryflag: 'CD' },
    { value: '45', countryName: 'Denmark', countryflag: 'DK' },
    { value: '253', countryName: 'Djibouti', countryflag: 'DJ' },
    { value: '1767', countryName: 'Dominica', countryflag: 'DM' },
    { value: '1809', countryName: 'Dominican Republic', countryflag: 'DO' },
    { value: '593', countryName: 'Ecuador', countryflag: 'EC' },
    { value: '20', countryName: 'Egypt', countryflag: 'EG' },
    { value: '503', countryName: 'El Salvador', countryflag: 'SV' },
    { value: '240', countryName: 'Equatorial Guinea', countryflag: 'GQ' },
    { value: '291', countryName: 'Eritrea', countryflag: 'ER' },
    { value: '372', countryName: 'Estonia', countryflag: 'EE' },
    { value: '251', countryName: 'Ethiopia', countryflag: 'ET' },
    { value: '500', countryName: 'Falkland Islands', countryflag: 'FK' },
    { value: '298', countryName: 'Faroe Islands', countryflag: 'FO' },
    { value: '679', countryName: 'Fiji', countryflag: 'FJ' },
    { value: '358', countryName: 'Finland', countryflag: 'FI' },
    { value: '33', countryName: 'France', countryflag: 'FR' },
    { value: '689', countryName: 'French Polynesia', countryflag: 'PF' },
    { value: '241', countryName: 'Gabon', countryflag: 'GA' },
    { value: '220', countryName: 'Gambia', countryflag: 'GM' },
    { value: '995', countryName: 'Georgia', countryflag: 'GE' },
    { value: '49', countryName: 'Germany', countryflag: 'DE' },
    { value: '233', countryName: 'Ghana', countryflag: 'GH' },
    { value: '350', countryName: 'Gibraltar', countryflag: 'GI' },
    { value: '30', countryName: 'Greece', countryflag: 'GR' },
    { value: '299', countryName: 'Greenland', countryflag: 'GL' },
    { value: '1473', countryName: 'Grenada', countryflag: 'GD' },
    { value: '1671', countryName: 'Guam', countryflag: 'GU' },
    { value: '502', countryName: 'Guatemala', countryflag: 'GT' },
    { value: '224', countryName: 'Guinea', countryflag: 'GN' },
    { value: '245', countryName: 'Guinea-Bissau', countryflag: 'GW' },
    { value: '592', countryName: 'Guyana', countryflag: 'GY' },
    { value: '509', countryName: 'Haiti', countryflag: 'HT' },
    { value: '39', countryName: 'Holy See (Vatican, City)', countryflag: 'VA' },
    { value: '504', countryName: 'Honduras', countryflag: 'HN' },
    { value: '852', countryName: 'Hong Kong', countryflag: 'HK' },
    { value: '36', countryName: 'Hungary', countryflag: 'HU' },
    { value: '354', countryName: 'Iceland', countryflag: 'IS' },
    { value: '91', countryName: 'India', countryflag: 'IN' },
    { value: '62', countryName: 'Indonesia', countryflag: 'ID' },
    { value: '98', countryName: 'Iran', countryflag: 'IR' },
    { value: '964', countryName: 'Iraq', countryflag: 'IQ' },
    { value: '353', countryName: 'Ireland', countryflag: 'IE' },
    { value: '44', countryName: 'Isle of Man', countryflag: 'IM' },
    { value: '972', countryName: 'Israel', countryflag: 'IL' },
    { value: '39', countryName: 'Italy', countryflag: 'IT' },
    { value: '225', countryName: 'Ivory Coast', countryflag: 'CI' },
    { value: '1876', countryName: 'Jamaica', countryflag: 'JM' },
    { value: '81', countryName: 'Japan', countryflag: 'JP' },
    { value: '44', countryName: 'Jersey', countryflag: 'JE' },
    { value: '962', countryName: 'Jordan', countryflag: 'JO' },
    { value: '7', countryName: 'Kazakhstan', countryflag: 'KZ' },
    { value: '254', countryName: 'Kenya', countryflag: 'KE' },
    { value: '686', countryName: 'Kiribati', countryflag: 'KI' },
    { value: '965', countryName: 'Kuwait', countryflag: 'KW' },
    { value: '996', countryName: 'Kyrgyzstan', countryflag: 'KG' },
    { value: '856', countryName: 'Laos', countryflag: 'LA' },
    { value: '371', countryName: 'Latvia', countryflag: 'LV' },
    { value: '961', countryName: 'Lebanon', countryflag: 'LB' },
    { value: '266', countryName: 'Lesotho', countryflag: 'LS' },
    { value: '231', countryName: 'Liberia', countryflag: 'LR' },
    { value: '218', countryName: 'Libya', countryflag: 'LY' },
    { value: '423', countryName: 'Liechtenstein', countryflag: 'LI' },
    { value: '370', countryName: 'Lithuania', countryflag: 'LT' },
    { value: '352', countryName: 'Luxembourg', countryflag: 'LU' },
    { value: '853', countryName: 'Macau', countryflag: 'MO' },
    { value: '389', countryName: 'Macedonia', countryflag: 'MK' },
    { value: '261', countryName: 'Madagascar', countryflag: 'MG' },
    { value: '265', countryName: 'Malawi', countryflag: 'MW' },
    { value: '60', countryName: 'Malaysia', countryflag: 'MY' },
    { value: '960', countryName: 'Maldives', countryflag: 'MV' },
    { value: '223', countryName: 'Mali', countryflag: 'ML' },
    { value: '356', countryName: 'Malta', countryflag: 'MT' },
    { value: '692', countryName: 'Marshall Islands', countryflag: 'MH' },
    { value: '222', countryName: 'Mauritania', countryflag: 'MR' },
    { value: '230', countryName: 'Mauritius', countryflag: 'MU' },
    { value: '262', countryName: 'Mayotte', countryflag: 'YT' },
    { value: '52', countryName: 'Mexico', countryflag: 'MX' },
    { value: '691', countryName: 'Micronesia', countryflag: 'FM' },
    { value: '373', countryName: 'Moldova', countryflag: 'MD' },
    { value: '377', countryName: 'Monaco', countryflag: 'MC' },
    { value: '976', countryName: 'Mongolia', countryflag: 'MN' },
    { value: '382', countryName: 'Montenegro', countryflag: 'ME' },
    { value: '1664', countryName: 'Montserrat', countryflag: 'MS' },
    { value: '212', countryName: 'Morocco', countryflag: 'MA' },
    { value: '258', countryName: 'Mozambique', countryflag: 'MZ' },
    { value: '264', countryName: 'Namibia', countryflag: 'NA' },
    { value: '674', countryName: 'Nauru', countryflag: 'NR' },
    { value: '977', countryName: 'Nepal', countryflag: 'NP' },
    { value: '31', countryName: 'Netherlands', countryflag: 'NL' },
    { value: '599', countryName: 'Netherlands Antilles', countryflag: 'AN' },
    { value: '687', countryName: 'New Caledonia', countryflag: 'NC' },
    { value: '64', countryName: 'New Zealand', countryflag: 'NZ' },
    { value: '505', countryName: 'Nicaragua', countryflag: 'NI' },
    { value: '227', countryName: 'Niger', countryflag: 'NE' },
    { value: '234', countryName: 'Nigeria', countryflag: 'NG' },
    { value: '683', countryName: 'Niue', countryflag: 'NU' },
    { value: '850', countryName: 'North Korea', countryflag: 'KP' },
    { value: '1670', countryName: 'Northern Mariana Islands', countryflag: 'MP' },
    { value: '47', countryName: 'Norway', countryflag: 'NO' },
    { value: '968', countryName: 'Oman', countryflag: 'OM' },
    { value: '92', countryName: 'Pakistan', countryflag: 'PK' },
    { value: '680', countryName: 'Palau', countryflag: 'PW' },
    { value: '507', countryName: 'Panama', countryflag: 'PA' },
    { value: '675', countryName: 'Papua New Guinea', countryflag: 'PG' },
    { value: '595', countryName: 'Paraguay', countryflag: 'PY' },
    { value: '51', countryName: 'Peru', countryflag: 'PE' },
    { value: '63', countryName: 'Philippines', countryflag: 'PH' },
    { value: '870', countryName: 'Pitcairn Islands', countryflag: 'PN' },
    { value: '48', countryName: 'Poland', countryflag: 'PL' },
    { value: '351', countryName: 'Portugal', countryflag: 'PT' },
    { value: '1', countryName: 'Puerto Rico', countryflag: 'PR' },
    { value: '974', countryName: 'Qatar', countryflag: 'QA' },
    { value: '242', countryName: 'Republic of the Congo', countryflag: 'CG' },
    { value: '40', countryName: 'Romania', countryflag: 'RO' },
    { value: '7', countryName: 'Russia', countryflag: 'RU' },
    { value: '250', countryName: 'Rwanda', countryflag: 'RW' },
    { value: '590', countryName: 'Saint Barthelemy', countryflag: 'BL' },
    { value: '290', countryName: 'Saint Helena', countryflag: 'SH' },
    { value: '1869', countryName: 'Saint Kitts and Nevis', countryflag: 'KN' },
    { value: '1758', countryName: 'Saint Lucia', countryflag: 'LC' },
    { value: '1599', countryName: 'Saint Martin', countryflag: 'MF' },
    { value: '508', countryName: 'Saint Pierre and Miquelon', countryflag: 'PM' },
    { value: '1784', countryName: 'Saint Vincent and the Grenadines', countryflag: 'VC' },
    { value: '685', countryName: 'Samoa', countryflag: 'WS' },
    { value: '378', countryName: 'San Marino', countryflag: 'SM' },
    { value: '239', countryName: 'Sao Tome and Principe', countryflag: 'ST' },
    { value: '966', countryName: 'Saudi Arabia', countryflag: 'SA' },
    { value: '221', countryName: 'Senegal', countryflag: 'SN' },
    { value: '381', countryName: 'Serbia', countryflag: 'RS' },
    { value: '248', countryName: 'Seychelles', countryflag: 'SC' },
    { value: '232', countryName: 'Sierra Leone', countryflag: 'SL' },
    { value: '65', countryName: 'Singapore', countryflag: 'SG' },
    { value: '421', countryName: 'Slovakia', countryflag: 'SK' },
    { value: '386', countryName: 'Slovenia', countryflag: 'SI' },
    { value: '677', countryName: 'Solomon Islands', countryflag: 'SB' },
    { value: '252', countryName: 'Somalia', countryflag: 'SO' },
    { value: '27', countryName: 'South Africa', countryflag: 'ZA' },
    { value: '82', countryName: 'South Korea', countryflag: 'KR' },
    { value: '34', countryName: 'Spain', countryflag: 'ES' },
    { value: '94', countryName: 'Sri Lanka', countryflag: 'LK' },
    { value: '249', countryName: 'Sudan', countryflag: 'SD' },
    { value: '597', countryName: 'SuriName', countryflag: 'SR' },
    { value: '47', countryName: 'Svalbard', countryflag: 'SJ' },
    { value: '268', countryName: 'Swaziland', countryflag: 'SZ' },
    { value: '46', countryName: 'Sweden', countryflag: 'SE' },
    { value: '41', countryName: 'Switzerland', countryflag: 'CH' },
    { value: '963', countryName: 'Syria', countryflag: 'SY' },
    { value: '886', countryName: 'Taiwan', countryflag: 'TW' },
    { value: '992', countryName: 'Tajikistan', countryflag: 'TJ' },
    { value: '255', countryName: 'Tanzania', countryflag: 'TZ' },
    { value: '66', countryName: 'Thailand', countryflag: 'TH' },
    { value: '670', countryName: 'Timor-Leste', countryflag: 'TL' },
    { value: '228', countryName: 'Togo', countryflag: 'TG' },
    { value: '690', countryName: 'Tokelau', countryflag: 'TK' },
    { value: '676', countryName: 'Tonga', countryflag: 'TO' },
    { value: '1868', countryName: 'Trinidad and Tobago', countryflag: 'TT' },
    { value: '216', countryName: 'Tunisia', countryflag: 'TN' },
    { value: '90', countryName: 'Turkey', countryflag: 'TR' },
    { value: '993', countryName: 'Turkmenistan', countryflag: 'TM' },
    { value: '1649', countryName: 'Turks and Caicos Islands', countryflag: 'TC' },
    { value: '688', countryName: 'Tuvalu', countryflag: 'TV' },
    { value: '256', countryName: 'Uganda', countryflag: 'UG' },
    { value: '380', countryName: 'Ukraine', countryflag: 'UA' },
    { value: '971', countryName: 'United Arab Emirates', countryflag: 'AE' },
    { value: '44', countryName: 'United Kingdom', countryflag: 'GB' },
    { value: '598', countryName: 'Uruguay', countryflag: 'UY' },
    { value: '1340', countryName: 'US Virgin Islands', countryflag: 'VI' },
    { value: '998', countryName: 'Uzbekistan', countryflag: 'UZ' },
    { value: '678', countryName: 'Vanuatu', countryflag: 'VU' },
    { value: '58', countryName: 'Venezuela', countryflag: 'VE' },
    { value: '84', countryName: 'Vietnam', countryflag: 'VN' },
    { value: '681', countryName: 'Wallis and Futuna', countryflag: 'WF' },
    { value: '212', countryName: 'Western Sahara', countryflag: 'EH' },
    { value: '967', countryName: 'Yemen', countryflag: 'YE' },
    { value: '260', countryName: 'Zambia', countryflag: 'ZM' },
    { value: '263', countryName: 'Zimbabwe', countryflag: 'ZW' },
    { value: '1868', countryName: 'Trinidad & Tobago', countryflag: 'TT' },
    { value: '1', countryName: 'Usa', countryflag: 'US' },
    { value: '95', countryName: 'Myanmar', countryflag: 'MM' },
    { value: '1784', countryName: 'St. Vincent', countryflag: 'VC' },
    { value: '1868', countryName: 'Trinidad', countryflag: 'TT' },
    { value: '1758', countryName: 'St. Lucia', countryflag: 'LC' },
    { value: '1599', countryName: 'St. Martin', countryflag: 'MF' },
    { value: '1869', countryName: 'St. Kitts', countryflag: 'KN' },
    { value: '290', countryName: 'St. Helena', countryflag: 'SH' },
    { value: '1268', countryName: 'Antigua', countryflag: 'AG' }
];

export const countryCodeForFlagUrl: string[] = ['ad', 'ae', 'af', 'ag', 'ai', 'al', 'am', 'ao', 'aq', 'ar', 'as', 'at', 'au', 'aw', 'ax', 'az', 'ba', 'bb', 'bd', 'be', 'bf', 'bg', 'bh', 'bi', 'bj', 'bl', 'bm', 'bn', 'bo', 'bq', 'br', 'bs', 'bt', 'bv', 'bw', 'by', 'bz', 'ca', 'cc', 'cd', 'cf', 'cg', 'ch', 'ci', 'ck', 'cl', 'cm', 'cn', 'co', 'cr', 'cu', 'cv', 'cw', 'cx', 'cy', 'cz', 'de', 'dj', 'dk', 'dm', 'do', 'dz', 'ec', 'ee', 'eg', 'eh', 'er', 'es', 'et', 'eu', 'fi', 'fj', 'fk', 'fm', 'fo', 'fr', 'ga', 'gb', 'gb-eng', 'gb-nir', 'gb-sct', 'gb-wls', 'gd', 'ge', 'gf', 'gg', 'gh', 'gi', 'gl', 'gm', 'gn', 'gp', 'gq', 'gr', 'gs', 'gt', 'gu', 'gw', 'gy', 'hk', 'hm', 'hn', 'hr', 'ht', 'hu', 'id', 'ie', 'il', 'im', 'in', 'io', 'iq', 'ir', 'is', 'it', 'je', 'jm', 'jo', 'jp', 'ke', 'kg', 'kh', 'ki', 'km', 'kn', 'kp', 'kr', 'kw', 'ky', 'kz', 'la', 'lb', 'lc', 'li', 'lk', 'lr', 'ls', 'lt', 'lu', 'lv', 'ly', 'ma', 'mc', 'md', 'me', 'mf', 'mg', 'mh', 'mk', 'ml', 'mm', 'mn', 'mo', 'mp', 'mq', 'mr', 'ms', 'mt', 'mu', 'mv', 'mw', 'mx', 'my', 'mz', 'na', 'nc', 'ne', 'nf', 'ng', 'ni', 'nl', 'no', 'np', 'nr', 'nu', 'nz', 'om', 'pa', 'pe', 'pf', 'pg', 'ph', 'pk', 'pl', 'pm', 'pn', 'pr', 'ps', 'pt', 'pw', 'py', 'qa', 're', 'ro', 'rs', 'ru', 'rw', 'sa', 'sb', 'sc', 'sd', 'se', 'sg', 'sh', 'si', 'sj', 'sk', 'sl', 'sm', 'sn', 'so', 'sr', 'ss', 'st', 'sv', 'sx', 'sy', 'sz', 'tc', 'td', 'tf', 'tg', 'th', 'tj', 'tk', 'tl', 'tm', 'tn', 'to', 'tr', 'tt', 'tv', 'tw', 'tz', 'ua', 'ug', 'um', 'us', 'uy', 'uz', 'va', 'vc', 've', 'vg', 'vi', 'vn', 'vu', 'wf', 'ws', 'xk', 'ye', 'yt', 'za', 'zm', 'zw'];

export const gulfCountriesCode = [ 'bh', 'kw', 'om', 'qa', 'sa', 'ye'];

 export const regionCountriesCode = ['eur', 'glb', 'glf'];
