/**
 * Clean comprehensive constants for Angular 21 compilation
 * Single source of truth for all action constants
 */

// INVOICE constants with all nested properties
export const INVOICE = {
    GET_INVOICE_TEMPLATE_DETAILS: 'GET_INVOICE_TEMPLATE_DETAILS',
    GET_INVOICE_TEMPLATE_DETAILS_RESPONSE: 'GET_INVOICE_TEMPLATE_DETAILS_RESPONSE',
    UPDATE_INVOICE_TEMPLATE: 'UPDATE_INVOICE_TEMPLATE',
    UPDATE_INVOICE_TEMPLATE_RESPONSE: 'UPDATE_INVOICE_TEMPLATE_RESPONSE',
    DELETE_INVOICE_TEMPLATE: 'DELETE_INVOICE_TEMPLATE',
    DELETE_INVOICE_TEMPLATE_RESPONSE: 'DELETE_INVOICE_TEMPLATE_RESPONSE',
    SETTING: {
        GET_INVOICE_SETTING: 'GET_INVOICE_SETTING',
        GET_INVOICE_SETTING_RESPONSE: 'GET_INVOICE_SETTING_RESPONSE',
        DELETE_WEBHOOK_RESPONSE: 'DELETE_WEBHOOK_RESPONSE',
        UPDATE_INVOICE_EMAIL_RESPONSE: 'UPDATE_INVOICE_EMAIL_RESPONSE',
        SAVE_INVOICE_WEBHOOK_RESPONSE: 'SAVE_INVOICE_WEBHOOK_RESPONSE',
        UPDATE_INVOICE_SETTING_RESPONSE: 'UPDATE_INVOICE_SETTING_RESPONSE',
        GET_RAZORPAY_DETAIL_RESPONSE: 'GET_RAZORPAY_DETAIL_RESPONSE',
        UPDATE_RAZORPAY_DETAIL_RESPONSE: 'UPDATE_RAZORPAY_DETAIL_RESPONSE',
        DELETE_RAZORPAY_DETAIL_RESPONSE: 'DELETE_RAZORPAY_DETAIL_RESPONSE',
        DELETE_INVOICE_EMAIL_RESPONSE: 'DELETE_INVOICE_EMAIL_RESPONSE',
        SAVE_RAZORPAY_DETAIL_RESPONSE: 'SAVE_RAZORPAY_DETAIL_RESPONSE'
    },
    RECURRING: {
        GET_RECURRING_INVOICES: 'GET_RECURRING_INVOICES',
        GET_RECURRING_INVOICES_RESPONSE: 'GET_RECURRING_INVOICES_RESPONSE',
        GET_RECURRING_INVOICE_DATA_RESPONSE: 'GET_RECURRING_INVOICE_DATA_RESPONSE',
        CREATE_RECURRING_INVOICE: 'CREATE_RECURRING_INVOICE',
        CREATE_RECURRING_INVOICE_RESPONSE: 'CREATE_RECURRING_INVOICE_RESPONSE',
        UPDATE_RECURRING_INVOICE: 'UPDATE_RECURRING_INVOICE',
        UPDATE_RECURRING_INVOICE_RESPONSE: 'UPDATE_RECURRING_INVOICE_RESPONSE',
        RESET_RECURRING_INVOICE_REQUEST: 'RESET_RECURRING_INVOICE_REQUEST',
        NO_PERMISSIONS_RECURRING_INVOICE: 'NO_PERMISSIONS_RECURRING_INVOICE'
    },
    TEMPLATE: {
        GET_INVOICE_TEMPLATE: 'GET_INVOICE_TEMPLATE',
        GET_INVOICE_TEMPLATE_RESPONSE: 'GET_INVOICE_TEMPLATE_RESPONSE',
        GET_SAMPLE_TEMPLATES_RESPONSE: 'GET_SAMPLE_TEMPLATES_RESPONSE',
        GET_ALL_CREATED_TEMPLATES_RESPONSE: 'GET_ALL_CREATED_TEMPLATES_RESPONSE',
        SET_TEMPLATE_AS_DEFAULT_RESPONSE: 'SET_TEMPLATE_AS_DEFAULT_RESPONSE',
        DELETE_TEMPLATE_RESPONSE: 'DELETE_TEMPLATE_RESPONSE'
    }
};

// Complete InventoryActionsConst with all properties
export const InventoryActionsConst = {
    GetInventory: 'GetInventory',
    GetInventoryResponse: 'GetInventoryResponse',
    CreateStock: 'CreateStock',
    CreateStockResponse: 'CreateStockResponse',
    UpdateStock: 'UpdateStock',
    UpdateStockResponse: 'UpdateStockResponse',
    DeleteStock: 'DeleteStock',
    DeleteStockResponse: 'DeleteStockResponse',
    GetStock: 'GetStock',
    GetStockResponse: 'GetStockResponse',
    GetStockWithUniqueName: 'GetStockWithUniqueName',
    GetStockWithUniqueNameResponse: 'GetStockWithUniqueNameResponse',
    ShowLoadingForStockEditInProcess: 'ShowLoadingForStockEditInProcess',
    HideLoadingForStockEditInProcess: 'HideLoadingForStockEditInProcess',
    ResetActiveStock: 'ResetActiveStock',
    ResetInventoryState: 'ResetInventoryState',
    MoveStock: 'MoveStock',
    MoveStockResponse: 'MoveStockResponse',
    NewGroupAsidePane: 'NewGroupAsidePane',
    NewCustomUnitAsidePane: 'NewCustomUnitAsidePane',
    ManageInventoryAside: 'ManageInventoryAside',
    ShowBranchScreen: 'ShowBranchScreen',
    ShowBranchScreenSideBar: 'ShowBranchScreenSideBar',
    BulkStockResponse: 'BulkStockResponse',
    SetActiveStock: 'SetActiveStock',
    GetGroupsWithStocksHierarchyMin: 'GetGroupsWithStocksHierarchyMin',
    GetGroupsWithStocksHierarchyMinResponse: 'GetGroupsWithStocksHierarchyMinResponse',
    GetInventoryGroupResponse: 'GetInventoryGroupResponse',
    InventoryGroupToggleOpen: 'InventoryGroupToggleOpen',
    AddNewGroup: 'AddNewGroup',
    AddNewGroupResponse: 'AddNewGroupResponse',
    GetGroupUniqueName: 'GetGroupUniqueName',
    GetGroupUniqueNameResponse: 'GetGroupUniqueNameResponse',
    UpdateGroup: 'UpdateGroup',
    UpdateGroupResponse: 'UpdateGroupResponse',
    RemoveGroup: 'RemoveGroup',
    RemoveGroupResponse: 'RemoveGroupResponse',
    ResetActiveGroup: 'ResetActiveGroup',
    GetStockUniqueName: 'GetStockUniqueName',
    GetStockUniqueNameResponse: 'GetStockUniqueNameResponse',
    GetManufacturingStockResponse: 'GetManufacturingStockResponse',
    GetManufacturingStockForCreateResponse: 'GetManufacturingStockForCreateResponse',
    GetManufacturingStockForCreate: 'GetManufacturingStockForCreate',
    ResetCreateStockFlags: 'ResetCreateStockFlags',
    RemoveStock: 'RemoveStock',
    RemoveStockResponse: 'RemoveStockResponse',
    GetInventoryStockResponse: 'GetInventoryStockResponse',
    SearchGroupsWithStocks: 'SearchGroupsWithStocks',
    SearchGroupsWithStocksResponse: 'SearchGroupsWithStocksResponse'
};

// Stock unit actions
export const CUSTOM_STOCK_UNIT_ACTIONS = {
    GET_STOCK_MAPPED_UNITS_RESPONSE: 'GET_STOCK_MAPPED_UNITS_RESPONSE',
    GET_STOCK_MAPPED_UNIT_UNIQUE_NAME_RESPONSE: 'GET_STOCK_MAPPED_UNIT_UNIQUE_NAME_RESPONSE',
    GET_STOCK_UNIT_RESPONSE: 'GET_STOCK_UNIT_RESPONSE',
    CREATE_STOCK_UNIT: 'CREATE_STOCK_UNIT',
    RESET_STOCK_UNIT_RESPONSE: 'RESET_STOCK_UNIT_RESPONSE',
    CREATE_STOCK_UNIT_RESPONSE: 'CREATE_STOCK_UNIT_RESPONSE',
    UPDATE_STOCK_UNIT: 'UPDATE_STOCK_UNIT',
    UPDATE_STOCK_UNIT_RESPONSE: 'UPDATE_STOCK_UNIT_RESPONSE',
    DELETE_STOCK_UNIT: 'DELETE_STOCK_UNIT',
    DELETE_STOCK_UNIT_RESPONSE: 'DELETE_STOCK_UNIT_RESPONSE',
    GET_STOCK_UNIT_NAME: 'GET_STOCK_UNIT_NAME',
    GET_STOCK_UNIT_NAME_RESPONSE: 'GET_STOCK_UNIT_NAME_RESPONSE'
};

// Stock report actions
export const STOCKS_REPORT_ACTIONS = {
    GET_STOCKS_REPORT_RESPONSE: 'GET_STOCKS_REPORT_RESPONSE',
    GET_GROUP_STOCKS_REPORT: 'GET_GROUP_STOCKS_REPORT',
    GET_STOCKS_REPORT: 'GET_STOCKS_REPORT',
    GET_GROUP_STOCKS_REPORT_RESPONSE: 'GET_GROUP_STOCKS_REPORT_RESPONSE'
};

// All other action constants
export const LEDGER = {
    GET_LEDGER: 'GET_LEDGER',
    SET_LEDGER: 'SET_LEDGER',
    RESET_LEDGER: 'RESET_LEDGER',
    GET_LEDGER_ACCOUNT: 'GET_LEDGER_ACCOUNT',
    GET_LEDGER_ACCOUNT_RESPONSE: 'GET_LEDGER_ACCOUNT_RESPONSE',
    GET_TRANSACTION: 'GET_TRANSACTION',
    GET_TRANSACTION_RESPONSE: 'GET_TRANSACTION_RESPONSE',
    ADVANCE_SEARCH: 'ADVANCE_SEARCH',
    ADVANCE_SEARCH_RESPONSE: 'ADVANCE_SEARCH_RESPONSE',
    DOWNLOAD_LEDGER_INVOICE: 'DOWNLOAD_LEDGER_INVOICE',
    DOWNLOAD_LEDGER_INVOICE_RESPONSE: 'DOWNLOAD_LEDGER_INVOICE_RESPONSE',
    CREATE_BLANK_LEDGER_REQUEST: 'CREATE_BLANK_LEDGER_REQUEST',
    CREATE_BLANK_LEDGER_RESPONSE: 'CREATE_BLANK_LEDGER_RESPONSE',
    CREATE_BULK_BLANK_LEDGER_RESPONSE: 'CREATE_BULK_BLANK_LEDGER_RESPONSE',
    RESET_BLANK_LEDGER_REQUEST: 'RESET_BLANK_LEDGER_REQUEST',
    SET_SELECTED_TXN_FOR_EDIT: 'SET_SELECTED_TXN_FOR_EDIT',
    SET_SELECTED_ACCOUNT_FOR_EDIT: 'SET_SELECTED_ACCOUNT_FOR_EDIT',
    DELETE_TRX_ENTRY: 'DELETE_TRX_ENTRY',
    DELETE_TRX_ENTRY_RESPONSE: 'DELETE_TRX_ENTRY_RESPONSE',
    RESET_DELETE_TRX_ENTRY_MODAL: 'RESET_DELETE_TRX_ENTRY_MODAL',
    LEDGER_SHARED_ACCOUNT_WITH_RESPONSE: 'LEDGER_SHARED_ACCOUNT_WITH_RESPONSE',
    UPDATE_TXN_ENTRY: 'UPDATE_TXN_ENTRY',
    RESET_UPDATE_TXN_ENTRY: 'RESET_UPDATE_TXN_ENTRY',
    UPDATE_TXN_ENTRY_RESPONSE: 'UPDATE_TXN_ENTRY_RESPONSE',
    CREATE_QUICK_ACCOUNT: 'CREATE_QUICK_ACCOUNT',
    CREATE_QUICK_ACCOUNT_RESPONSE: 'CREATE_QUICK_ACCOUNT_RESPONSE',
    GET_LEDGER_TRX_DETAILS_RESPONSE: 'GET_LEDGER_TRX_DETAILS_RESPONSE',
    RESET_LEGER_TRX_DETAILS: 'RESET_LEGER_TRX_DETAILS',
    RESET_QUICK_ACCOUNT_MODAL: 'RESET_QUICK_ACCOUNT_MODAL',
    GET_RECONCILIATION_RESPONSE: 'GET_RECONCILIATION_RESPONSE',
    DELETE_MULTIPLE_LEDGER_ENTRIES: 'DELETE_MULTIPLE_LEDGER_ENTRIES',
    DELETE_MULTIPLE_LEDGER_ENTRIES_RESPONSE: 'DELETE_MULTIPLE_LEDGER_ENTRIES_RESPONSE',
    GENERATE_BULK_LEDGER_INVOICE: 'GENERATE_BULK_LEDGER_INVOICE',
    GENERATE_BULK_LEDGER_INVOICE_RESPONSE: 'GENERATE_BULK_LEDGER_INVOICE_RESPONSE',
    SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION: 'SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION',
    GET_CURRENCY_RATE_RESPONSE: 'GET_CURRENCY_RATE_RESPONSE',
    SELECT_DESELECT_ALL_ENTRIES: 'SELECT_DESELECT_ALL_ENTRIES',
    SELECT_GIVEN_ENTRIES: 'SELECT_GIVEN_ENTRIES',
    DESELECT_GIVEN_ENTRIES: 'DESELECT_GIVEN_ENTRIES',
    SET_FAILED_BULK_ENTRIES: 'SET_FAILED_BULK_ENTRIES',
    GET_LEDGER_BALANCE: 'GET_LEDGER_BALANCE',
    GET_LEDGER_BALANCE_RESPONSE: 'GET_LEDGER_BALANCE_RESPONSE',
    REFRESH_LEDGER: 'REFRESH_LEDGER',
    SHOW_DUPLICATE_VOUCHER_CONFIRMATION: 'SHOW_DUPLICATE_VOUCHER_CONFIRMATION'
};

// Action classes
export class SearchActions {
    static SEARCH_RESPONSE = 'SEARCH_RESPONSE';
    static SEARCH_REQUEST = 'SEARCH_REQUEST';
    static RESET_SEARCH_STATE = 'RESET_SEARCH_STATE';
    [key: string]: any;
}

export class TBPlBsActions {
    static GET_TRIAL_BALANCE_RESPONSE = 'GET_TRIAL_BALANCE_RESPONSE';
    static GET_V2_TRIAL_BALANCE_RESPONSE = 'GET_V2_TRIAL_BALANCE_RESPONSE';
    static GET_TRIAL_BALANCE_REQUEST = 'GET_TRIAL_BALANCE_REQUEST';
    static GET_V2_TRIAL_BALANCE_REQUEST = 'GET_V2_TRIAL_BALANCE_REQUEST';
    static GET_PROFIT_LOSS_RESPONSE = 'GET_PROFIT_LOSS_RESPONSE';
    static GET_PROFIT_LOSS_REQUEST = 'GET_PROFIT_LOSS_REQUEST';
    static GET_COGS_RESPONSE = 'GET_COGS_RESPONSE';
    static GET_BALANCE_SHEET_RESPONSE = 'GET_BALANCE_SHEET_RESPONSE';
    static GET_BALANCE_SHEET_REQUEST = 'GET_BALANCE_SHEET_REQUEST';
    [key: string]: any;
}

export class SubscriptionsActions {
    static SubscribedCompaniesResponse = 'SubscribedCompaniesResponse';
    static SubscribedUserTransactionsResponse = 'SubscribedUserTransactionsResponse';
    static SubscribedCompanyTransactionsResponse = 'SubscribedCompanyTransactionsResponse';
    static SubscribedCompaniesListResponse = 'SubscribedCompaniesListResponse';
    [key: string]: any;
}

export class AccountsAction {
    static SHARE_ENTITY = 'SHARE_ENTITY';
    static SHARE_ENTITY_RESPONSE = 'SHARE_ENTITY_RESPONSE';
    static RESET_SHARE_ENTITY = 'RESET_SHARE_ENTITY';
    static MERGE_ACCOUNT = 'MERGE_ACCOUNT';
    static MERGE_ACCOUNT_RESPONSE = 'MERGE_ACCOUNT_RESPONSE';
    static UNMERGE_ACCOUNT = 'UNMERGE_ACCOUNT';
    static UNMERGE_ACCOUNT_RESPONSE = 'UNMERGE_ACCOUNT_RESPONSE';
    static CREATE_ACCOUNTV2 = 'CREATE_ACCOUNTV2';
    static CREATE_ACCOUNT = 'CREATE_ACCOUNT';
    static CREATE_ACCOUNT_RESPONSEV2 = 'CREATE_ACCOUNT_RESPONSEV2';
    static CREATE_ACCOUNT_RESPONSE = 'CREATE_ACCOUNT_RESPONSE';
    static ACCOUNT_HAS_UNSAVED_CHANGES = 'ACCOUNT_HAS_UNSAVED_CHANGES';
    static GET_ACCOUNT_DETAILS_RESPONSE = 'GET_ACCOUNT_DETAILS_RESPONSE';
    static UPDATE_ACCOUNTV2 = 'UPDATE_ACCOUNTV2';
    static UPDATE_ACCOUNTV2_PATCH = 'UPDATE_ACCOUNTV2_PATCH';
    static RESET_UPDATE_ACCOUNTV2 = 'RESET_UPDATE_ACCOUNTV2';
    static UPDATE_ACCOUNT_RESPONSEV2 = 'UPDATE_ACCOUNT_RESPONSEV2';
    static RESET_ACTIVE_ACCOUNT = 'RESET_ACTIVE_ACCOUNT';
    static DELETE_ACCOUNT = 'DELETE_ACCOUNT';
    static DELETE_ACCOUNT_RESPONSE = 'DELETE_ACCOUNT_RESPONSE';
    static RESET_DELETE_ACCOUNT_FLAGS = 'RESET_DELETE_ACCOUNT_FLAGS';
    static MOVE_ACCOUNT_RESPONSE = 'MOVE_ACCOUNT_RESPONSE';
    static MOVE_ACCOUNT_RESET = 'MOVE_ACCOUNT_RESET';
    static SHARED_ACCOUNT_WITH_RESPONSE = 'SHARED_ACCOUNT_WITH_RESPONSE';
    static UNSHARE_ACCOUNT_RESPONSE = 'UNSHARE_ACCOUNT_RESPONSE';
    static GET_ACCOUNT_TAX_HIERARCHY = 'GET_ACCOUNT_TAX_HIERARCHY';
    static GET_ACCOUNT_TAX_HIERARCHY_RESPONSE = 'GET_ACCOUNT_TAX_HIERARCHY_RESPONSE';
    static RESET_ACTIVE_GROUP = 'RESET_ACTIVE_GROUP';
    [key: string]: any;
}

export class GroupWithAccountsAction {
    static MOVE_GROUP_COMPLETE = 'MOVE_GROUP_COMPLETE';
    static UPDATE_ACTIVE_TAB_ADD_AND_MANAGE = 'UPDATE_ACTIVE_TAB_ADD_AND_MANAGE';
    static GET_ACCOUNT_GROUP_DETAILS_RESPONSE = 'GET_ACCOUNT_GROUP_DETAILS_RESPONSE';
    static UPDATE_GROUP = 'UPDATE_GROUP';
    static UPDATE_GROUP_RESPONSE = 'UPDATE_GROUP_RESPONSE';
    static DELETE_GROUP = 'DELETE_GROUP';
    static DELETE_GROUP_RESPONSE = 'DELETE_GROUP_RESPONSE';
    static MOVE_GROUP = 'MOVE_GROUP';
    static MOVE_GROUP_RESPONSE = 'MOVE_GROUP_RESPONSE';
    static GEN_ADD_AND_MANAGE_UI = 'GEN_ADD_AND_MANAGE_UI';
    static GET_GROUP_DETAILS = 'GET_GROUP_DETAILS';
    static GET_GROUP_DETAILS_RESPONSE = 'GET_GROUP_DETAILS_RESPONSE';
    static CREATE_GROUP = 'CREATE_GROUP';
    static CREATE_GROUP_RESPONSE = 'CREATE_GROUP_RESPONSE';
    static SHARED_GROUP_WITH_RESPONSE = 'SHARED_GROUP_WITH_RESPONSE';
    static UNSHARE_GROUP_RESPONSE = 'UNSHARE_GROUP_RESPONSE';
    static RESET_GROUPS_STATE = 'RESET_GROUPS_STATE';
    static GET_GROUP_TAX_HIERARCHY = 'GET_GROUP_TAX_HIERARCHY';
    static GET_GROUP_TAX_HIERARCHY_RESPONSE = 'GET_GROUP_TAX_HIERARCHY_RESPONSE';
    static SHOW_ADD_GROUP_FORM = 'SHOW_ADD_GROUP_FORM';
    static SHOW_ADD_ACCOUNT_FORM = 'SHOW_ADD_ACCOUNT_FORM';
    static HIDE_ADD_ACCOUNT_FORM = 'HIDE_ADD_ACCOUNT_FORM';
    static SHOW_EDIT_ACCOUNT_FORM = 'SHOW_EDIT_ACCOUNT_FORM';
    static HIDE_EDIT_ACCOUNT_FORM = 'HIDE_EDIT_ACCOUNT_FORM';
    static SHOW_ADD_NEW_FORM = 'SHOW_ADD_NEW_FORM';
    static HIDE_ADD_NEW_FORM = 'HIDE_ADD_NEW_FORM';
    static SET_ACTIVE_GROUP = 'SET_ACTIVE_GROUP';
    static GET_GROUP_WITH_ACCOUNTS = 'GET_GROUP_WITH_ACCOUNTS';
    static SET_GROUP_ACCOUNTS_SEARCH_STRING = 'SET_GROUP_ACCOUNTS_SEARCH_STRING';
    static OPEN_ADD_AND_MANAGE_FROM_OUTSIDE = 'OPEN_ADD_AND_MANAGE_FROM_OUTSIDE';
    static HIDE_ADD_AND_MANAGE_FROM_OUTSIDE = 'HIDE_ADD_AND_MANAGE_FROM_OUTSIDE';
    static GET_GROUP_WITH_ACCOUNTS_RESPONSE = 'GET_GROUP_WITH_ACCOUNTS_RESPONSE';
    [key: string]: any;
}

export class ItemOnBoardingActions {
    static SET_ON_BOARDING_STATUS = 'SET_ON_BOARDING_STATUS';
    static SET_ON_BOARDING_TYPE = 'SET_ON_BOARDING_TYPE';
    static SET_ITEM_UPDATE_PROGRESS = 'SET_ITEM_UPDATE_PROGRESS';
    static RESET_ON_BOARDING = 'RESET_ON_BOARDING';
    [key: string]: any;
}

// Company Actions class
export class CompanyActions {
    static RESET_USER_CHOSEN_FINANCIAL_YEAR = 'RESET_USER_CHOSEN_FINANCIAL_YEAR';
    static SET_COMPANY_BRANCH = 'SET_COMPANY_BRANCH';
    static GET_COMPANY_USER_RESPONSE = 'GET_COMPANY_USER_RESPONSE';
    static SET_ACTIVE_COMPANY_DATA = 'SET_ACTIVE_COMPANY_DATA';
    static RESET_ACTIVE_COMPANY_DATA = 'RESET_ACTIVE_COMPANY_DATA';
    static GET_TAX = 'GET_TAX';
    static GET_TAX_RESPONSE = 'GET_TAX_RESPONSE';
    static SET_ACTIVE_COMPANY = 'SET_ACTIVE_COMPANY';
    static GET_REGISTRATION_ACCOUNT = 'GET_REGISTRATION_ACCOUNT';
    static GET_REGISTRATION_ACCOUNT_RESPONSE = 'GET_REGISTRATION_ACCOUNT_RESPONSE';
    static SET_IS_TCS_TDS_APPLICABLE = 'SET_IS_TCS_TDS_APPLICABLE';
    static GET_ALL_INTEGRATED_BANK = 'GET_ALL_INTEGRATED_BANK';
    static GET_ALL_INTEGRATED_BANK_RESPONSE = 'GET_ALL_INTEGRATED_BANK_RESPONSE';
    static CREATE_NEW_COMPANY = 'CREATE_NEW_COMPANY';
    static RESET_CREATE_COMPANY_FLAG = 'RESET_CREATE_COMPANY_FLAG';
    static CREATE_NEW_COMPANY_RESPONSE = 'CREATE_NEW_COMPANY_RESPONSE';
    static USER_SELECTED_PLANS = 'USER_SELECTED_PLANS';
    static TOTAL_COMPANIES = 'TOTAL_COMPANIES';
    static CURRENT_COMPANY_CURRENCY = 'CURRENT_COMPANY_CURRENCY';
    static USER_CAREATE_COMPANY = 'USER_CAREATE_COMPANY';
    static USER_CAREATE_BRANCH = 'USER_CAREATE_BRANCH';
    static REFRESH_COMPANIES = 'REFRESH_COMPANIES';
    static REFRESH_COMPANIES_RESPONSE = 'REFRESH_COMPANIES_RESPONSE';
    static SET_MULTIPLE_CURRENCY_FIELD = 'SET_MULTIPLE_CURRENCY_FIELD';
    static USER_REMOVE_COMPANY_CREATE_SESSION = 'USER_REMOVE_COMPANY_CREATE_SESSION';
    static SET_USER_CHOSEN_FINANCIAL_YEAR = 'SET_USER_CHOSEN_FINANCIAL_YEAR';
    static GET_STATE_DETAILS_RESPONSE = 'GET_STATE_DETAILS_RESPONSE';
    static CHANGE_COMPANY_RESPONSE = 'CHANGE_COMPANY_RESPONSE';
    static SET_STATE_DETAILS_REQUEST = 'SET_STATE_DETAILS_REQUEST';
    static SET_STATE_DETAILS_RESPONSE = 'SET_STATE_DETAILS_RESPONSE';
    static SET_APPLICATION_DATE_RESPONSE = 'SET_APPLICATION_DATE_RESPONSE';
    static RESET_APPLICATION_DATE = 'RESET_APPLICATION_DATE';
    static SET_CONTACT_NO = 'SET_CONTACT_NO';
    static CREATE_COMPANY = 'CREATE_COMPANY';
    static CREATE_COMPANY_RESPONSE = 'CREATE_COMPANY_RESPONSE';
    [key: string]: any;
}

// VerifyMobile Actions class
export class VerifyMobileActions {
    static SET_VERIFIACATION_MOBILENO = 'SET_VERIFIACATION_MOBILENO';
    static SHOW_VERIFICATION_BOX = 'SHOW_VERIFICATION_BOX';
    static VERIFY_MOBILE_CODE_RESPONSE = 'VERIFY_MOBILE_CODE_RESPONSE';
    static HIDE_VERIFICATION_BOX = 'HIDE_VERIFICATION_BOX';
    [key: string]: any;
}

// AgingReport Actions class
export class AgingReportActions {
    static CREATE_DUE_DAY_RANGE = 'CREATE_DUE_DAY_RANGE';
    static DUE_DAY_RANGE_POPUP_OPEN = 'DUE_DAY_RANGE_POPUP_OPEN';
    static DUE_DAY_RANGE_POPUP_CLOSE = 'DUE_DAY_RANGE_POPUP_CLOSE';
    static CREATE_DUE_DAY_RANGE_RESPONSE = 'CREATE_DUE_DAY_RANGE_RESPONSE';
    static GET_DUE_DAY_RANGE_RESPONSE = 'GET_DUE_DAY_RANGE_RESPONSE';
    static GET_DUE_DAY_REPORT_RESPONSE = 'GET_DUE_DAY_REPORT_RESPONSE';
    static GET_DUE_DAY_REPORT = 'GET_DUE_DAY_REPORT';
    [key: string]: any;
}

// Audit Logs Actions constants
export const AUDIT_LOGS_ACTIONS = {
    GET_LOGS: 'GET_LOGS',
    GET_LOGS_RESPONSE: 'GET_LOGS_RESPONSE',
    LOAD_MORE_LOGS: 'LOAD_MORE_LOGS',
    LOAD_MORE_LOGS_RESPONSE: 'LOAD_MORE_LOGS_RESPONSE',
    AUDIT_LOGS_RESET: 'AUDIT_LOGS_RESET'
};

export const AUDIT_LOGS_ACTIONS_V2 = {
    GET_LOGS_REQUEST: 'GET_LOGS_REQUEST',
    GET_LOGS_RESPONSE_V2: 'GET_LOGS_RESPONSE_V2'
};

// GST related constants
export const GSTR_ACTIONS = {
    GET_GSTR: 'GET_GSTR',
    GET_GSTR_RESPONSE: 'GET_GSTR_RESPONSE',
    GST_SAVE_GSP_SESSION: 'GST_SAVE_GSP_SESSION',
    GST_SAVE_GSP_SESSION_RESPONSE: 'GST_SAVE_GSP_SESSION_RESPONSE',
    GST_SAVE_GSP_SESSION_WITH_OTP: 'GST_SAVE_GSP_SESSION_WITH_OTP',
    GST_SAVE_GSP_SESSION_WITH_OTP_RESPONSE: 'GST_SAVE_GSP_SESSION_WITH_OTP_RESPONSE',
    GST_GET_GSP_SESSION: 'GST_GET_GSP_SESSION',
    GST_GET_GSP_SESSION_RESPONSE: 'GST_GET_GSP_SESSION_RESPONSE',
    FILE_GSTR1: 'FILE_GSTR1',
    FILE_GSTR1_RESPONSE: 'FILE_GSTR1_RESPONSE',
    GST_RESET_ASIDE_FLAGS: 'GST_RESET_ASIDE_FLAGS',
    SET_ACTIVE_COMPANY_GSTIN: 'SET_ACTIVE_COMPANY_GSTIN',
    GET_GSTR1_OVERVIEW: 'GET_GSTR1_OVERVIEW',
    GET_GSTR1_OVERVIEW_RESPONSE: 'GET_GSTR1_OVERVIEW_RESPONSE',
    RESET_GSTR1_OVERVIEW_RESPONSE: 'RESET_GSTR1_OVERVIEW_RESPONSE',
    GET_GSTR3B_OVERVIEW: 'GET_GSTR3B_OVERVIEW',
    GET_GSTR3B_OVERVIEW_RESPONSE: 'GET_GSTR3B_OVERVIEW_RESPONSE',
    RESET_GSTR3B_OVERVIEW_RESPONSE: 'RESET_GSTR3B_OVERVIEW_RESPONSE',
    GET_GSTR2_OVERVIEW: 'GET_GSTR2_OVERVIEW',
    GET_GSTR2_OVERVIEW_RESPONSE: 'GET_GSTR2_OVERVIEW_RESPONSE',
    RESET_GSTR2_OVERVIEW_RESPONSE: 'RESET_GSTR2_OVERVIEW_RESPONSE',
    GET_SUMMARY_TRANSACTIONS: 'GET_SUMMARY_TRANSACTIONS',
    GET_SUMMARY_TRANSACTIONS_RESPONSE: 'GET_SUMMARY_TRANSACTIONS_RESPONSE',
    GET_GSTR1_SUMMARY_DETAILS: 'GET_GSTR1_SUMMARY_DETAILS',
    GET_GSTR1_SUMMARY_DETAILS_RESPONSE: 'GET_GSTR1_SUMMARY_DETAILS_RESPONSE',
    CURRENT_PERIOD: 'CURRENT_PERIOD'
};

export const GST_RETURN_ACTIONS = {
    GET_GST_RETURN: 'GET_GST_RETURN',
    GET_GST_RETURN_RESPONSE: 'GET_GST_RETURN_RESPONSE',
    FILE_JIO_GST: 'FILE_JIO_GST',
    FILE_JIO_GST_RESPONSE: 'FILE_JIO_GST_RESPONSE'
};

export const GST_RECONCILE_ACTIONS = {
    GET_GST_RECONCILE: 'GET_GST_RECONCILE',
    GET_GST_RECONCILE_RESPONSE: 'GET_GST_RECONCILE_RESPONSE',
    GST_RECONCILE_OTP_REQUEST: 'GST_RECONCILE_OTP_REQUEST',
    GST_RECONCILE_OTP_RESPONSE: 'GST_RECONCILE_OTP_RESPONSE',
    GST_RECONCILE_VERIFY_OTP_REQUEST: 'GST_RECONCILE_VERIFY_OTP_REQUEST',
    GST_RECONCILE_VERIFY_OTP_RESPONSE: 'GST_RECONCILE_VERIFY_OTP_RESPONSE',
    GST_RECONCILE_INVOICE_REQUEST: 'GST_RECONCILE_INVOICE_REQUEST',
    GST_RECONCILE_INVOICE_RESPONSE: 'GST_RECONCILE_INVOICE_RESPONSE'
};

// Additional inventory constants
export const INVENTORY_BRANCH_TRANSFER = {
    GET_BRANCH_TRANSFER: 'GET_BRANCH_TRANSFER',
    GET_BRANCH_TRANSFER_RESPONSE: 'GET_BRANCH_TRANSFER_RESPONSE',
    CREATE_TRANSFER: 'CREATE_TRANSFER',
    CREATE_TRANSFER_RESPONSE: 'CREATE_TRANSFER_RESPONSE',
    RESET_BRANCH_TRANSFER_STATE: 'RESET_BRANCH_TRANSFER_STATE'
};

export const INVENTORY_LINKED_STOCKS = {
    GET_LINKED_STOCKS: 'GET_LINKED_STOCKS',
    GET_LINKED_STOCKS_RESPONSE: 'GET_LINKED_STOCKS_RESPONSE'
};

export const INVENTORY_ENTRY_ACTIONS = {
    GET_INVENTORY_ENTRY: 'GET_INVENTORY_ENTRY',
    GET_INVENTORY_ENTRY_RESPONSE: 'GET_INVENTORY_ENTRY_RESPONSE',
    CREATE_ENTRY: 'CREATE_ENTRY',
    CREATE_ENTRY_RESPONSE: 'CREATE_ENTRY_RESPONSE',
    CREATE_TRANSFER_ENTRY: 'CREATE_TRANSFER_ENTRY',
    CREATE_TRANSFER_ENTRY_RESPONSE: 'CREATE_TRANSFER_ENTRY_RESPONSE'
};

export const INVENTORY_REPORT_ACTIONS = {
    GET_INVENTORY_REPORT: 'GET_INVENTORY_REPORT',
    GET_INVENTORY_REPORT_RESPONSE: 'GET_INVENTORY_REPORT_RESPONSE',
    GENERATE_REPORT_RESPONSE: 'GENERATE_REPORT_RESPONSE'
};

export const INVENTORY_USER_ACTIONS = {
    GET_INVENTORY_USER: 'GET_INVENTORY_USER',
    GET_INVENTORY_USER_RESPONSE: 'GET_INVENTORY_USER_RESPONSE',
    GET_ALL_USERS_RESPONSE: 'GET_ALL_USERS_RESPONSE',
    CREATE_USER: 'CREATE_USER',
    CREATE_USER_RESPONSE: 'CREATE_USER_RESPONSE'
};

export const EWAYBILL_ACTIONS = {
    GET_EWAYBILL: 'GET_EWAYBILL',
    GET_EWAYBILL_RESPONSE: 'GET_EWAYBILL_RESPONSE',
    LOGIN_EAYBILL_USER: 'LOGIN_EAYBILL_USER',
    LOGIN_EAYBILL_USER_RESPONSE: 'LOGIN_EAYBILL_USER_RESPONSE',
    GENERATE_EWAYBILL: 'GENERATE_EWAYBILL',
    GENERATE_EWAYBILL_RESPONSE: 'GENERATE_EWAYBILL_RESPONSE',
    IS_LOOGEDIN_USER_EWAYBILL_RESPONSE: 'IS_LOOGEDIN_USER_EWAYBILL_RESPONSE',
    ADD_TRANSPORTER: 'ADD_TRANSPORTER',
    ADD_TRANSPORTER_RESPONSE: 'ADD_TRANSPORTER_RESPONSE',
    UPDATE_TRANSPORTER: 'UPDATE_TRANSPORTER',
    UPDATE_TRANSPORTER_RESPONSE: 'UPDATE_TRANSPORTER_RESPONSE',
    GET_ALL_TRANSPORTER_RESPONSE: 'GET_ALL_TRANSPORTER_RESPONSE',
    DELETE_TRANSPORTER_RESPONSE: 'DELETE_TRANSPORTER_RESPONSE',
    UPDATE_EWAY_VEHICLE: 'UPDATE_EWAY_VEHICLE',
    UPDATE_EWAY_VEHICLE_RESPONSE: 'UPDATE_EWAY_VEHICLE_RESPONSE',
    CANCEL_EWAYBILL: 'CANCEL_EWAYBILL',
    CANCEL_EWAYBILL_RESPONSE: 'CANCEL_EWAYBILL_RESPONSE',
    RESET_ALL_TRANSPORTER_RESPONSE: 'RESET_ALL_TRANSPORTER_RESPONSE',
    GET_All_LIST_EWAYBILLS: 'GET_All_LIST_EWAYBILLS',
    GET_All_FILTERED_LIST_EWAYBILLS: 'GET_All_FILTERED_LIST_EWAYBILLS',
    GET_All_LIST_EWAYBILLS_RESPONSE: 'GET_All_LIST_EWAYBILLS_RESPONSE',
    GET_All_FILTERED_LIST_EWAYBILLS_RESPONSE: 'GET_All_FILTERED_LIST_EWAYBILLS_RESPONSE'
};

export const PURCHASE_INVOICE_ACTIONS = {
    GET_PURCHASE_INVOICE: 'GET_PURCHASE_INVOICE',
    GET_PURCHASE_INVOICE_RESPONSE: 'GET_PURCHASE_INVOICE_RESPONSE',
    SET_TAXES_FOR_COMPANY: 'SET_TAXES_FOR_COMPANY'
};

export const INVOICE_RECEIPT_ACTIONS = {
    GET_INVOICE_RECEIPT: 'GET_INVOICE_RECEIPT',
    GET_INVOICE_RECEIPT_RESPONSE: 'GET_INVOICE_RECEIPT_RESPONSE',
    GET_ALL_INVOICE_RECEIPT: 'GET_ALL_INVOICE_RECEIPT',
    GET_ALL_INVOICE_RECEIPT_RESPONSE: 'GET_ALL_INVOICE_RECEIPT_RESPONSE',
    DELETE_INVOICE_RECEIPT: 'DELETE_INVOICE_RECEIPT',
    DELETE_INVOICE_RECEIPT_RESPONSE: 'DELETE_INVOICE_RECEIPT_RESPONSE',
    UPDATE_INVOICE_RECEIPT_RESPONSE: 'UPDATE_INVOICE_RECEIPT_RESPONSE',
    UPDATE_VOUCHER_DETAILS_AFTER_VOUCHER_UPDATE: 'UPDATE_VOUCHER_DETAILS_AFTER_VOUCHER_UPDATE',
    GET_VOUCHER_DETAILS: 'GET_VOUCHER_DETAILS',
    GET_VOUCHER_DETAILS_RESPONSE: 'GET_VOUCHER_DETAILS_RESPONSE',
    GET_VOUCHER_DETAILS_RESPONSEV4: 'GET_VOUCHER_DETAILS_RESPONSEV4',
    RESET_VOUCHER_DETAILS: 'RESET_VOUCHER_DETAILS',
    DOWNLOAD_VOUCHER_REQUEST: 'DOWNLOAD_VOUCHER_REQUEST',
    DOWNLOAD_VOUCHER_RESPONSE: 'DOWNLOAD_VOUCHER_RESPONSE',
    INVOICE_SET_VOUCHER_FOR_DETAILS: 'INVOICE_SET_VOUCHER_FOR_DETAILS',
    INVOICE_RESET_VOUCHER_FOR_DETAILS: 'INVOICE_RESET_VOUCHER_FOR_DETAILS',
    GET_SALESRAGISTED_DETAILS: 'GET_SALESRAGISTED_DETAILS',
    GET_SALESRAGISTED_DETAILS_RESPONSE: 'GET_SALESRAGISTED_DETAILS_RESPONSE',
    GET_PURCHASE_REGISTERED_DETAILS: 'GET_PURCHASE_REGISTERED_DETAILS',
    GET_PURCHASE_REGISTERED_DETAILS_RESPONSE: 'GET_PURCHASE_REGISTERED_DETAILS_RESPONSE'
};

export const INVOICE_ACTIONS = {
    GET_INVOICE: 'GET_INVOICE',
    GET_INVOICE_RESPONSE: 'GET_INVOICE_RESPONSE',
    DOWNLOAD_INVOICE_EXPORTED: 'DOWNLOAD_INVOICE_EXPORTED',
    DOWNLOAD_INVOICE_EXPORTED_RESPONSE: 'DOWNLOAD_INVOICE_EXPORTED_RESPONSE',
    DOWNLOAD_INVOICE_RESPONSE: 'DOWNLOAD_INVOICE_RESPONSE',
    GET_ALL_LEDGERS_FOR_INVOICE: 'GET_ALL_LEDGERS_FOR_INVOICE',
    GET_ALL_LEDGERS_FOR_INVOICE_RESPONSE: 'GET_ALL_LEDGERS_FOR_INVOICE_RESPONSE',
    RESET_PENDING_DATA: 'RESET_PENDING_DATA',
    GENERATE_BULK_E_INVOICE: 'GENERATE_BULK_E_INVOICE',
    GENERATE_BULK_E_INVOICE_RESPONSE: 'GENERATE_BULK_E_INVOICE_RESPONSE',
    RESET_BULK_E_INVOICE_RESPONSE: 'RESET_BULK_E_INVOICE_RESPONSE',
    SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION: 'SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION',
    RESET_ACTION_ON_INVOICE: 'RESET_ACTION_ON_INVOICE',
    MODIFIED_INVOICE_STATE_DATA: 'MODIFIED_INVOICE_STATE_DATA',
    PREVIEW_INVOICE: 'PREVIEW_INVOICE',
    PREVIEW_INVOICE_RESPONSE: 'PREVIEW_INVOICE_RESPONSE',
    PREVIEW_OF_GENERATED_INVOICE: 'PREVIEW_OF_GENERATED_INVOICE',
    PREVIEW_OF_GENERATED_INVOICE_RESPONSE: 'PREVIEW_OF_GENERATED_INVOICE_RESPONSE',
    UPDATE_GENERATED_INVOICE_RESPONSE: 'UPDATE_GENERATED_INVOICE_RESPONSE',
    RESET_INVOICE_DATA: 'RESET_INVOICE_DATA',
    INVOICE_GENERATION_COMPLETED: 'INVOICE_GENERATION_COMPLETED',
    GENERATE_INVOICE_RESPONSE: 'GENERATE_INVOICE_RESPONSE',
    GENERATE_BULK_INVOICE_RESPONSE: 'GENERATE_BULK_INVOICE_RESPONSE',
    GET_INVOICE_TEMPLATE_DETAILS_RESPONSE: 'GET_INVOICE_TEMPLATE_DETAILS_RESPONSE',
    ACTION_ON_INVOICE: 'ACTION_ON_INVOICE',
    ACTION_ON_INVOICE_RESPONSE: 'ACTION_ON_INVOICE_RESPONSE',
    DELETE_INVOICE_RESPONSE: 'DELETE_INVOICE_RESPONSE'
};

// Manufacturing actions
export const MANUFACTURING_ACTIONS = {
    GET_MANUFACTURING: 'GET_MANUFACTURING',
    SET_MANUFACTURING: 'SET_MANUFACTURING',
    RESET_MANUFACTURING: 'RESET_MANUFACTURING',
    MF_REPORT: 'MF_REPORT',
    MF_REPORT_RESPONSE: 'MF_REPORT_RESPONSE',
    GET_STOCK_WITH_RATE: 'GET_STOCK_WITH_RATE',
    GET_STOCK_WITH_RATE_RESPONSE: 'GET_STOCK_WITH_RATE_RESPONSE',
    CREATE_MF_ITEM: 'CREATE_MF_ITEM',
    CREATE_MF_ITEM_RESPONSE: 'CREATE_MF_ITEM_RESPONSE',
    UPDATE_MF_ITEM: 'UPDATE_MF_ITEM',
    UPDATE_MF_ITEM_RESPONSE: 'UPDATE_MF_ITEM_RESPONSE',
    DELETE_MF_ITEM: 'DELETE_MF_ITEM',
    DELETE_MF_ITEM_RESPONSE: 'DELETE_MF_ITEM_RESPONSE',
    SET_MF_ITEM_UNIQUENAME_IN_STORE: 'SET_MF_ITEM_UNIQUENAME_IN_STORE',
    REMOVE_MF_ITEM_UNIQUENAME_FROM_STORE: 'REMOVE_MF_ITEM_UNIQUENAME_FROM_STORE'
};

// Permission actions
export const PERMISSION_ACTIONS = {
    GET_PERMISSIONS: 'GET_PERMISSIONS',
    SET_PERMISSIONS: 'SET_PERMISSIONS',
    RESET_PERMISSIONS: 'RESET_PERMISSIONS',
    GET_ROLES: 'GET_ROLES',
    GET_ROLES_RESPONSE: 'GET_ROLES_RESPONSE',
    CREATE_ROLE: 'CREATE_ROLE',
    CREATE_ROLE_RESPONSE: 'CREATE_ROLE_RESPONSE',
    UPDATE_ROLE: 'UPDATE_ROLE',
    UPDATE_ROLE_RESPONSE: 'UPDATE_ROLE_RESPONSE',
    DELETE_ROLE: 'DELETE_ROLE',
    DELETE_ROLE_RESPONSE: 'DELETE_ROLE_RESPONSE',
    GET_ALL_PAGES: 'GET_ALL_PAGES',
    GET_ALL_PAGES_RESPONSE: 'GET_ALL_PAGES_RESPONSE',
    GET_ALL_PERMISSIONS_RESPONSE: 'GET_ALL_PERMISSIONS_RESPONSE',
    PUSH_TEMP_ROLE_IN_STORE: 'PUSH_TEMP_ROLE_IN_STORE',
    REMOVE_NEWLY_CREATED_ROLE_FROM_STORE: 'REMOVE_NEWLY_CREATED_ROLE_FROM_STORE'
};

// Proforma actions
export const PROFORMA_ACTIONS = {
    GET_PROFORMA: 'GET_PROFORMA',
    SET_PROFORMA: 'SET_PROFORMA',
    RESET_PROFORMA: 'RESET_PROFORMA',
    GENERATE_PROFORMA_REQUEST: 'GENERATE_PROFORMA_REQUEST',
    GENERATE_PROFORMA_RESPONSE: 'GENERATE_PROFORMA_RESPONSE',
    GET_ALL_PROFORMA_REQUEST: 'GET_ALL_PROFORMA_REQUEST',
    GET_ALL_PROFORMA_RESPONSE: 'GET_ALL_PROFORMA_RESPONSE',
    GET_PROFORMA_DETAILS_REQUEST: 'GET_PROFORMA_DETAILS_REQUEST',
    GET_PROFORMA_DETAILS_RESPONSE: 'GET_PROFORMA_DETAILS_RESPONSE',
    UPDATE_PROFORMA_REQUEST: 'UPDATE_PROFORMA_REQUEST',
    UPDATE_PROFORMA_RESPONSE: 'UPDATE_PROFORMA_RESPONSE',
    DELETE_PROFORMA_REQUEST: 'DELETE_PROFORMA_REQUEST',
    DELETE_PROFORMA_RESPONSE: 'DELETE_PROFORMA_RESPONSE',
    UPDATE_PROFORMA_ACTION: 'UPDATE_PROFORMA_ACTION',
    UPDATE_PROFORMA_ACTION_RESPONSE: 'UPDATE_PROFORMA_ACTION_RESPONSE',
    GET_ESTIMATE_VERSIONS: 'GET_ESTIMATE_VERSIONS',
    GET_ESTIMATE_VERSIONS_RESPONSE: 'GET_ESTIMATE_VERSIONS_RESPONSE',
    GENERATE_PROFORMA_FROM_ESTIMATE: 'GENERATE_PROFORMA_FROM_ESTIMATE',
    GENERATE_PROFORMA_FROM_ESTIMATE_RESPONSE: 'GENERATE_PROFORMA_FROM_ESTIMATE_RESPONSE',
    GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES: 'GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES',
    GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES_RESPONSE: 'GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES_RESPONSE',
    RESET_ACTIVE_VOUCHER: 'RESET_ACTIVE_VOUCHER',
    SET_VOUCHER_FOR_DETAILS: 'SET_VOUCHER_FOR_DETAILS',
    RESET_VOUCHER_FOR_DETAILS: 'RESET_VOUCHER_FOR_DETAILS'
};

// Purchase order actions
export const PURCHASE_ORDER_ACTIONS = {
    GET_PURCHASE_ORDER: 'GET_PURCHASE_ORDER',
    SET_PURCHASE_ORDER: 'SET_PURCHASE_ORDER',
    RESET_PURCHASE_ORDER: 'RESET_PURCHASE_ORDER',
    SET_FILTERS: 'SET_FILTERS',
    PO_PREVIEW_SEARCH: 'PO_PREVIEW_SEARCH'
};

// Purchase record actions
export const PURCHASE_RECORD_ACTIONS = {
    GET_PURCHASE_RECORD: 'GET_PURCHASE_RECORD',
    SET_PURCHASE_RECORD: 'SET_PURCHASE_RECORD',
    RESET_PURCHASE_RECORD: 'RESET_PURCHASE_RECORD',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    RESET_UPDATE_DETAILS: 'RESET_UPDATE_DETAILS'
};

// Sales actions
export const SALES_ACTIONS = {
    GET_SALES: 'GET_SALES',
    SET_SALES: 'SET_SALES',
    RESET_SALES: 'RESET_SALES',
    STOCK_AC_SUCCESS: 'STOCK_AC_SUCCESS',
    GET_ACCOUNT_DETAILS_RESPONSE: 'GET_ACCOUNT_DETAILS_RESPONSE',
    ADD_ACCOUNT_DETAILS: 'ADD_ACCOUNT_DETAILS',
    ADD_ACCOUNT_DETAILS_RESPONSE: 'ADD_ACCOUNT_DETAILS_RESPONSE',
    UPDATE_ACCOUNT_DETAILS: 'UPDATE_ACCOUNT_DETAILS',
    UPDATE_ACCOUNT_DETAILS_RESPONSE: 'UPDATE_ACCOUNT_DETAILS_RESPONSE',
    RESET_ACCOUNT_DETAILS: 'RESET_ACCOUNT_DETAILS'
};

// Additional constants that might be missing
export const COMMON_ACTIONS = {
    RESET_APPLICATION_DATA: 'RESET_APPLICATION_DATA'
};
