/**
 * Comprehensive placeholder constants generated from reducer analysis
 * These provide complete compatibility for all used constants
 */

// INVOICE constants
export const INVOICE = {
    GET_INVOICE_TEMPLATE_DETAILS: 'GET_INVOICE_TEMPLATE_DETAILS',
    GET_INVOICE_TEMPLATE_DETAILS_RESPONSE: 'GET_INVOICE_TEMPLATE_DETAILS_RESPONSE',
    UPDATE_INVOICE_TEMPLATE: 'UPDATE_INVOICE_TEMPLATE',
    UPDATE_INVOICE_TEMPLATE_RESPONSE: 'UPDATE_INVOICE_TEMPLATE_RESPONSE',
    DELETE_INVOICE_TEMPLATE: 'DELETE_INVOICE_TEMPLATE',
    DELETE_INVOICE_TEMPLATE_RESPONSE: 'DELETE_INVOICE_TEMPLATE_RESPONSE',
    SETTING: {
        GET_INVOICE_SETTING: 'GET_INVOICE_SETTING',
        GET_INVOICE_SETTING_RESPONSE: 'GET_INVOICE_SETTING_RESPONSE',
        DELETE_WEBHOOK_RESPONSE: 'DELETE_WEBHOOK_RESPONSE',
        UPDATE_INVOICE_EMAIL_RESPONSE: 'UPDATE_INVOICE_EMAIL_RESPONSE',
        SAVE_INVOICE_WEBHOOK_RESPONSE: 'SAVE_INVOICE_WEBHOOK_RESPONSE',
        UPDATE_INVOICE_SETTING_RESPONSE: 'UPDATE_INVOICE_SETTING_RESPONSE',
        GET_RAZORPAY_DETAIL_RESPONSE: 'GET_RAZORPAY_DETAIL_RESPONSE',
        UPDATE_RAZORPAY_DETAIL_RESPONSE: 'UPDATE_RAZORPAY_DETAIL_RESPONSE',
        DELETE_RAZORPAY_DETAIL_RESPONSE: 'DELETE_RAZORPAY_DETAIL_RESPONSE',
        DELETE_INVOICE_EMAIL_RESPONSE: 'DELETE_INVOICE_EMAIL_RESPONSE',
        SAVE_RAZORPAY_DETAIL_RESPONSE: 'SAVE_RAZORPAY_DETAIL_RESPONSE'
    },
    RECURRING: {
        GET_RECURRING_INVOICES: 'GET_RECURRING_INVOICES',
        GET_RECURRING_INVOICES_RESPONSE: 'GET_RECURRING_INVOICES_RESPONSE',
        GET_RECURRING_INVOICE_DATA_RESPONSE: 'GET_RECURRING_INVOICE_DATA_RESPONSE',
        CREATE_RECURRING_INVOICE: 'CREATE_RECURRING_INVOICE',
        CREATE_RECURRING_INVOICE_RESPONSE: 'CREATE_RECURRING_INVOICE_RESPONSE',
        UPDATE_RECURRING_INVOICE: 'UPDATE_RECURRING_INVOICE',
        UPDATE_RECURRING_INVOICE_RESPONSE: 'UPDATE_RECURRING_INVOICE_RESPONSE',
        RESET_RECURRING_INVOICE_REQUEST: 'RESET_RECURRING_INVOICE_REQUEST',
        NO_PERMISSIONS_RECURRING_INVOICE: 'NO_PERMISSIONS_RECURRING_INVOICE'
    },
    TEMPLATE: {
        GET_INVOICE_TEMPLATE: 'GET_INVOICE_TEMPLATE',
        GET_INVOICE_TEMPLATE_RESPONSE: 'GET_INVOICE_TEMPLATE_RESPONSE',
        GET_SAMPLE_TEMPLATES_RESPONSE: 'GET_SAMPLE_TEMPLATES_RESPONSE',
        GET_ALL_CREATED_TEMPLATES_RESPONSE: 'GET_ALL_CREATED_TEMPLATES_RESPONSE',
        SET_TEMPLATE_AS_DEFAULT_RESPONSE: 'SET_TEMPLATE_AS_DEFAULT_RESPONSE',
        DELETE_TEMPLATE_RESPONSE: 'DELETE_TEMPLATE_RESPONSE'
    }
};

// Inventory related constants
export const InventoryActionsConst = {
    GetInventory: 'GetInventory',
    GetInventoryResponse: 'GetInventoryResponse',
    CreateStock: 'CreateStock',
    CreateStockResponse: 'CreateStockResponse',
    UpdateStock: 'UpdateStock',
    UpdateStockResponse: 'UpdateStockResponse',
    DeleteStock: 'DeleteStock',
    DeleteStockResponse: 'DeleteStockResponse',
    GetStock: 'GetStock',
    GetStockResponse: 'GetStockResponse',
    GetStockWithUniqueName: 'GetStockWithUniqueName',
    GetStockWithUniqueNameResponse: 'GetStockWithUniqueNameResponse',
    ShowLoadingForStockEditInProcess: 'ShowLoadingForStockEditInProcess',
    HideLoadingForStockEditInProcess: 'HideLoadingForStockEditInProcess',
    ResetActiveStock: 'ResetActiveStock',
    ResetInventoryState: 'ResetInventoryState',
    MoveStock: 'MoveStock',
    MoveStockResponse: 'MoveStockResponse',
    NewGroupAsidePane: 'NewGroupAsidePane',
    NewCustomUnitAsidePane: 'NewCustomUnitAsidePane',
    ManageInventoryAside: 'ManageInventoryAside',
    ShowBranchScreen: 'ShowBranchScreen',
    ShowBranchScreenSideBar: 'ShowBranchScreenSideBar',
    BulkStockResponse: 'BulkStockResponse'
};

export const CUSTOM_STOCK_UNIT_ACTIONS = {
    GET_STOCK_MAPPED_UNITS_RESPONSE: 'GET_STOCK_MAPPED_UNITS_RESPONSE',
    GET_STOCK_MAPPED_UNIT_UNIQUE_NAME_RESPONSE: 'GET_STOCK_MAPPED_UNIT_UNIQUE_NAME_RESPONSE',
    GET_STOCK_UNIT_RESPONSE: 'GET_STOCK_UNIT_RESPONSE',
    CREATE_STOCK_UNIT: 'CREATE_STOCK_UNIT',
    RESET_STOCK_UNIT_RESPONSE: 'RESET_STOCK_UNIT_RESPONSE',
    CREATE_STOCK_UNIT_RESPONSE: 'CREATE_STOCK_UNIT_RESPONSE',
    UPDATE_STOCK_UNIT: 'UPDATE_STOCK_UNIT',
    UPDATE_STOCK_UNIT_RESPONSE: 'UPDATE_STOCK_UNIT_RESPONSE',
    DELETE_STOCK_UNIT: 'DELETE_STOCK_UNIT',
    DELETE_STOCK_UNIT_RESPONSE: 'DELETE_STOCK_UNIT_RESPONSE',
    GET_STOCK_UNIT_NAME: 'GET_STOCK_UNIT_NAME',
    GET_STOCK_UNIT_NAME_RESPONSE: 'GET_STOCK_UNIT_NAME_RESPONSE'
};

export const STOCKS_REPORT_ACTIONS = {
    GET_STOCKS_REPORT_RESPONSE: 'GET_STOCKS_REPORT_RESPONSE',
    GET_GROUP_STOCKS_REPORT: 'GET_GROUP_STOCKS_REPORT',
    GET_STOCKS_REPORT: 'GET_STOCKS_REPORT',
    GET_GROUP_STOCKS_REPORT_RESPONSE: 'GET_GROUP_STOCKS_REPORT_RESPONSE'
};

// AgingReportActions constants
export const AgingReportActions = {
    CREATE_DUE_DAY_RANGE: 'CREATE_DUE_DAY_RANGE',
    DUE_DAY_RANGE_POPUP_OPEN: 'DUE_DAY_RANGE_POPUP_OPEN',
    DUE_DAY_RANGE_POPUP_CLOSE: 'DUE_DAY_RANGE_POPUP_CLOSE',
    CREATE_DUE_DAY_RANGE_RESPONSE: 'CREATE_DUE_DAY_RANGE_RESPONSE',
    GET_DUE_DAY_RANGE_RESPONSE: 'GET_DUE_DAY_RANGE_RESPONSE',
    GET_DUE_DAY_REPORT_RESPONSE: 'GET_DUE_DAY_REPORT_RESPONSE',
    GET_DUE_DAY_REPORT: 'GET_DUE_DAY_REPORT',
};

// COMMON_ACTIONS constants
export const COMMON_ACTIONS = {
    RESET_APPLICATION_DATA: 'RESET_APPLICATION_DATA',
};

// AUDIT_LOGS_ACTIONS constants
export const AUDIT_LOGS_ACTIONS = {
    GET_LOGS: 'GET_LOGS',
    GET_LOGS_RESPONSE: 'GET_LOGS_RESPONSE',
    LOAD_MORE_LOGS: 'LOAD_MORE_LOGS',
    LOAD_MORE_LOGS_RESPONSE: 'LOAD_MORE_LOGS_RESPONSE',
    AUDIT_LOGS_RESET: 'AUDIT_LOGS_RESET',
};

// AUDIT_LOGS_ACTIONS_V2 constants
export const AUDIT_LOGS_ACTIONS_V2 = {
    GET_LOGS_REQUEST: 'GET_LOGS_REQUEST',
    GET_LOGS_RESPONSE_V2: 'GET_LOGS_RESPONSE_V2',
};

// LoginActions constants
export const LoginActions = {
    RESET_NEEDS_TO_REDIRECT_TO_LEDGER: 'RESET_NEEDS_TO_REDIRECT_TO_LEDGER',
    NEEDS_TO_REDIRECT_TO_LEDGER: 'NEEDS_TO_REDIRECT_TO_LEDGER',
    SignupWithEmailResponce: 'SignupWithEmailResponce',
    SIGNUP_WITH_GOOGLE_REQUEST: 'SIGNUP_WITH_GOOGLE_REQUEST',
    SIGNUP_WITH_GOOGLE_RESPONSE: 'SIGNUP_WITH_GOOGLE_RESPONSE',
    SignupWithEmailRequest: 'SignupWithEmailRequest',
    ResetSignupWithEmailState: 'ResetSignupWithEmailState',
    VerifyEmailRequest: 'VerifyEmailRequest',
    VerifyEmailResponce: 'VerifyEmailResponce',
    SignupWithMobileResponce: 'SignupWithMobileResponce',
    SignupWithMobileRequest: 'SignupWithMobileRequest',
    ResetSignupWithMobileState: 'ResetSignupWithMobileState',
    VerifyMobileRequest: 'VerifyMobileRequest',
    VerifyMobileResponce: 'VerifyMobileResponce',
    LogOut: 'LogOut',
    SOCIAL_LOGOUT_ATTEMPT: 'SOCIAL_LOGOUT_ATTEMPT',
    RESET_SOCIAL_LOGOUT_ATTEMPT: 'RESET_SOCIAL_LOGOUT_ATTEMPT',
    VerifyTwoWayAuthRequest: 'VerifyTwoWayAuthRequest',
    VerifyTwoWayAuthResponse: 'VerifyTwoWayAuthResponse',
    ResetTwoWayAuthModal: 'ResetTwoWayAuthModal',
    AddNewMobileNo: 'AddNewMobileNo',
    AddNewMobileNoResponse: 'AddNewMobileNoResponse',
    VerifyAddNewMobileNo: 'VerifyAddNewMobileNo',
    VerifyAddNewMobileNoResponse: 'VerifyAddNewMobileNoResponse',
    LoginWithPasswdRequest: 'LoginWithPasswdRequest',
    LoginWithPasswdResponse: 'LoginWithPasswdResponse',
    SignupWithPasswdRequest: 'SignupWithPasswdRequest',
    SignupWithPasswdResponse: 'SignupWithPasswdResponse',
    forgotPasswordRequest: 'forgotPasswordRequest',
    forgotPasswordResponse: 'forgotPasswordResponse',
    resetPasswordRequest: 'resetPasswordRequest',
    resetPasswordResponse: 'resetPasswordResponse',
    hideTwoWayOtpPopup: 'hideTwoWayOtpPopup',
    renewSessionResponse: 'renewSessionResponse',
    FetchUserDetailsResponse: 'FetchUserDetailsResponse',
    SetLoginStatus: 'SetLoginStatus',
    SetCurrencyInStore: 'SetCurrencyInStore',
    AutoLoginWithPasswdResponse: 'AutoLoginWithPasswdResponse',
};

// CommonActions constants
export const CommonActions = {
    SET_BRANCH_CONSOLIDATED: 'SET_BRANCH_CONSOLIDATED',
    SET_COMMON_LOCALE_DATA: 'SET_COMMON_LOCALE_DATA',
    SET_ACTIVE_LOCALE: 'SET_ACTIVE_LOCALE',
    SET_ACTIVE_FINANCIAL_YEAR: 'SET_ACTIVE_FINANCIAL_YEAR',
    SET_ACTIVE_THEME: 'SET_ACTIVE_THEME',
    SET_FILTERS: 'SET_FILTERS',
    GET_COUNTRY_RESPONSE: 'GET_COUNTRY_RESPONSE',
    GET_ALL_COUNTRY_RESPONSE: 'GET_ALL_COUNTRY_RESPONSE',
    GET_CALLING_CODES_RESPONSE: 'GET_CALLING_CODES_RESPONSE',
    GET_ONBOARDING_FORM: 'GET_ONBOARDING_FORM',
    GET_ONBOARDING_FORM_RESPONSE: 'GET_ONBOARDING_FORM_RESPONSE',
    GET_PARTY_TYPE_RESPONSE: 'GET_PARTY_TYPE_RESPONSE',
    RESET_ONBOARDING_FORM_RESPONSE: 'RESET_ONBOARDING_FORM_RESPONSE',
    RESET_COUNTRY: 'RESET_COUNTRY',
    ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
    SET_IMPORT_BANK_TRANSACTIONS_RESPONSE: 'SET_IMPORT_BANK_TRANSACTIONS_RESPONSE',
    HAS_UNSAVED_CHANGES: 'HAS_UNSAVED_CHANGES',
    BYPASS_UNSAVED_CHANGES: 'BYPASS_UNSAVED_CHANGES',
    REAUTH_PLAID: 'REAUTH_PLAID',
    SELECT_PRINTER: 'SELECT_PRINTER',
};

// CompanyActions constants
export const CompanyActions = {
    GET_STATE_DETAILS_RESPONSE: 'GET_STATE_DETAILS_RESPONSE',
    CHANGE_COMPANY_RESPONSE: 'CHANGE_COMPANY_RESPONSE',
    SET_STATE_DETAILS_REQUEST: 'SET_STATE_DETAILS_REQUEST',
    SET_STATE_DETAILS_RESPONSE: 'SET_STATE_DETAILS_RESPONSE',
    SET_APPLICATION_DATE_RESPONSE: 'SET_APPLICATION_DATE_RESPONSE',
    RESET_APPLICATION_DATE: 'RESET_APPLICATION_DATE',
    SET_CONTACT_NO: 'SET_CONTACT_NO',
    CREATE_COMPANY: 'CREATE_COMPANY',
    RESET_CREATE_COMPANY_FLAG: 'RESET_CREATE_COMPANY_FLAG',
    CREATE_COMPANY_RESPONSE: 'CREATE_COMPANY_RESPONSE',
    CREATE_NEW_COMPANY: 'CREATE_NEW_COMPANY',
    CREATE_NEW_COMPANY_RESPONSE: 'CREATE_NEW_COMPANY_RESPONSE',
    USER_SELECTED_PLANS: 'USER_SELECTED_PLANS',
    TOTAL_COMPANIES: 'TOTAL_COMPANIES',
    CURRENT_COMPANY_CURRENCY: 'CURRENT_COMPANY_CURRENCY',
    USER_CAREATE_COMPANY: 'USER_CAREATE_COMPANY',
    USER_CAREATE_BRANCH: 'USER_CAREATE_BRANCH',
    REFRESH_COMPANIES: 'REFRESH_COMPANIES',
    REFRESH_COMPANIES_RESPONSE: 'REFRESH_COMPANIES_RESPONSE',
    SET_MULTIPLE_CURRENCY_FIELD: 'SET_MULTIPLE_CURRENCY_FIELD',
    USER_REMOVE_COMPANY_CREATE_SESSION: 'USER_REMOVE_COMPANY_CREATE_SESSION',
    SET_USER_CHOSEN_FINANCIAL_YEAR: 'SET_USER_CHOSEN_FINANCIAL_YEAR',
    RESET_USER_CHOSEN_FINANCIAL_YEAR: 'RESET_USER_CHOSEN_FINANCIAL_YEAR',
    SET_COMPANY_BRANCH: 'SET_COMPANY_BRANCH',
    GET_COMPANY_USER_RESPONSE: 'GET_COMPANY_USER_RESPONSE',
    SET_ACTIVE_COMPANY_DATA: 'SET_ACTIVE_COMPANY_DATA',
    RESET_ACTIVE_COMPANY_DATA: 'RESET_ACTIVE_COMPANY_DATA',
    GET_TAX: 'GET_TAX',
    GET_TAX_RESPONSE: 'GET_TAX_RESPONSE',
    SET_ACTIVE_COMPANY: 'SET_ACTIVE_COMPANY',
    GET_REGISTRATION_ACCOUNT: 'GET_REGISTRATION_ACCOUNT',
    GET_REGISTRATION_ACCOUNT_RESPONSE: 'GET_REGISTRATION_ACCOUNT_RESPONSE',
    SET_IS_TCS_TDS_APPLICABLE: 'SET_IS_TCS_TDS_APPLICABLE',
    GET_ALL_INTEGRATED_BANK: 'GET_ALL_INTEGRATED_BANK',
    GET_ALL_INTEGRATED_BANK_RESPONSE: 'GET_ALL_INTEGRATED_BANK_RESPONSE',
};

// SETTINGS_PROFILE_ACTIONS constants
export const SETTINGS_PROFILE_ACTIONS = {
    UPDATE_PROFILE_RESPONSE: 'UPDATE_PROFILE_RESPONSE',
    PATCH_PROFILE_RESPONSE: 'PATCH_PROFILE_RESPONSE',
    GET_PROFILE_INFO: 'GET_PROFILE_INFO',
    GET_PROFILE_RESPONSE: 'GET_PROFILE_RESPONSE',
    GET_BRANCH_INFO_RESPONSE: 'GET_BRANCH_INFO_RESPONSE',
    PATCH_PROFILE: 'PATCH_PROFILE',
    RESET_PATCH_PROFILE: 'RESET_PATCH_PROFILE',
    GET_INVENTORY_RESPONSE: 'GET_INVENTORY_RESPONSE',
    UPDATE_INVENTORY_RESPONSE: 'UPDATE_INVENTORY_RESPONSE',
    FREE_PLAN_SUBSCRIBED: 'FREE_PLAN_SUBSCRIBED',
    HAS_UNSAVED_CHANGES: 'HAS_UNSAVED_CHANGES',
};

// VerifyMobileActions constants
export const VerifyMobileActions = {
    SET_VERIFIACATION_MOBILENO: 'SET_VERIFIACATION_MOBILENO',
    SHOW_VERIFICATION_BOX: 'SHOW_VERIFICATION_BOX',
    VERIFY_MOBILE_CODE_RESPONSE: 'VERIFY_MOBILE_CODE_RESPONSE',
    HIDE_VERIFICATION_BOX: 'HIDE_VERIFICATION_BOX',
};

// SETTINGS_TAXES_ACTIONS constants
export const SETTINGS_TAXES_ACTIONS = {
    CREATE_TAX: 'CREATE_TAX',
    CREATE_TAX_RESPONSE: 'CREATE_TAX_RESPONSE',
    UPDATE_TAX: 'UPDATE_TAX',
    UPDATE_TAX_RESPONSE: 'UPDATE_TAX_RESPONSE',
    DELETE_TAX_RESPONSE: 'DELETE_TAX_RESPONSE',
    GET_TAX_RESPONSE: 'GET_TAX_RESPONSE',
    RESET_TAX_RESPONSE: 'RESET_TAX_RESPONSE',
};

// GENERAL_ACTIONS constants
export const GENERAL_ACTIONS = {
    GENERAL_GET_GROUP_WITH_ACCOUNTS_RESPONSE: 'GENERAL_GET_GROUP_WITH_ACCOUNTS_RESPONSE',
    GENERAL_GET_ALL_STATES_RESPONSE: 'GENERAL_GET_ALL_STATES_RESPONSE',
    RESET_STATES_LIST: 'RESET_STATES_LIST',
    CLOSE_ADD_AND_MANAGE: 'CLOSE_ADD_AND_MANAGE',
    SET_SIDE_MENU_BAR_STATE: 'SET_SIDE_MENU_BAR_STATE',
    SET_APP_HEADER_TITLE: 'SET_APP_HEADER_TITLE',
    SET_PAGE_HEADER_TITLE: 'SET_PAGE_HEADER_TITLE',
    OPEN_SIDE_MENU: 'OPEN_SIDE_MENU',
    UPDATE_CURRENT_LIABILITIES: 'UPDATE_CURRENT_LIABILITIES',
    UPDATE_INDEX_DB: 'UPDATE_INDEX_DB',
    UPDATE_INDEX_DB_COMPLETE: 'UPDATE_INDEX_DB_COMPLETE',
    DELETE_ENTRY_FROM_INDEX_DB: 'DELETE_ENTRY_FROM_INDEX_DB',
    DELETE_ENTRY_FROM_INDEX_DB_COMPLETE: 'DELETE_ENTRY_FROM_INDEX_DB_COMPLETE',
    DELETE_ENTRY_FROM_INDEX_DB_ERROR: 'DELETE_ENTRY_FROM_INDEX_DB_ERROR',
    UPDATE_UI_FROM_DB: 'UPDATE_UI_FROM_DB',
    SAVE_SIDE_MENU_ITEMS: 'SAVE_SIDE_MENU_ITEMS',
    OPEN_GST_SIDE_MENU: 'OPEN_GST_SIDE_MENU',
    OPEN_CALENDLY_MODEL: 'OPEN_CALENDLY_MODEL',
};

// AccountsAction constants
export const AccountsAction = {
    CREATE_ACCOUNT_RESPONSEV2: 'CREATE_ACCOUNT_RESPONSEV2',
    UPDATE_ACCOUNT_RESPONSEV2: 'UPDATE_ACCOUNT_RESPONSEV2',
    DELETE_ACCOUNT_RESPONSE: 'DELETE_ACCOUNT_RESPONSE',
    MOVE_ACCOUNT_RESPONSE: 'MOVE_ACCOUNT_RESPONSE',
    MERGE_ACCOUNT_RESPONSE: 'MERGE_ACCOUNT_RESPONSE',
    RESET_ACTIVE_GROUP: 'RESET_ACTIVE_GROUP',
    SHARED_ACCOUNT_WITH_RESPONSE: 'SHARED_ACCOUNT_WITH_RESPONSE',
    UNSHARE_ACCOUNT_RESPONSE: 'UNSHARE_ACCOUNT_RESPONSE',
    GET_ACCOUNT_TAX_HIERARCHY: 'GET_ACCOUNT_TAX_HIERARCHY',
    GET_ACCOUNT_TAX_HIERARCHY_RESPONSE: 'GET_ACCOUNT_TAX_HIERARCHY_RESPONSE',
    GET_ACCOUNT_DETAILS_RESPONSE: 'GET_ACCOUNT_DETAILS_RESPONSE',
    UPDATE_ACCOUNTV2: 'UPDATE_ACCOUNTV2',
    UPDATE_ACCOUNTV2_PATCH: 'UPDATE_ACCOUNTV2_PATCH',
    RESET_UPDATE_ACCOUNTV2: 'RESET_UPDATE_ACCOUNTV2',
    RESET_ACTIVE_ACCOUNT: 'RESET_ACTIVE_ACCOUNT',
    DELETE_ACCOUNT: 'DELETE_ACCOUNT',
    RESET_DELETE_ACCOUNT_FLAGS: 'RESET_DELETE_ACCOUNT_FLAGS',
    MOVE_ACCOUNT_RESET: 'MOVE_ACCOUNT_RESET',
    MERGE_ACCOUNT: 'MERGE_ACCOUNT',
    UNMERGE_ACCOUNT: 'UNMERGE_ACCOUNT',
    UNMERGE_ACCOUNT_RESPONSE: 'UNMERGE_ACCOUNT_RESPONSE',
    CREATE_ACCOUNTV2: 'CREATE_ACCOUNTV2',
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    CREATE_ACCOUNT_RESPONSE: 'CREATE_ACCOUNT_RESPONSE',
    ACCOUNT_HAS_UNSAVED_CHANGES: 'ACCOUNT_HAS_UNSAVED_CHANGES',
    SHARE_ENTITY: 'SHARE_ENTITY',
    SHARE_ENTITY_RESPONSE: 'SHARE_ENTITY_RESPONSE',
    RESET_SHARE_ENTITY: 'RESET_SHARE_ENTITY',
};

// SALES_ACTIONS constants
export const SALES_ACTIONS = {
    ADD_ACCOUNT_DETAILS_RESPONSE: 'ADD_ACCOUNT_DETAILS_RESPONSE',
    UPDATE_ACCOUNT_DETAILS_RESPONSE: 'UPDATE_ACCOUNT_DETAILS_RESPONSE',
    GET_ACCOUNT_DETAILS_RESPONSE: 'GET_ACCOUNT_DETAILS_RESPONSE',
    ADD_ACCOUNT_DETAILS: 'ADD_ACCOUNT_DETAILS',
    UPDATE_ACCOUNT_DETAILS: 'UPDATE_ACCOUNT_DETAILS',
    RESET_ACCOUNT_DETAILS: 'RESET_ACCOUNT_DETAILS',
    STOCK_AC_SUCCESS: 'STOCK_AC_SUCCESS',
};

// SessionActions constants
export const SessionActions = {
    GET_ALL_SESSION_RESPONSE: 'GET_ALL_SESSION_RESPONSE',
    DELETE_SESSION_RESPONSE: 'DELETE_SESSION_RESPONSE',
    DELETE_ALL_SESSION_RESPONSE: 'DELETE_ALL_SESSION_RESPONSE',
};

// GroupWithAccountsAction constants
export const GroupWithAccountsAction = {
    SHOW_ADD_NEW_FORM: 'SHOW_ADD_NEW_FORM',
    HIDE_ADD_NEW_FORM: 'HIDE_ADD_NEW_FORM',
    SET_ACTIVE_GROUP: 'SET_ACTIVE_GROUP',
    GET_GROUP_WITH_ACCOUNTS: 'GET_GROUP_WITH_ACCOUNTS',
    SET_GROUP_ACCOUNTS_SEARCH_STRING: 'SET_GROUP_ACCOUNTS_SEARCH_STRING',
    OPEN_ADD_AND_MANAGE_FROM_OUTSIDE: 'OPEN_ADD_AND_MANAGE_FROM_OUTSIDE',
    HIDE_ADD_AND_MANAGE_FROM_OUTSIDE: 'HIDE_ADD_AND_MANAGE_FROM_OUTSIDE',
    GET_GROUP_WITH_ACCOUNTS_RESPONSE: 'GET_GROUP_WITH_ACCOUNTS_RESPONSE',
    GET_GROUP_DETAILS: 'GET_GROUP_DETAILS',
    GET_GROUP_DETAILS_RESPONSE: 'GET_GROUP_DETAILS_RESPONSE',
    CREATE_GROUP: 'CREATE_GROUP',
    CREATE_GROUP_RESPONSE: 'CREATE_GROUP_RESPONSE',
    SHARED_GROUP_WITH_RESPONSE: 'SHARED_GROUP_WITH_RESPONSE',
    UNSHARE_GROUP_RESPONSE: 'UNSHARE_GROUP_RESPONSE',
    RESET_GROUPS_STATE: 'RESET_GROUPS_STATE',
    GET_GROUP_TAX_HIERARCHY: 'GET_GROUP_TAX_HIERARCHY',
    GET_GROUP_TAX_HIERARCHY_RESPONSE: 'GET_GROUP_TAX_HIERARCHY_RESPONSE',
    SHOW_ADD_GROUP_FORM: 'SHOW_ADD_GROUP_FORM',
    SHOW_ADD_ACCOUNT_FORM: 'SHOW_ADD_ACCOUNT_FORM',
    HIDE_ADD_ACCOUNT_FORM: 'HIDE_ADD_ACCOUNT_FORM',
    SHOW_EDIT_ACCOUNT_FORM: 'SHOW_EDIT_ACCOUNT_FORM',
    HIDE_EDIT_ACCOUNT_FORM: 'HIDE_EDIT_ACCOUNT_FORM',
    UPDATE_GROUP: 'UPDATE_GROUP',
    UPDATE_GROUP_RESPONSE: 'UPDATE_GROUP_RESPONSE',
    DELETE_GROUP: 'DELETE_GROUP',
    DELETE_GROUP_RESPONSE: 'DELETE_GROUP_RESPONSE',
    MOVE_GROUP: 'MOVE_GROUP',
    MOVE_GROUP_RESPONSE: 'MOVE_GROUP_RESPONSE',
    GEN_ADD_AND_MANAGE_UI: 'GEN_ADD_AND_MANAGE_UI',
    MOVE_GROUP_COMPLETE: 'MOVE_GROUP_COMPLETE',
    UPDATE_ACTIVE_TAB_ADD_AND_MANAGE: 'UPDATE_ACTIVE_TAB_ADD_AND_MANAGE',
    GET_ACCOUNT_GROUP_DETAILS_RESPONSE: 'GET_ACCOUNT_GROUP_DETAILS_RESPONSE',
};

// GSTR_ACTIONS constants
export const GSTR_ACTIONS = {
    SET_ACTIVE_COMPANY_GSTIN: 'SET_ACTIVE_COMPANY_GSTIN',
    GET_GSTR1_OVERVIEW: 'GET_GSTR1_OVERVIEW',
    GET_GSTR1_OVERVIEW_RESPONSE: 'GET_GSTR1_OVERVIEW_RESPONSE',
    RESET_GSTR1_OVERVIEW_RESPONSE: 'RESET_GSTR1_OVERVIEW_RESPONSE',
    GET_GSTR3B_OVERVIEW: 'GET_GSTR3B_OVERVIEW',
    GET_GSTR3B_OVERVIEW_RESPONSE: 'GET_GSTR3B_OVERVIEW_RESPONSE',
    RESET_GSTR3B_OVERVIEW_RESPONSE: 'RESET_GSTR3B_OVERVIEW_RESPONSE',
    GET_GSTR2_OVERVIEW: 'GET_GSTR2_OVERVIEW',
    GET_GSTR2_OVERVIEW_RESPONSE: 'GET_GSTR2_OVERVIEW_RESPONSE',
    RESET_GSTR2_OVERVIEW_RESPONSE: 'RESET_GSTR2_OVERVIEW_RESPONSE',
    GET_SUMMARY_TRANSACTIONS: 'GET_SUMMARY_TRANSACTIONS',
    GET_SUMMARY_TRANSACTIONS_RESPONSE: 'GET_SUMMARY_TRANSACTIONS_RESPONSE',
    GET_GSTR1_SUMMARY_DETAILS: 'GET_GSTR1_SUMMARY_DETAILS',
    GET_GSTR1_SUMMARY_DETAILS_RESPONSE: 'GET_GSTR1_SUMMARY_DETAILS_RESPONSE',
    CURRENT_PERIOD: 'CURRENT_PERIOD',
    GST_SAVE_GSP_SESSION: 'GST_SAVE_GSP_SESSION',
    GST_SAVE_GSP_SESSION_RESPONSE: 'GST_SAVE_GSP_SESSION_RESPONSE',
    GST_SAVE_GSP_SESSION_WITH_OTP: 'GST_SAVE_GSP_SESSION_WITH_OTP',
    GST_SAVE_GSP_SESSION_WITH_OTP_RESPONSE: 'GST_SAVE_GSP_SESSION_WITH_OTP_RESPONSE',
    GST_GET_GSP_SESSION: 'GST_GET_GSP_SESSION',
    GST_GET_GSP_SESSION_RESPONSE: 'GST_GET_GSP_SESSION_RESPONSE',
    FILE_GSTR1: 'FILE_GSTR1',
    FILE_GSTR1_RESPONSE: 'FILE_GSTR1_RESPONSE',
    GST_RESET_ASIDE_FLAGS: 'GST_RESET_ASIDE_FLAGS',
};

// GST_RETURN_ACTIONS constants
export const GST_RETURN_ACTIONS = {
    FILE_JIO_GST: 'FILE_JIO_GST',
    FILE_JIO_GST_RESPONSE: 'FILE_JIO_GST_RESPONSE',
};

// GST_RECONCILE_ACTIONS constants
export const GST_RECONCILE_ACTIONS = {
    GST_RECONCILE_OTP_REQUEST: 'GST_RECONCILE_OTP_REQUEST',
    GST_RECONCILE_OTP_RESPONSE: 'GST_RECONCILE_OTP_RESPONSE',
    GST_RECONCILE_VERIFY_OTP_REQUEST: 'GST_RECONCILE_VERIFY_OTP_REQUEST',
    GST_RECONCILE_VERIFY_OTP_RESPONSE: 'GST_RECONCILE_VERIFY_OTP_RESPONSE',
    GST_RECONCILE_INVOICE_REQUEST: 'GST_RECONCILE_INVOICE_REQUEST',
    GST_RECONCILE_INVOICE_RESPONSE: 'GST_RECONCILE_INVOICE_RESPONSE',
};

// GstReconcileActionsEnum constants
export const GstReconcileActionsEnum = {
    notfoundongiddh: 'notfoundongiddh',
    notfoundonportal: 'notfoundonportal',
    matched: 'matched',
    partiallymatched: 'partiallymatched',
};

// HOME constants
export const HOME = {
    RESET_HOME_STATE: 'RESET_HOME_STATE',
    GET_RATIO_ANALYSIS_RESPONSE: 'GET_RATIO_ANALYSIS_RESPONSE',
    GET_REVENUE_GRAPH_TYPES_RESPONSE: 'GET_REVENUE_GRAPH_TYPES_RESPONSE',
};

// InventoryActionsConst constants
export const InventoryActionsConst = {
    SetActiveStock: 'SetActiveStock',
    GetGroupsWithStocksHierarchyMin: 'GetGroupsWithStocksHierarchyMin',
    GetGroupsWithStocksHierarchyMinResponse: 'GetGroupsWithStocksHierarchyMinResponse',
    GetInventoryGroupResponse: 'GetInventoryGroupResponse',
    InventoryGroupToggleOpen: 'InventoryGroupToggleOpen',
    AddNewGroup: 'AddNewGroup',
    AddNewGroupResponse: 'AddNewGroupResponse',
    GetGroupUniqueName: 'GetGroupUniqueName',
    GetGroupUniqueNameResponse: 'GetGroupUniqueNameResponse',
    UpdateGroup: 'UpdateGroup',
    UpdateGroupResponse: 'UpdateGroupResponse',
    RemoveGroup: 'RemoveGroup',
    RemoveGroupResponse: 'RemoveGroupResponse',
    ResetActiveGroup: 'ResetActiveGroup',
    GetStockUniqueName: 'GetStockUniqueName',
    GetStockUniqueNameResponse: 'GetStockUniqueNameResponse',
    GetStockResponse: 'GetStockResponse',
    GetManufacturingStockResponse: 'GetManufacturingStockResponse',
    GetManufacturingStockForCreateResponse: 'GetManufacturingStockForCreateResponse',
    GetManufacturingStockForCreate: 'GetManufacturingStockForCreate',
    CreateStock: 'CreateStock',
    CreateStockResponse: 'CreateStockResponse',
    ResetCreateStockFlags: 'ResetCreateStockFlags',
    UpdateStock: 'UpdateStock',
    UpdateStockResponse: 'UpdateStockResponse',
    RemoveStock: 'RemoveStock',
    RemoveStockResponse: 'RemoveStockResponse',
    GetInventoryStockResponse: 'GetInventoryStockResponse',
    SearchGroupsWithStocks: 'SearchGroupsWithStocks',
    SearchGroupsWithStocksResponse: 'SearchGroupsWithStocksResponse',
    GetStockWithUniqueNameResponse: 'GetStockWithUniqueNameResponse',
    ShowLoadingForStockEditInProcess: 'ShowLoadingForStockEditInProcess',
    HideLoadingForStockEditInProcess: 'HideLoadingForStockEditInProcess',
    ResetActiveStock: 'ResetActiveStock',
    ResetInventoryState: 'ResetInventoryState',
    MoveStock: 'MoveStock',
    MoveStockResponse: 'MoveStockResponse',
    NewGroupAsidePane: 'NewGroupAsidePane',
    NewCustomUnitAsidePane: 'NewCustomUnitAsidePane',
    ManageInventoryAside: 'ManageInventoryAside',
    ShowBranchScreen: 'ShowBranchScreen',
    ShowBranchScreenSideBar: 'ShowBranchScreenSideBar',
    BulkStockResponse: 'BulkStockResponse',
};

// CUSTOM_STOCK_UNIT_ACTIONS constants
export const CUSTOM_STOCK_UNIT_ACTIONS = {
    GET_STOCK_MAPPED_UNITS_RESPONSE: 'GET_STOCK_MAPPED_UNITS_RESPONSE',
    GET_STOCK_MAPPED_UNIT_UNIQUE_NAME_RESPONSE: 'GET_STOCK_MAPPED_UNIT_UNIQUE_NAME_RESPONSE',
    GET_STOCK_UNIT_RESPONSE: 'GET_STOCK_UNIT_RESPONSE',
    CREATE_STOCK_UNIT: 'CREATE_STOCK_UNIT',
    RESET_STOCK_UNIT_RESPONSE: 'RESET_STOCK_UNIT_RESPONSE',
    CREATE_STOCK_UNIT_RESPONSE: 'CREATE_STOCK_UNIT_RESPONSE',
    UPDATE_STOCK_UNIT: 'UPDATE_STOCK_UNIT',
    UPDATE_STOCK_UNIT_RESPONSE: 'UPDATE_STOCK_UNIT_RESPONSE',
    DELETE_STOCK_UNIT: 'DELETE_STOCK_UNIT',
    DELETE_STOCK_UNIT_RESPONSE: 'DELETE_STOCK_UNIT_RESPONSE',
    GET_STOCK_UNIT_NAME: 'GET_STOCK_UNIT_NAME',
    GET_STOCK_UNIT_NAME_RESPONSE: 'GET_STOCK_UNIT_NAME_RESPONSE',
};

// STOCKS_REPORT_ACTIONS constants
export const STOCKS_REPORT_ACTIONS = {
    GET_STOCKS_REPORT_RESPONSE: 'GET_STOCKS_REPORT_RESPONSE',
    GET_GROUP_STOCKS_REPORT: 'GET_GROUP_STOCKS_REPORT',
    GET_STOCKS_REPORT: 'GET_STOCKS_REPORT',
    GET_GROUP_STOCKS_REPORT_RESPONSE: 'GET_GROUP_STOCKS_REPORT_RESPONSE',
};

// INVENTORY_BRANCH_TRANSFER constants
export const INVENTORY_BRANCH_TRANSFER = {
    CREATE_TRANSFER: 'CREATE_TRANSFER',
    CREATE_TRANSFER_RESPONSE: 'CREATE_TRANSFER_RESPONSE',
    RESET_BRANCH_TRANSFER_STATE: 'RESET_BRANCH_TRANSFER_STATE',
};

// INVENTORY_LINKED_STOCKS constants
export const INVENTORY_LINKED_STOCKS = {
    GET_LINKED_STOCKS: 'GET_LINKED_STOCKS',
    GET_LINKED_STOCKS_RESPONSE: 'GET_LINKED_STOCKS_RESPONSE',
};

// INVENTORY_USER_ACTIONS constants
export const INVENTORY_USER_ACTIONS = {
    GET_ALL_USERS_RESPONSE: 'GET_ALL_USERS_RESPONSE',
    CREATE_USER: 'CREATE_USER',
    CREATE_USER_RESPONSE: 'CREATE_USER_RESPONSE',
};

// INVENTORY_REPORT_ACTIONS constants
export const INVENTORY_REPORT_ACTIONS = {
    GENERATE_REPORT_RESPONSE: 'GENERATE_REPORT_RESPONSE',
};

// INVENTORY_ENTRY_ACTIONS constants
export const INVENTORY_ENTRY_ACTIONS = {
    CREATE_ENTRY: 'CREATE_ENTRY',
    CREATE_ENTRY_RESPONSE: 'CREATE_ENTRY_RESPONSE',
    CREATE_TRANSFER_ENTRY: 'CREATE_TRANSFER_ENTRY',
    CREATE_TRANSFER_ENTRY_RESPONSE: 'CREATE_TRANSFER_ENTRY_RESPONSE',
};

// INVOICE_RECEIPT_ACTIONS constants
export const INVOICE_RECEIPT_ACTIONS = {
    GET_ALL_INVOICE_RECEIPT: 'GET_ALL_INVOICE_RECEIPT',
    GET_ALL_INVOICE_RECEIPT_RESPONSE: 'GET_ALL_INVOICE_RECEIPT_RESPONSE',
    DELETE_INVOICE_RECEIPT: 'DELETE_INVOICE_RECEIPT',
    DELETE_INVOICE_RECEIPT_RESPONSE: 'DELETE_INVOICE_RECEIPT_RESPONSE',
    UPDATE_INVOICE_RECEIPT_RESPONSE: 'UPDATE_INVOICE_RECEIPT_RESPONSE',
    UPDATE_VOUCHER_DETAILS_AFTER_VOUCHER_UPDATE: 'UPDATE_VOUCHER_DETAILS_AFTER_VOUCHER_UPDATE',
    GET_VOUCHER_DETAILS: 'GET_VOUCHER_DETAILS',
    GET_VOUCHER_DETAILS_RESPONSE: 'GET_VOUCHER_DETAILS_RESPONSE',
    GET_VOUCHER_DETAILS_RESPONSEV4: 'GET_VOUCHER_DETAILS_RESPONSEV4',
    RESET_VOUCHER_DETAILS: 'RESET_VOUCHER_DETAILS',
    DOWNLOAD_VOUCHER_REQUEST: 'DOWNLOAD_VOUCHER_REQUEST',
    DOWNLOAD_VOUCHER_RESPONSE: 'DOWNLOAD_VOUCHER_RESPONSE',
    INVOICE_SET_VOUCHER_FOR_DETAILS: 'INVOICE_SET_VOUCHER_FOR_DETAILS',
    INVOICE_RESET_VOUCHER_FOR_DETAILS: 'INVOICE_RESET_VOUCHER_FOR_DETAILS',
    GET_SALESRAGISTED_DETAILS: 'GET_SALESRAGISTED_DETAILS',
    GET_SALESRAGISTED_DETAILS_RESPONSE: 'GET_SALESRAGISTED_DETAILS_RESPONSE',
    GET_PURCHASE_REGISTERED_DETAILS: 'GET_PURCHASE_REGISTERED_DETAILS',
    GET_PURCHASE_REGISTERED_DETAILS_RESPONSE: 'GET_PURCHASE_REGISTERED_DETAILS_RESPONSE',
};

// INVOICE_ACTIONS constants
export const INVOICE_ACTIONS = {
    ACTION_ON_INVOICE: 'ACTION_ON_INVOICE',
    ACTION_ON_INVOICE_RESPONSE: 'ACTION_ON_INVOICE_RESPONSE',
    DELETE_INVOICE_RESPONSE: 'DELETE_INVOICE_RESPONSE',
    PREVIEW_INVOICE: 'PREVIEW_INVOICE',
    PREVIEW_INVOICE_RESPONSE: 'PREVIEW_INVOICE_RESPONSE',
    PREVIEW_OF_GENERATED_INVOICE_RESPONSE: 'PREVIEW_OF_GENERATED_INVOICE_RESPONSE',
    RESET_INVOICE_DATA: 'RESET_INVOICE_DATA',
    GENERATE_INVOICE_RESPONSE: 'GENERATE_INVOICE_RESPONSE',
    DOWNLOAD_INVOICE_RESPONSE: 'DOWNLOAD_INVOICE_RESPONSE',
    GET_ALL_LEDGERS_FOR_INVOICE: 'GET_ALL_LEDGERS_FOR_INVOICE',
    GET_ALL_LEDGERS_FOR_INVOICE_RESPONSE: 'GET_ALL_LEDGERS_FOR_INVOICE_RESPONSE',
    MODIFIED_INVOICE_STATE_DATA: 'MODIFIED_INVOICE_STATE_DATA',
    PREVIEW_OF_GENERATED_INVOICE: 'PREVIEW_OF_GENERATED_INVOICE',
    UPDATE_GENERATED_INVOICE_RESPONSE: 'UPDATE_GENERATED_INVOICE_RESPONSE',
    INVOICE_GENERATION_COMPLETED: 'INVOICE_GENERATION_COMPLETED',
    GENERATE_BULK_INVOICE_RESPONSE: 'GENERATE_BULK_INVOICE_RESPONSE',
    GET_INVOICE_TEMPLATE_DETAILS_RESPONSE: 'GET_INVOICE_TEMPLATE_DETAILS_RESPONSE',
    RESET_ACTION_ON_INVOICE: 'RESET_ACTION_ON_INVOICE',
    DOWNLOAD_INVOICE_EXPORTED: 'DOWNLOAD_INVOICE_EXPORTED',
    DOWNLOAD_INVOICE_EXPORTED_RESPONSE: 'DOWNLOAD_INVOICE_EXPORTED_RESPONSE',
    RESET_PENDING_DATA: 'RESET_PENDING_DATA',
    GENERATE_BULK_E_INVOICE: 'GENERATE_BULK_E_INVOICE',
    GENERATE_BULK_E_INVOICE_RESPONSE: 'GENERATE_BULK_E_INVOICE_RESPONSE',
    RESET_BULK_E_INVOICE_RESPONSE: 'RESET_BULK_E_INVOICE_RESPONSE',
    SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION: 'SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION',
};

// EWAYBILL_ACTIONS constants
export const EWAYBILL_ACTIONS = {
    GET_All_LIST_EWAYBILLS: 'GET_All_LIST_EWAYBILLS',
    GET_All_FILTERED_LIST_EWAYBILLS: 'GET_All_FILTERED_LIST_EWAYBILLS',
    GET_All_LIST_EWAYBILLS_RESPONSE: 'GET_All_LIST_EWAYBILLS_RESPONSE',
    GET_All_FILTERED_LIST_EWAYBILLS_RESPONSE: 'GET_All_FILTERED_LIST_EWAYBILLS_RESPONSE',
    LOGIN_EAYBILL_USER: 'LOGIN_EAYBILL_USER',
    LOGIN_EAYBILL_USER_RESPONSE: 'LOGIN_EAYBILL_USER_RESPONSE',
    GENERATE_EWAYBILL: 'GENERATE_EWAYBILL',
    GENERATE_EWAYBILL_RESPONSE: 'GENERATE_EWAYBILL_RESPONSE',
    IS_LOOGEDIN_USER_EWAYBILL_RESPONSE: 'IS_LOOGEDIN_USER_EWAYBILL_RESPONSE',
    ADD_TRANSPORTER: 'ADD_TRANSPORTER',
    ADD_TRANSPORTER_RESPONSE: 'ADD_TRANSPORTER_RESPONSE',
    UPDATE_TRANSPORTER: 'UPDATE_TRANSPORTER',
    UPDATE_TRANSPORTER_RESPONSE: 'UPDATE_TRANSPORTER_RESPONSE',
    GET_ALL_TRANSPORTER_RESPONSE: 'GET_ALL_TRANSPORTER_RESPONSE',
    DELETE_TRANSPORTER_RESPONSE: 'DELETE_TRANSPORTER_RESPONSE',
    UPDATE_EWAY_VEHICLE: 'UPDATE_EWAY_VEHICLE',
    UPDATE_EWAY_VEHICLE_RESPONSE: 'UPDATE_EWAY_VEHICLE_RESPONSE',
    CANCEL_EWAYBILL: 'CANCEL_EWAYBILL',
    CANCEL_EWAYBILL_RESPONSE: 'CANCEL_EWAYBILL_RESPONSE',
    RESET_ALL_TRANSPORTER_RESPONSE: 'RESET_ALL_TRANSPORTER_RESPONSE',
};

// LEDGER constants
export const LEDGER = {
    GENERATE_BULK_LEDGER_INVOICE_RESPONSE: 'GENERATE_BULK_LEDGER_INVOICE_RESPONSE',
    GET_LEDGER_ACCOUNT: 'GET_LEDGER_ACCOUNT',
    GET_LEDGER_ACCOUNT_RESPONSE: 'GET_LEDGER_ACCOUNT_RESPONSE',
    GET_TRANSACTION: 'GET_TRANSACTION',
    GET_TRANSACTION_RESPONSE: 'GET_TRANSACTION_RESPONSE',
    ADVANCE_SEARCH: 'ADVANCE_SEARCH',
    ADVANCE_SEARCH_RESPONSE: 'ADVANCE_SEARCH_RESPONSE',
    DOWNLOAD_LEDGER_INVOICE: 'DOWNLOAD_LEDGER_INVOICE',
    DOWNLOAD_LEDGER_INVOICE_RESPONSE: 'DOWNLOAD_LEDGER_INVOICE_RESPONSE',
    CREATE_BLANK_LEDGER_REQUEST: 'CREATE_BLANK_LEDGER_REQUEST',
    CREATE_BLANK_LEDGER_RESPONSE: 'CREATE_BLANK_LEDGER_RESPONSE',
    CREATE_BULK_BLANK_LEDGER_RESPONSE: 'CREATE_BULK_BLANK_LEDGER_RESPONSE',
    RESET_BLANK_LEDGER_REQUEST: 'RESET_BLANK_LEDGER_REQUEST',
    SET_SELECTED_TXN_FOR_EDIT: 'SET_SELECTED_TXN_FOR_EDIT',
    SET_SELECTED_ACCOUNT_FOR_EDIT: 'SET_SELECTED_ACCOUNT_FOR_EDIT',
    DELETE_TRX_ENTRY: 'DELETE_TRX_ENTRY',
    DELETE_TRX_ENTRY_RESPONSE: 'DELETE_TRX_ENTRY_RESPONSE',
    RESET_DELETE_TRX_ENTRY_MODAL: 'RESET_DELETE_TRX_ENTRY_MODAL',
    LEDGER_SHARED_ACCOUNT_WITH_RESPONSE: 'LEDGER_SHARED_ACCOUNT_WITH_RESPONSE',
    UPDATE_TXN_ENTRY: 'UPDATE_TXN_ENTRY',
    RESET_UPDATE_TXN_ENTRY: 'RESET_UPDATE_TXN_ENTRY',
    UPDATE_TXN_ENTRY_RESPONSE: 'UPDATE_TXN_ENTRY_RESPONSE',
    CREATE_QUICK_ACCOUNT: 'CREATE_QUICK_ACCOUNT',
    CREATE_QUICK_ACCOUNT_RESPONSE: 'CREATE_QUICK_ACCOUNT_RESPONSE',
    GET_LEDGER_TRX_DETAILS_RESPONSE: 'GET_LEDGER_TRX_DETAILS_RESPONSE',
    RESET_LEGER_TRX_DETAILS: 'RESET_LEGER_TRX_DETAILS',
    RESET_QUICK_ACCOUNT_MODAL: 'RESET_QUICK_ACCOUNT_MODAL',
    RESET_LEDGER: 'RESET_LEDGER',
    GET_RECONCILIATION_RESPONSE: 'GET_RECONCILIATION_RESPONSE',
    DELETE_MULTIPLE_LEDGER_ENTRIES: 'DELETE_MULTIPLE_LEDGER_ENTRIES',
    DELETE_MULTIPLE_LEDGER_ENTRIES_RESPONSE: 'DELETE_MULTIPLE_LEDGER_ENTRIES_RESPONSE',
    GENERATE_BULK_LEDGER_INVOICE: 'GENERATE_BULK_LEDGER_INVOICE',
    SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION: 'SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION',
    GET_CURRENCY_RATE_RESPONSE: 'GET_CURRENCY_RATE_RESPONSE',
    SELECT_DESELECT_ALL_ENTRIES: 'SELECT_DESELECT_ALL_ENTRIES',
    SELECT_GIVEN_ENTRIES: 'SELECT_GIVEN_ENTRIES',
    DESELECT_GIVEN_ENTRIES: 'DESELECT_GIVEN_ENTRIES',
    SET_FAILED_BULK_ENTRIES: 'SET_FAILED_BULK_ENTRIES',
    GET_LEDGER_BALANCE: 'GET_LEDGER_BALANCE',
    GET_LEDGER_BALANCE_RESPONSE: 'GET_LEDGER_BALANCE_RESPONSE',
    REFRESH_LEDGER: 'REFRESH_LEDGER',
    SHOW_DUPLICATE_VOUCHER_CONFIRMATION: 'SHOW_DUPLICATE_VOUCHER_CONFIRMATION',
};

// PURCHASE_INVOICE_ACTIONS constants
export const PURCHASE_INVOICE_ACTIONS = {
    SET_TAXES_FOR_COMPANY: 'SET_TAXES_FOR_COMPANY',
};

// ItemOnBoardingActions constants
export const ItemOnBoardingActions = {
    SET_ON_BOARDING_STATUS: 'SET_ON_BOARDING_STATUS',
    SET_ON_BOARDING_TYPE: 'SET_ON_BOARDING_TYPE',
    SET_ITEM_UPDATE_PROGRESS: 'SET_ITEM_UPDATE_PROGRESS',
    RESET_ON_BOARDING: 'RESET_ON_BOARDING',
};

// MANUFACTURING_ACTIONS constants
export const MANUFACTURING_ACTIONS = {
    MF_REPORT: 'MF_REPORT',
    MF_REPORT_RESPONSE: 'MF_REPORT_RESPONSE',
    GET_STOCK_WITH_RATE: 'GET_STOCK_WITH_RATE',
    GET_STOCK_WITH_RATE_RESPONSE: 'GET_STOCK_WITH_RATE_RESPONSE',
    CREATE_MF_ITEM: 'CREATE_MF_ITEM',
    CREATE_MF_ITEM_RESPONSE: 'CREATE_MF_ITEM_RESPONSE',
    UPDATE_MF_ITEM: 'UPDATE_MF_ITEM',
    UPDATE_MF_ITEM_RESPONSE: 'UPDATE_MF_ITEM_RESPONSE',
    DELETE_MF_ITEM: 'DELETE_MF_ITEM',
    DELETE_MF_ITEM_RESPONSE: 'DELETE_MF_ITEM_RESPONSE',
    SET_MF_ITEM_UNIQUENAME_IN_STORE: 'SET_MF_ITEM_UNIQUENAME_IN_STORE',
    REMOVE_MF_ITEM_UNIQUENAME_FROM_STORE: 'REMOVE_MF_ITEM_UNIQUENAME_FROM_STORE',
};

// PERMISSION_ACTIONS constants
export const PERMISSION_ACTIONS = {
    GET_ROLES: 'GET_ROLES',
    GET_ROLES_RESPONSE: 'GET_ROLES_RESPONSE',
    CREATE_ROLE: 'CREATE_ROLE',
    CREATE_ROLE_RESPONSE: 'CREATE_ROLE_RESPONSE',
    UPDATE_ROLE: 'UPDATE_ROLE',
    UPDATE_ROLE_RESPONSE: 'UPDATE_ROLE_RESPONSE',
    DELETE_ROLE: 'DELETE_ROLE',
    DELETE_ROLE_RESPONSE: 'DELETE_ROLE_RESPONSE',
    GET_ALL_PAGES: 'GET_ALL_PAGES',
    GET_ALL_PAGES_RESPONSE: 'GET_ALL_PAGES_RESPONSE',
    GET_ALL_PERMISSIONS_RESPONSE: 'GET_ALL_PERMISSIONS_RESPONSE',
    PUSH_TEMP_ROLE_IN_STORE: 'PUSH_TEMP_ROLE_IN_STORE',
    REMOVE_NEWLY_CREATED_ROLE_FROM_STORE: 'REMOVE_NEWLY_CREATED_ROLE_FROM_STORE',
};

// PROFORMA_ACTIONS constants
export const PROFORMA_ACTIONS = {
    GENERATE_PROFORMA_REQUEST: 'GENERATE_PROFORMA_REQUEST',
    GENERATE_PROFORMA_RESPONSE: 'GENERATE_PROFORMA_RESPONSE',
    GET_ALL_PROFORMA_REQUEST: 'GET_ALL_PROFORMA_REQUEST',
    GET_ALL_PROFORMA_RESPONSE: 'GET_ALL_PROFORMA_RESPONSE',
    GET_PROFORMA_DETAILS_REQUEST: 'GET_PROFORMA_DETAILS_REQUEST',
    GET_PROFORMA_DETAILS_RESPONSE: 'GET_PROFORMA_DETAILS_RESPONSE',
    UPDATE_PROFORMA_REQUEST: 'UPDATE_PROFORMA_REQUEST',
    UPDATE_PROFORMA_RESPONSE: 'UPDATE_PROFORMA_RESPONSE',
    DELETE_PROFORMA_REQUEST: 'DELETE_PROFORMA_REQUEST',
    DELETE_PROFORMA_RESPONSE: 'DELETE_PROFORMA_RESPONSE',
    UPDATE_PROFORMA_ACTION: 'UPDATE_PROFORMA_ACTION',
    UPDATE_PROFORMA_ACTION_RESPONSE: 'UPDATE_PROFORMA_ACTION_RESPONSE',
    GET_ESTIMATE_VERSIONS: 'GET_ESTIMATE_VERSIONS',
    GET_ESTIMATE_VERSIONS_RESPONSE: 'GET_ESTIMATE_VERSIONS_RESPONSE',
    GENERATE_PROFORMA_FROM_ESTIMATE: 'GENERATE_PROFORMA_FROM_ESTIMATE',
    GENERATE_PROFORMA_FROM_ESTIMATE_RESPONSE: 'GENERATE_PROFORMA_FROM_ESTIMATE_RESPONSE',
    GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES: 'GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES',
    GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES_RESPONSE: 'GENERATE_INVOICE_FROM_PROFORMA_OR_ESTIMATES_RESPONSE',
    RESET_ACTIVE_VOUCHER: 'RESET_ACTIVE_VOUCHER',
    SET_VOUCHER_FOR_DETAILS: 'SET_VOUCHER_FOR_DETAILS',
    RESET_VOUCHER_FOR_DETAILS: 'RESET_VOUCHER_FOR_DETAILS',
};

// PURCHASE_ORDER_ACTIONS constants
export const PURCHASE_ORDER_ACTIONS = {
    SET_FILTERS: 'SET_FILTERS',
    PO_PREVIEW_SEARCH: 'PO_PREVIEW_SEARCH',
};

// PURCHASE_RECORD_ACTIONS constants
export const PURCHASE_RECORD_ACTIONS = {
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    RESET_UPDATE_DETAILS: 'RESET_UPDATE_DETAILS',
};

// SearchActions constants
export const SearchActions = {
    SEARCH_RESPONSE: 'SEARCH_RESPONSE',
    SEARCH_REQUEST: 'SEARCH_REQUEST',
    RESET_SEARCH_STATE: 'RESET_SEARCH_STATE',
};

// SETTINGS_FINANCIAL_YEAR_ACTIONS constants
export const SETTINGS_FINANCIAL_YEAR_ACTIONS = {
    UPDATE_FINANCIAL_YEAR_PERIOD: 'UPDATE_FINANCIAL_YEAR_PERIOD',
    UPDATE_FINANCIAL_YEAR_PERIOD_RESPONSE: 'UPDATE_FINANCIAL_YEAR_PERIOD_RESPONSE',
    GET_ALL_FINANCIAL_YEARS_RESPONSE: 'GET_ALL_FINANCIAL_YEARS_RESPONSE',
    LOCK_FINANCIAL_YEAR_RESPONSE: 'LOCK_FINANCIAL_YEAR_RESPONSE',
    UNLOCK_FINANCIAL_YEAR_RESPONSE: 'UNLOCK_FINANCIAL_YEAR_RESPONSE',
    ADD_FINANCIAL_YEAR_RESPONSE: 'ADD_FINANCIAL_YEAR_RESPONSE',
    ADD_FINANCIAL_YEAR: 'ADD_FINANCIAL_YEAR',
    ADD_FUTURE_FINANCIAL_YEAR: 'ADD_FUTURE_FINANCIAL_YEAR',
    GET_FINANCIAL_YEAR_LIMITS_RESPONSE: 'GET_FINANCIAL_YEAR_LIMITS_RESPONSE',
};

// SETTINGS_INTEGRATION_ACTIONS constants
export const SETTINGS_INTEGRATION_ACTIONS = {
    GET_SMS_KEY_RESPONSE: 'GET_SMS_KEY_RESPONSE',
    CREATE_SMS_KEY_RESPONSE: 'CREATE_SMS_KEY_RESPONSE',
    GET_EMAIL_KEY_RESPONSE: 'GET_EMAIL_KEY_RESPONSE',
    CREATE_EMAIL_KEY_RESPONSE: 'CREATE_EMAIL_KEY_RESPONSE',
    CREATE_PAYMENT_KEY_RESPONSE: 'CREATE_PAYMENT_KEY_RESPONSE',
    UPDATE_PAYMENT_KEY_RESPONSE: 'UPDATE_PAYMENT_KEY_RESPONSE',
    GET_PAYPAL_DETAILS_RESPONSE: 'GET_PAYPAL_DETAILS_RESPONSE',
    SAVE_PAYPAL_DETAILS_RESPONSE: 'SAVE_PAYPAL_DETAILS_RESPONSE',
    UPDATE_PAYPAL_DETAILS_RESPONSE: 'UPDATE_PAYPAL_DETAILS_RESPONSE',
    DELETE_PAYPAL_DETAILS_RESPONSE: 'DELETE_PAYPAL_DETAILS_RESPONSE',
    GET_RAZOR_PAY_DETAILS_RESPONSE: 'GET_RAZOR_PAY_DETAILS_RESPONSE',
    SAVE_RAZOR_PAY_DETAILS_RESPONSE: 'SAVE_RAZOR_PAY_DETAILS_RESPONSE',
    UPDATE_RAZOR_PAY_DETAILS_RESPONSE: 'UPDATE_RAZOR_PAY_DETAILS_RESPONSE',
    DELETE_RAZOR_PAY_DETAILS_RESPONSE: 'DELETE_RAZOR_PAY_DETAILS_RESPONSE',
    GET_CASHFREE_DETAILS_RESPONSE: 'GET_CASHFREE_DETAILS_RESPONSE',
    SAVE_CASHFREE_DETAILS_RESPONSE: 'SAVE_CASHFREE_DETAILS_RESPONSE',
    UPDATE_CASHFREE_DETAILS_RESPONSE: 'UPDATE_CASHFREE_DETAILS_RESPONSE',
    DELETE_CASHFREE_DETAILS_RESPONSE: 'DELETE_CASHFREE_DETAILS_RESPONSE',
    GET_AUTOCOLLECT_USER_RESPONSE: 'GET_AUTOCOLLECT_USER_RESPONSE',
    ADD_AUTOCOLLECT_USER_RESPONSE: 'ADD_AUTOCOLLECT_USER_RESPONSE',
    DELETE_AUTOCOLLECT_USER_RESPONSE: 'DELETE_AUTOCOLLECT_USER_RESPONSE',
    GET_PAYMENT_GATEWAY_RESPONSE: 'GET_PAYMENT_GATEWAY_RESPONSE',
    UPDATE_PAYMENT_GATEWAY_RESPONSE: 'UPDATE_PAYMENT_GATEWAY_RESPONSE',
    DELETE_PAYMENT_GATEWAY_RESPONSE: 'DELETE_PAYMENT_GATEWAY_RESPONSE',
    GET_AMAZON_SELLER_RESPONSE: 'GET_AMAZON_SELLER_RESPONSE',
    ADD_AMAZON_SELLER: 'ADD_AMAZON_SELLER',
    ADD_AMAZON_SELLER_RESPONSE: 'ADD_AMAZON_SELLER_RESPONSE',
    UPDATE_AMAZON_SELLER: 'UPDATE_AMAZON_SELLER',
    UPDATE_AMAZON_SELLER_RESPONSE: 'UPDATE_AMAZON_SELLER_RESPONSE',
    DELETE_AMAZON_SELLER_RESPONSE: 'DELETE_AMAZON_SELLER_RESPONSE',
    GET_GMAIL_INTEGRATION_STATUS_RESPONSE: 'GET_GMAIL_INTEGRATION_STATUS_RESPONSE',
    REMOVE_GMAIL_INTEGRATION_RESPONSE: 'REMOVE_GMAIL_INTEGRATION_RESPONSE',
    RESET_PAYMENT_STATUS_RESPONSE: 'RESET_PAYMENT_STATUS_RESPONSE',
};

// SETTINGS_LINKED_ACCOUNTS_ACTIONS constants
export const SETTINGS_LINKED_ACCOUNTS_ACTIONS = {
    GET_ALL_ACCOUNTS: 'GET_ALL_ACCOUNTS',
    GET_ALL_ACCOUNTS_RESPONSE: 'GET_ALL_ACCOUNTS_RESPONSE',
    REFRESH_ALL_ACCOUNTS_RESPONSE: 'REFRESH_ALL_ACCOUNTS_RESPONSE',
    REFRESH_BANK_ACCOUNT_RESPONSE: 'REFRESH_BANK_ACCOUNT_RESPONSE',
    DELETE_BANK_ACCOUNT: 'DELETE_BANK_ACCOUNT',
    DELETE_BANK_ACCOUNT_RESPONSE: 'DELETE_BANK_ACCOUNT_RESPONSE',
    RECONNECT_ACCOUNT_RESPONSE: 'RECONNECT_ACCOUNT_RESPONSE',
    LINK_BANK_ACCOUNT_RESPONSE: 'LINK_BANK_ACCOUNT_RESPONSE',
    UNLINK_BANK_ACCOUNT_RESPONSE: 'UNLINK_BANK_ACCOUNT_RESPONSE',
};

// SETTINGS_PERMISSION_ACTIONS constants
export const SETTINGS_PERMISSION_ACTIONS = {
    GET_USERS_WITH_COMPANY_PERMISSIONS_RESPONSE: 'GET_USERS_WITH_COMPANY_PERMISSIONS_RESPONSE',
};

// SETTINGS_BRANCH_ACTIONS constants
export const SETTINGS_BRANCH_ACTIONS = {
    GET_ALL_BRANCHES_RESPONSE: 'GET_ALL_BRANCHES_RESPONSE',
    REMOVED_BRANCH_RESPONSE: 'REMOVED_BRANCH_RESPONSE',
    RESET_REMOVED_BRANCH_RESPONSE: 'RESET_REMOVED_BRANCH_RESPONSE',
    RESET_ALL_BRANCHES_RESPONSE: 'RESET_ALL_BRANCHES_RESPONSE',
};

// TBPlBsActions constants
export const TBPlBsActions = {
    GET_TRIAL_BALANCE_RESPONSE: 'GET_TRIAL_BALANCE_RESPONSE',
    GET_V2_TRIAL_BALANCE_RESPONSE: 'GET_V2_TRIAL_BALANCE_RESPONSE',
    GET_TRIAL_BALANCE_REQUEST: 'GET_TRIAL_BALANCE_REQUEST',
    GET_V2_TRIAL_BALANCE_REQUEST: 'GET_V2_TRIAL_BALANCE_REQUEST',
    GET_PROFIT_LOSS_RESPONSE: 'GET_PROFIT_LOSS_RESPONSE',
    GET_PROFIT_LOSS_REQUEST: 'GET_PROFIT_LOSS_REQUEST',
    GET_COGS_RESPONSE: 'GET_COGS_RESPONSE',
    GET_BALANCE_SHEET_RESPONSE: 'GET_BALANCE_SHEET_RESPONSE',
    GET_BALANCE_SHEET_REQUEST: 'GET_BALANCE_SHEET_REQUEST',
};

// SubscriptionsActions constants
export const SubscriptionsActions = {
    SubscribedCompaniesResponse: 'SubscribedCompaniesResponse',
    SubscribedUserTransactionsResponse: 'SubscribedUserTransactionsResponse',
    SubscribedCompanyTransactionsResponse: 'SubscribedCompanyTransactionsResponse',
    SubscribedCompaniesListResponse: 'SubscribedCompaniesListResponse',
};

// AgingReportActions class
export class AgingReportActions {
    static CREATE_DUE_DAY_RANGE = 'CREATE_DUE_DAY_RANGE';
    static DUE_DAY_RANGE_POPUP_OPEN = 'DUE_DAY_RANGE_POPUP_OPEN';
    static DUE_DAY_RANGE_POPUP_CLOSE = 'DUE_DAY_RANGE_POPUP_CLOSE';
    static CREATE_DUE_DAY_RANGE_RESPONSE = 'CREATE_DUE_DAY_RANGE_RESPONSE';
    static GET_DUE_DAY_RANGE_RESPONSE = 'GET_DUE_DAY_RANGE_RESPONSE';
    static GET_DUE_DAY_REPORT_RESPONSE = 'GET_DUE_DAY_REPORT_RESPONSE';
    static GET_DUE_DAY_REPORT = 'GET_DUE_DAY_REPORT';
    [key: string]: any;
}

// LoginActions class
export class LoginActions {
    static RESET_NEEDS_TO_REDIRECT_TO_LEDGER = 'RESET_NEEDS_TO_REDIRECT_TO_LEDGER';
    static NEEDS_TO_REDIRECT_TO_LEDGER = 'NEEDS_TO_REDIRECT_TO_LEDGER';
    static SignupWithEmailResponce = 'SignupWithEmailResponce';
    static SIGNUP_WITH_GOOGLE_REQUEST = 'SIGNUP_WITH_GOOGLE_REQUEST';
    static SIGNUP_WITH_GOOGLE_RESPONSE = 'SIGNUP_WITH_GOOGLE_RESPONSE';
    static SignupWithEmailRequest = 'SignupWithEmailRequest';
    static ResetSignupWithEmailState = 'ResetSignupWithEmailState';
    static VerifyEmailRequest = 'VerifyEmailRequest';
    static VerifyEmailResponce = 'VerifyEmailResponce';
    static SignupWithMobileResponce = 'SignupWithMobileResponce';
    static SignupWithMobileRequest = 'SignupWithMobileRequest';
    static ResetSignupWithMobileState = 'ResetSignupWithMobileState';
    static VerifyMobileRequest = 'VerifyMobileRequest';
    static VerifyMobileResponce = 'VerifyMobileResponce';
    static LogOut = 'LogOut';
    static SOCIAL_LOGOUT_ATTEMPT = 'SOCIAL_LOGOUT_ATTEMPT';
    static RESET_SOCIAL_LOGOUT_ATTEMPT = 'RESET_SOCIAL_LOGOUT_ATTEMPT';
    static VerifyTwoWayAuthRequest = 'VerifyTwoWayAuthRequest';
    static VerifyTwoWayAuthResponse = 'VerifyTwoWayAuthResponse';
    static ResetTwoWayAuthModal = 'ResetTwoWayAuthModal';
    static AddNewMobileNo = 'AddNewMobileNo';
    static AddNewMobileNoResponse = 'AddNewMobileNoResponse';
    static VerifyAddNewMobileNo = 'VerifyAddNewMobileNo';
    static VerifyAddNewMobileNoResponse = 'VerifyAddNewMobileNoResponse';
    static LoginWithPasswdRequest = 'LoginWithPasswdRequest';
    static LoginWithPasswdResponse = 'LoginWithPasswdResponse';
    static SignupWithPasswdRequest = 'SignupWithPasswdRequest';
    static SignupWithPasswdResponse = 'SignupWithPasswdResponse';
    static forgotPasswordRequest = 'forgotPasswordRequest';
    static forgotPasswordResponse = 'forgotPasswordResponse';
    static resetPasswordRequest = 'resetPasswordRequest';
    static resetPasswordResponse = 'resetPasswordResponse';
    static hideTwoWayOtpPopup = 'hideTwoWayOtpPopup';
    static renewSessionResponse = 'renewSessionResponse';
    static FetchUserDetailsResponse = 'FetchUserDetailsResponse';
    static SetLoginStatus = 'SetLoginStatus';
    static SetCurrencyInStore = 'SetCurrencyInStore';
    static AutoLoginWithPasswdResponse = 'AutoLoginWithPasswdResponse';
    [key: string]: any;
}

// CommonActions class
export class CommonActions {
    static SET_BRANCH_CONSOLIDATED = 'SET_BRANCH_CONSOLIDATED';
    static SET_COMMON_LOCALE_DATA = 'SET_COMMON_LOCALE_DATA';
    static SET_ACTIVE_LOCALE = 'SET_ACTIVE_LOCALE';
    static SET_ACTIVE_FINANCIAL_YEAR = 'SET_ACTIVE_FINANCIAL_YEAR';
    static SET_ACTIVE_THEME = 'SET_ACTIVE_THEME';
    static SET_FILTERS = 'SET_FILTERS';
    static GET_COUNTRY_RESPONSE = 'GET_COUNTRY_RESPONSE';
    static GET_ALL_COUNTRY_RESPONSE = 'GET_ALL_COUNTRY_RESPONSE';
    static GET_CALLING_CODES_RESPONSE = 'GET_CALLING_CODES_RESPONSE';
    static GET_ONBOARDING_FORM = 'GET_ONBOARDING_FORM';
    static GET_ONBOARDING_FORM_RESPONSE = 'GET_ONBOARDING_FORM_RESPONSE';
    static GET_PARTY_TYPE_RESPONSE = 'GET_PARTY_TYPE_RESPONSE';
    static RESET_ONBOARDING_FORM_RESPONSE = 'RESET_ONBOARDING_FORM_RESPONSE';
    static RESET_COUNTRY = 'RESET_COUNTRY';
    static ACCOUNT_UPDATED = 'ACCOUNT_UPDATED';
    static SET_IMPORT_BANK_TRANSACTIONS_RESPONSE = 'SET_IMPORT_BANK_TRANSACTIONS_RESPONSE';
    static HAS_UNSAVED_CHANGES = 'HAS_UNSAVED_CHANGES';
    static BYPASS_UNSAVED_CHANGES = 'BYPASS_UNSAVED_CHANGES';
    static REAUTH_PLAID = 'REAUTH_PLAID';
    static SELECT_PRINTER = 'SELECT_PRINTER';
    [key: string]: any;
}

// CompanyActions class
export class CompanyActions {
    static GET_STATE_DETAILS_RESPONSE = 'GET_STATE_DETAILS_RESPONSE';
    static CHANGE_COMPANY_RESPONSE = 'CHANGE_COMPANY_RESPONSE';
    static SET_STATE_DETAILS_REQUEST = 'SET_STATE_DETAILS_REQUEST';
    static SET_STATE_DETAILS_RESPONSE = 'SET_STATE_DETAILS_RESPONSE';
    static SET_APPLICATION_DATE_RESPONSE = 'SET_APPLICATION_DATE_RESPONSE';
    static RESET_APPLICATION_DATE = 'RESET_APPLICATION_DATE';
    static SET_CONTACT_NO = 'SET_CONTACT_NO';
    static CREATE_COMPANY = 'CREATE_COMPANY';
    static RESET_CREATE_COMPANY_FLAG = 'RESET_CREATE_COMPANY_FLAG';
    static CREATE_COMPANY_RESPONSE = 'CREATE_COMPANY_RESPONSE';
    static CREATE_NEW_COMPANY = 'CREATE_NEW_COMPANY';
    static CREATE_NEW_COMPANY_RESPONSE = 'CREATE_NEW_COMPANY_RESPONSE';
    static USER_SELECTED_PLANS = 'USER_SELECTED_PLANS';
    static TOTAL_COMPANIES = 'TOTAL_COMPANIES';
    static CURRENT_COMPANY_CURRENCY = 'CURRENT_COMPANY_CURRENCY';
    static USER_CAREATE_COMPANY = 'USER_CAREATE_COMPANY';
    static USER_CAREATE_BRANCH = 'USER_CAREATE_BRANCH';
    static REFRESH_COMPANIES = 'REFRESH_COMPANIES';
    static REFRESH_COMPANIES_RESPONSE = 'REFRESH_COMPANIES_RESPONSE';
    static SET_MULTIPLE_CURRENCY_FIELD = 'SET_MULTIPLE_CURRENCY_FIELD';
    static USER_REMOVE_COMPANY_CREATE_SESSION = 'USER_REMOVE_COMPANY_CREATE_SESSION';
    static SET_USER_CHOSEN_FINANCIAL_YEAR = 'SET_USER_CHOSEN_FINANCIAL_YEAR';
    static RESET_USER_CHOSEN_FINANCIAL_YEAR = 'RESET_USER_CHOSEN_FINANCIAL_YEAR';
    static SET_COMPANY_BRANCH = 'SET_COMPANY_BRANCH';
    static GET_COMPANY_USER_RESPONSE = 'GET_COMPANY_USER_RESPONSE';
    static SET_ACTIVE_COMPANY_DATA = 'SET_ACTIVE_COMPANY_DATA';
    static RESET_ACTIVE_COMPANY_DATA = 'RESET_ACTIVE_COMPANY_DATA';
    static GET_TAX = 'GET_TAX';
    static GET_TAX_RESPONSE = 'GET_TAX_RESPONSE';
    static SET_ACTIVE_COMPANY = 'SET_ACTIVE_COMPANY';
    static GET_REGISTRATION_ACCOUNT = 'GET_REGISTRATION_ACCOUNT';
    static GET_REGISTRATION_ACCOUNT_RESPONSE = 'GET_REGISTRATION_ACCOUNT_RESPONSE';
    static SET_IS_TCS_TDS_APPLICABLE = 'SET_IS_TCS_TDS_APPLICABLE';
    static GET_ALL_INTEGRATED_BANK = 'GET_ALL_INTEGRATED_BANK';
    static GET_ALL_INTEGRATED_BANK_RESPONSE = 'GET_ALL_INTEGRATED_BANK_RESPONSE';
    [key: string]: any;
}

// VerifyMobileActions class
export class VerifyMobileActions {
    static SET_VERIFIACATION_MOBILENO = 'SET_VERIFIACATION_MOBILENO';
    static SHOW_VERIFICATION_BOX = 'SHOW_VERIFICATION_BOX';
    static VERIFY_MOBILE_CODE_RESPONSE = 'VERIFY_MOBILE_CODE_RESPONSE';
    static HIDE_VERIFICATION_BOX = 'HIDE_VERIFICATION_BOX';
    [key: string]: any;
}

// SessionActions class
export class SessionActions {
    static GET_ALL_SESSION_RESPONSE = 'GET_ALL_SESSION_RESPONSE';
    static DELETE_SESSION_RESPONSE = 'DELETE_SESSION_RESPONSE';
    static DELETE_ALL_SESSION_RESPONSE = 'DELETE_ALL_SESSION_RESPONSE';
    [key: string]: any;
}

// ItemOnBoardingActions class
export class ItemOnBoardingActions {
    static SET_ON_BOARDING_STATUS = 'SET_ON_BOARDING_STATUS';
    static SET_ON_BOARDING_TYPE = 'SET_ON_BOARDING_TYPE';
    static SET_ITEM_UPDATE_PROGRESS = 'SET_ITEM_UPDATE_PROGRESS';
    static RESET_ON_BOARDING = 'RESET_ON_BOARDING';
    [key: string]: any;
}

// SearchActions class
export class SearchActions {
    static SEARCH_RESPONSE = 'SEARCH_RESPONSE';
    static SEARCH_REQUEST = 'SEARCH_REQUEST';
    static RESET_SEARCH_STATE = 'RESET_SEARCH_STATE';
    [key: string]: any;
}

// TBPlBsActions class
export class TBPlBsActions {
    static GET_TRIAL_BALANCE_RESPONSE = 'GET_TRIAL_BALANCE_RESPONSE';
    static GET_V2_TRIAL_BALANCE_RESPONSE = 'GET_V2_TRIAL_BALANCE_RESPONSE';
    static GET_TRIAL_BALANCE_REQUEST = 'GET_TRIAL_BALANCE_REQUEST';
    static GET_V2_TRIAL_BALANCE_REQUEST = 'GET_V2_TRIAL_BALANCE_REQUEST';
    static GET_PROFIT_LOSS_RESPONSE = 'GET_PROFIT_LOSS_RESPONSE';
    static GET_PROFIT_LOSS_REQUEST = 'GET_PROFIT_LOSS_REQUEST';
    static GET_COGS_RESPONSE = 'GET_COGS_RESPONSE';
    static GET_BALANCE_SHEET_RESPONSE = 'GET_BALANCE_SHEET_RESPONSE';
    static GET_BALANCE_SHEET_REQUEST = 'GET_BALANCE_SHEET_REQUEST';
    [key: string]: any;
}

// SubscriptionsActions class
export class SubscriptionsActions {
    static SubscribedCompaniesResponse = 'SubscribedCompaniesResponse';
    static SubscribedUserTransactionsResponse = 'SubscribedUserTransactionsResponse';
    static SubscribedCompanyTransactionsResponse = 'SubscribedCompanyTransactionsResponse';
    static SubscribedCompaniesListResponse = 'SubscribedCompaniesListResponse';
    [key: string]: any;
}

export class AccountsAction {
    [key: string]: any;
}

export class GroupWithAccountsAction {
    [key: string]: any;
}

