/**
 * Placeholder constants for missing action files during Angular 21 migration
 * These provide temporary compatibility until action files are restored
 */

// Ledger constants
export const LEDGER = {
    GET_LEDGER: 'GET_LEDGER',
    SET_LEDGER: 'SET_LEDGER',
    RESET_LEDGER: 'RESET_LEDGER',
    GET_LEDGER_ACCOUNT: 'GET_LEDGER_ACCOUNT',
    GET_LEDGER_ACCOUNT_RESPONSE: 'GET_LEDGER_ACCOUNT_RESPONSE',
    GET_TRANSACTION: 'GET_TRANSACTION',
    GET_TRANSACTION_RESPONSE: 'GET_TRANSACTION_RESPONSE',
    ADVANCE_SEARCH: 'ADVANCE_SEARCH',
    ADVANCE_SEARCH_RESPONSE: 'ADVANCE_SEARCH_RESPONSE',
    DOWNLOAD_LEDGER_INVOICE: 'DOWNLOAD_LEDGER_INVOICE',
    DOWNLOAD_LEDGER_INVOICE_RESPONSE: 'DOWNLOAD_LEDGER_INVOICE_RESPONSE',
    CREATE_BLANK_LEDGER_REQUEST: 'CREATE_BLANK_LEDGER_REQUEST',
    CREATE_BLANK_LEDGER_RESPONSE: 'CREATE_BLANK_LEDGER_RESPONSE',
    CREATE_BULK_BLANK_LEDGER_RESPONSE: 'CREATE_BULK_BLANK_LEDGER_RESPONSE',
    RESET_BLANK_LEDGER_REQUEST: 'RESET_BLANK_LEDGER_REQUEST',
    SET_SELECTED_TXN_FOR_EDIT: 'SET_SELECTED_TXN_FOR_EDIT',
    SET_SELECTED_ACCOUNT_FOR_EDIT: 'SET_SELECTED_ACCOUNT_FOR_EDIT',
    DELETE_TRX_ENTRY: 'DELETE_TRX_ENTRY',
    DELETE_TRX_ENTRY_RESPONSE: 'DELETE_TRX_ENTRY_RESPONSE',
    RESET_DELETE_TRX_ENTRY_MODAL: 'RESET_DELETE_TRX_ENTRY_MODAL',
    LEDGER_SHARED_ACCOUNT_WITH_RESPONSE: 'LEDGER_SHARED_ACCOUNT_WITH_RESPONSE',
    UPDATE_TXN_ENTRY: 'UPDATE_TXN_ENTRY',
    RESET_UPDATE_TXN_ENTRY: 'RESET_UPDATE_TXN_ENTRY',
    UPDATE_TXN_ENTRY_RESPONSE: 'UPDATE_TXN_ENTRY_RESPONSE',
    CREATE_QUICK_ACCOUNT: 'CREATE_QUICK_ACCOUNT',
    CREATE_QUICK_ACCOUNT_RESPONSE: 'CREATE_QUICK_ACCOUNT_RESPONSE',
    GET_LEDGER_TRX_DETAILS_RESPONSE: 'GET_LEDGER_TRX_DETAILS_RESPONSE',
    RESET_LEGER_TRX_DETAILS: 'RESET_LEGER_TRX_DETAILS',
    RESET_QUICK_ACCOUNT_MODAL: 'RESET_QUICK_ACCOUNT_MODAL',
    GET_RECONCILIATION_RESPONSE: 'GET_RECONCILIATION_RESPONSE',
    DELETE_MULTIPLE_LEDGER_ENTRIES: 'DELETE_MULTIPLE_LEDGER_ENTRIES',
    DELETE_MULTIPLE_LEDGER_ENTRIES_RESPONSE: 'DELETE_MULTIPLE_LEDGER_ENTRIES_RESPONSE',
    GENERATE_BULK_LEDGER_INVOICE: 'GENERATE_BULK_LEDGER_INVOICE',
    GENERATE_BULK_LEDGER_INVOICE_RESPONSE: 'GENERATE_BULK_LEDGER_INVOICE_RESPONSE',
    SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION: 'SHOW_BULK_GENERATE_VOUCHER_CONFIRMATION',
    GET_CURRENCY_RATE_RESPONSE: 'GET_CURRENCY_RATE_RESPONSE',
    SELECT_DESELECT_ALL_ENTRIES: 'SELECT_DESELECT_ALL_ENTRIES',
    SELECT_GIVEN_ENTRIES: 'SELECT_GIVEN_ENTRIES',
    DESELECT_GIVEN_ENTRIES: 'DESELECT_GIVEN_ENTRIES',
    SET_FAILED_BULK_ENTRIES: 'SET_FAILED_BULK_ENTRIES',
    GET_LEDGER_BALANCE: 'GET_LEDGER_BALANCE',
    GET_LEDGER_BALANCE_RESPONSE: 'GET_LEDGER_BALANCE_RESPONSE',
    REFRESH_LEDGER: 'REFRESH_LEDGER',
    SHOW_DUPLICATE_VOUCHER_CONFIRMATION: 'SHOW_DUPLICATE_VOUCHER_CONFIRMATION'
};

// Manufacturing constants
export const MANUFACTURING_ACTIONS = {
    GET_MANUFACTURING: 'GET_MANUFACTURING',
    SET_MANUFACTURING: 'SET_MANUFACTURING',
    RESET_MANUFACTURING: 'RESET_MANUFACTURING',
    MF_REPORT: 'MF_REPORT',
    MF_REPORT_RESPONSE: 'MF_REPORT_RESPONSE',
    GET_STOCK_WITH_RATE: 'GET_STOCK_WITH_RATE',
    GET_STOCK_WITH_RATE_RESPONSE: 'GET_STOCK_WITH_RATE_RESPONSE',
    CREATE_MF_ITEM: 'CREATE_MF_ITEM',
    CREATE_MF_ITEM_RESPONSE: 'CREATE_MF_ITEM_RESPONSE',
    UPDATE_MF_ITEM: 'UPDATE_MF_ITEM',
    UPDATE_MF_ITEM_RESPONSE: 'UPDATE_MF_ITEM_RESPONSE',
    DELETE_MF_ITEM: 'DELETE_MF_ITEM',
    DELETE_MF_ITEM_RESPONSE: 'DELETE_MF_ITEM_RESPONSE',
    SET_MF_ITEM_UNIQUENAME_IN_STORE: 'SET_MF_ITEM_UNIQUENAME_IN_STORE',
    REMOVE_MF_ITEM_UNIQUENAME_FROM_STORE: 'REMOVE_MF_ITEM_UNIQUENAME_FROM_STORE'
};

// Permission constants
export const PERMISSION_ACTIONS = {
    GET_PERMISSIONS: 'GET_PERMISSIONS',
    SET_PERMISSIONS: 'SET_PERMISSIONS',
    RESET_PERMISSIONS: 'RESET_PERMISSIONS'
};

// Proforma constants
export const PROFORMA_ACTIONS = {
    GET_PROFORMA: 'GET_PROFORMA',
    SET_PROFORMA: 'SET_PROFORMA',
    RESET_PROFORMA: 'RESET_PROFORMA'
};

// Purchase order constants
export const PURCHASE_ORDER_ACTIONS = {
    GET_PURCHASE_ORDER: 'GET_PURCHASE_ORDER',
    SET_PURCHASE_ORDER: 'SET_PURCHASE_ORDER',
    RESET_PURCHASE_ORDER: 'RESET_PURCHASE_ORDER'
};

// Purchase record constants
export const PURCHASE_RECORD_ACTIONS = {
    GET_PURCHASE_RECORD: 'GET_PURCHASE_RECORD',
    SET_PURCHASE_RECORD: 'SET_PURCHASE_RECORD',
    RESET_PURCHASE_RECORD: 'RESET_PURCHASE_RECORD'
};

// Sales constants
export const SALES_ACTIONS = {
    GET_SALES: 'GET_SALES',
    SET_SALES: 'SET_SALES',
    RESET_SALES: 'RESET_SALES',
    STOCK_AC_SUCCESS: 'STOCK_AC_SUCCESS'
};

// Subscriptions constants
export const SUBSCRIPTIONS_ACTIONS = {
    GET_SUBSCRIPTIONS: 'GET_SUBSCRIPTIONS',
    SET_SUBSCRIPTIONS: 'SET_SUBSCRIPTIONS',
    RESET_SUBSCRIPTIONS: 'RESET_SUBSCRIPTIONS'
};

// Placeholder action classes
export class AccountsAction {
    [key: string]: any;
}

export class SearchActions {
    static SEARCH_RESPONSE = 'SEARCH_RESPONSE';
    static SEARCH_REQUEST = 'SEARCH_REQUEST';
    static RESET_SEARCH_STATE = 'RESET_SEARCH_STATE';
    [key: string]: any;
}

export class TBPlBsActions {
    static GET_TRIAL_BALANCE_RESPONSE = 'GET_TRIAL_BALANCE_RESPONSE';
    static GET_V2_TRIAL_BALANCE_RESPONSE = 'GET_V2_TRIAL_BALANCE_RESPONSE';
    static GET_TRIAL_BALANCE_REQUEST = 'GET_TRIAL_BALANCE_REQUEST';
    static GET_V2_TRIAL_BALANCE_REQUEST = 'GET_V2_TRIAL_BALANCE_REQUEST';
    static GET_PROFIT_LOSS_RESPONSE = 'GET_PROFIT_LOSS_RESPONSE';
    static GET_PROFIT_LOSS_REQUEST = 'GET_PROFIT_LOSS_REQUEST';
    static GET_COGS_RESPONSE = 'GET_COGS_RESPONSE';
    static GET_BALANCE_SHEET_RESPONSE = 'GET_BALANCE_SHEET_RESPONSE';
    static GET_BALANCE_SHEET_REQUEST = 'GET_BALANCE_SHEET_REQUEST';
    [key: string]: any;
}

export class SubscriptionsActions {
    static SubscribedCompaniesResponse = 'SubscribedCompaniesResponse';
    static SubscribedUserTransactionsResponse = 'SubscribedUserTransactionsResponse';
    static SubscribedCompanyTransactionsResponse = 'SubscribedCompanyTransactionsResponse';
    static SubscribedCompaniesListResponse = 'SubscribedCompaniesListResponse';
    [key: string]: any;
}

export class GroupWithAccountsAction {
    [key: string]: any;
}
