export const SETTINGS_LINKED_ACCOUNTS_ACTIONS = {
  GET_BANKS_ACCOUNTS: 'SETTINGS_GET_BANKS_ACCOUNTS',
  GET_BANKS_ACCOUNTS_RESPONSE: 'SETTINGS_GET_BANKS_ACCOUNTS_RESPONSE',
  DELETE_BANKS_ACCOUNTS: 'DELETE_BANKS_ACCOUNTS',
  DELETE_BANKS_ACCOUNTS_RESPONSE: 'DELETE_BANKS_ACCOUNTS_RESPONSE'
};
