export const HOME = {
  EXPENSES_CHART: {
    GET_EXPENSES_CHART_DATA_ACTIVE_YEAR: 'GET_EXPENSES_CHART_DATA_ACTIVE_YEAR',
    GET_EXPENSES_CHART_DATA_ACTIVE_YEAR_RESPONSE: 'GET_EXPENSES_CHART_DATA_ACTIVE_YEAR_RESPONSE',

    GET_EXPENSES_CHART_DATA_LAST_YEAR: 'GET_EXPENSES_CHART_DATA_LAST_YEAR',
    GET_EXPENSES_CHART_DATA_LAST_YEAR_RESPONSE: 'GET_EXPENSES_CHART_DATA_LAST_YEAR_RESPONSE',
  },
  REVENUE_CHART: {
    GET_REVENUE_CHART_DATA_ACTIVE_YEAR: 'GET_REVENUE_CHART_DATA_ACTIVE_YEAR',
    GET_REVENUE_CHART_DATA_ACTIVE_YEAR_RESPONSE: 'GET_REVENUE_CHART_DATA_ACTIVE_YEAR_RESPONSE',

    GET_REVENUE_CHART_DATA_LAST_YEAR: 'GET_REVENUE_CHART_DATA_LAST_YEAR',
    GET_REVENUE_CHART_DATA_LAST_YEAR_RESPONSE: 'GET_REVENUE_CHART_DATA_LAST_YEAR_RESPONSE',
  },
  COMPARISION_CHART: {
    GET_COMPARISION_CHART_DATA_ACTIVE_YEAR: 'GET_COMPARISION_CHART_DATA_ACTIVE_YEAR',
    GET_COMPARISION_CHART_DATA_ACTIVE_YEAR_RESPONSE: 'GET_COMPARISION_CHART_DATA_ACTIVE_YEAR_RESPONSE',

    GET_COMPARISION_CHART_DATA_LAST_YEAR: 'GET_COMPARISION_CHART_DATA_LAST_YEAR',
    GET_COMPARISION_CHART_DATA_LAST_YEAR_RESPONSE: 'GET_COMPARISION_CHART_DATA_LAST_YEAR_RESPONSE',

  }
};
