export const PURCHASE_INVOICE_ACTIONS = {
  GET_PURCHASE_INVOICES: 'GET_PURCHASE_INVOICES',
  GET_TAXES: 'GET_TAXES',
  GET_PURCHASE_INVOICES_RESPONSE: 'GET_PURCHASE_INVOICES_RESPONSE',
  UPDATE_PURCHASE_INVOICE: 'UPDATE_PURCHASE_INVOICE',
  UPDATE_PURCHASE_INVOICE_RESPONSE: 'UPDATE_PURCHASE_INVOICE_RESPONSE',
  DOWNLOAD_GSTR1_SHEET: 'DOWNLOAD_GSTR1_SHEET',
  DOWNLOAD_GSTR1_SHEET_RESPONSE: 'DOWNLOAD_GSTR1_SHEET_RESPONSE',
  DOWNLOAD_GSTR1_ERROR_SHEET: 'DOWNLOAD_GSTR1_ERROR_SHEET',
  DOWNLOAD_GSTR1_ERROR_SHEET_RESPONSE: 'DOWNLOAD_GSTR1_ERROR_SHEET_RESPONSE',
  SET_TAXES_FOR_COMPANY: 'SET_TAXES_FOR_COMPANY',
  GENERATE_PURCHASE_INVOICE: 'GENERATE_PURCHASE_INVOICE',
  UPDATE_ENTRY: 'UPDATE_ENTRY',
  UPDATE_ENTRY_RESPONSE: 'UPDATE_ENTRY_RESPONSE',
  UPDATE_INVOICE: 'UPDATE_INVOICE',
  UPDATE_INVOICE_RESPONSE: `UPDATE_INVOICE_RESPONSE`,
  SEND_GSTR3B_EMAIL: 'SEND_GSTR3B_EMAIL',
  SEND_GSTR3B_EMAIL_RESPONSE: 'SEND_GSTR3B_EMAIL_RESPONSE'
};

export const GST_RETURN_ACTIONS = {
  SAVE_JIO_GST: 'SAVE_JIO_GST',
  SAVE_JIO_GST_RESPONSE: 'SAVE_JIO_GST_RESPONSE'
};
