export const SETTINGS_BRANCH_ACTIONS = {
    GET_BRANCH_INFO: 'GET_BRANCH_INFO',
    GET_BRANCH_INFO_RESPONSE: 'GET_BRANCH_INFO_RESPONSE',
    UPDATE_BRANCH: 'UPDATE_BRANCH',
    UPDATE_BRANCH_RESPONSE: 'UPDATE_BRANCH_RESPONSE',
    CREATE_BRANCH: 'CREATE_BRANCH',
    CREATE_BRANCH_RESPONSE: 'CREATE_BRANCH_RESPONSE',
    DELETE_BRANCH: 'DELETE_BRANCH',
    DELETE_BRANCH_RESPONSE: 'DELETE_BRANCH_RESPONSE',
    REMOVED_BRANCH_RESPONSE: 'REMOVED_BRANCH_RESPONSE',
    RESET_REMOVED_BRANCH_RESPONSE: 'RESET_REMOVED_BRANCH_RESPONSE',
    RESET_ALL_BRANCHES_RESPONSE: 'RESET_ALL_BRANCHES_RESPONSE'
};
