export const SETTINGS_BRANCH_ACTIONS = {
    GET_ALL_BRANCHES: 'GET_ALL_BRANCHES',
    GET_ALL_BRANCHES_RESPONSE: 'GET_ALL_BRANCHES_RESPONSE',
    CREATE_BRANCHES: 'CREATE_BRANCHES',
    CREATE_BRANCHES_RESPONSE: 'CREATE_BRANCHES_RESPONSE',
    REMOVE_BRANCH: 'REMOVE_BRANCH',
    REMOVE_BRANCH_RESPONSE: 'REMOVE_BRANCH_RESPONSE',
    GET_PARENT_COMPANY: 'GET_PARENT_COMPANY',
    GET_PARENT_COMPANY_RESPONSE: 'GET_PARENT_COMPANY_RESPONSE',
    REMOVED_BRANCH_RESPONSE: 'REMOVED_BRANCH_RESPONSE',
    RESET_REMOVED_BRANCH_RESPONSE: 'RESET_REMOVED_BRANCH_RESPONSE'
};
