export const LEDGER = {
  GET_TRANSACTION: 'GET_TRANSACTION',
  GET_TRANSACTION_RESPONSE: 'GET_TRANSACTION_RESPONSE',
  GET_LEDGER_ACCOUNT: 'GET_LEDGER_ACCOUNT',
  GET_LEDGER_ACCOUNT_RESPONSE: 'GET_LEDGER_ACCOUNT_RESPONSE',
  DOWNLOAD_LEDGER_INVOICE: 'DOWNLOAD_LEDGER_INVOICE',
  DOWNLOAD_LEDGER_INVOICE_RESPONSE: 'DOWNLOAD_LEDGER_INVOICE_RESPONSE',
  GET_DISCOUNT_ACCOUNTS_LIST: 'GET_DISCOUNT_ACCOUNTS_LIST',
  GET_DISCOUNT_ACCOUNTS_LIST_RESPONSE: 'GET_DISCOUNT_ACCOUNTS_LIST_RESPONSE',
  CREATE_BLANK_LEDGER_REQUEST: 'CREATE_BLANK_LEDGER_REQUEST',
  CREATE_BLANK_LEDGER_RESPONSE: 'CREATE_BLANK_LEDGER_RESPONSE',
  RESET_LEDGER: 'RESET_LEDGER'
};
