version: 0.2

phases:
  pre_build:
    commands:
      - rm -rf node_modules
      - npm cache clean --force
      - npm install --force
  build:
    commands:
      - |
        if [ "${AWS_BRANCH}" = "giddh-2.0" ]; then
          npm run build-test
        elif [ "${AWS_BRANCH}" = "beta-stage" ]; then
          npm run build-stage
        elif [ "${AWS_BRANCH}" = "beta-branch" ]; then
          npm run build-prod
        elif [ "${AWS_BRANCH}" = "production" ]; then
          npm run build-prod
        fi

artifacts:
    baseDirectory: /dist/apps/web-giddh/
    files: '**/*'
