export const GENERAL_ACTIONS = {
  GENERAL_GET_GROUP_WITH_ACCOUNTS: 'GeneralGroupWithAccounts',
  GENERAL_GET_GROUP_WITH_ACCOUNTS_RESPONSE: 'GeneralGroupWithAccountsResponse',
  GENERAL_GET_FLATTEN_ACCOUNTS: 'GENERAL_GET_FLATTEN_ACCOUNTS',
  GENERAL_GET_FLATTEN_ACCOUNTS_RESPONSE: 'GENERAL_GET_FLATTEN_ACCOUNTS_RESPONSE',
  GENERAL_GET_ALL_STATES: 'GENERAL_GET_ALL_STATES',
  GENERAL_GET_ALL_STATES_RESPONSE: 'GENERAL_GET_ALL_STATES_RESPONSE',
  CLOSE_ADD_AND_MANAGE: 'CLOSE_ADD_AND_MANAGE'
};
