export const MANUFACTURING_ACTIONS = {
  GET_STOCK_LIST: 'GET_STOCK_LIST',
  GET_STOCK_LIST_RESPONSE: 'GET_STOCK_LIST_RESPONSE',
  GET_MF_ITEM_DETAILS: 'GET_MF_ITEM_DETAILS',
  GET_MF_ITEM_DETAILS_RESPONSE: 'GET_MF_ITEM_DETAILS_RESPONSE',
  CREATE_MF_ITEM: 'CREATE_MF_ITEM',
  CREATE_MF_ITEM_RESPONSE: 'CREATE_MF_ITEM_RESPONSE',
  UPDATE_MF_ITEM: 'UPDATE_MF_ITEM',
  UPDATE_MF_ITEM_RESPONSE: 'UPDATE_MF_ITEM_RESPONSE',
  DELETE_MF_ITEM: 'DELETE_MF_ITEM',
  DELETE_MF_ITEM_RESPONSE: 'DELETE_MF_ITEM_RESPONSE',
};
