export const PURCHASE_INVOICE_ACTIONS = {
  GET_PURCHASE_INVOICES: 'GET_PURCHASE_INVOICES',
  GET_PURCHASE_INVOICES_RESPONSE: 'GET_PURCHASE_INVOICES_RESPONSE',
  UPDATE_PURCHASE_INVOICE: 'UPDATE_PURCHASE_INVOICE',
  UPDATE_PURCHASE_INVOICE_RESPONSE: 'UPDATE_PURCHASE_INVOICE_RESPONSE',
};
