const aif = ['audio/x-aiff', 'audio/aiff'];
const mid = ['audio/midi', 'audio/x-midi'];
const ogg = ['application/ogg', 'audio/ogg', 'video/ogg'];
const wav = ['audio/wav', 'audio/x-wav'];
const arj = ['application/arj', 'application/octet-stream'];
const rar = ['application/vnd.rar', 'application/x-rar-compressed'];
const z = ['application/x-compress', 'application/x-compressed'];
const xml = ['application/xml', 'text/xml'];
const ico = ['image/vnd.microsoft.icon', 'image/x-icon'];
const cer = ['application/x-x509-ca-cert', 'application/pkix-cert'];
const _3g2 = ['video/3gpp2', 'audio/3gpp2'];
const _3gp = ['video/3gpp', 'audio/3gpp'];
export let fileType = [
    ...aif,
    'application/x-cdf',
    ...mid,
    'audio/mpeg',
    'video/mpeg',
    ...ogg,
    ...wav,
    'audio/x-ms-wma',
    'application/vnd.ms-wpl',
    'application/x-7z-compressed',
    ...arj,
    'application/vnd.debian.binary-package',
    'application/x-newton-compatible-pkg',
    ...rar,
    'audio/x-pn-realaudio-plugin',
    'application/x-tar',
    'application/gzip',
    ...z,
    'application/zip',
    'application/x-apple-diskimage',
    'application/x-cdlink',
    'text/csv',
    ...xml,
    'email',
    'message/rfc822',
    'application/vnd.ms-outlook',
    'text/x-vcard',
    'application/x-font-otf',
    'font/otf',
    'application/x-font-ttf',
    'font/ttf',
    'application/postscript',
    'image/bmp',
    'image/gif',
    ...ico,
    'image/jpeg',
    'image/png',
    'image/vnd.adobe.photoshop',
    'image/svg+xml',
    'image/tiff',
    ...cer,
    'application/x-cfm',
    'text/html',
    'application/vnd.oasis.opendocument.spreadsheet',
    'application/vnd.ms-excel',
    'application/vnd.ms-excel.sheet.macroenabled.12',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    ..._3g2,
    ..._3gp,
    'video/x-msvideo',
    'video/x-flv',
    'video/h264',
    'video/x-m4v',
    'video/x-matroska',
    'video/quicktime',
    'video/mp4',
    'video/mpeg',
    'application/vnd.rn-realmedia',
    'application/x-shockwave-flash',
    'video/x-ms-wmv',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.oasis.opendocument.text',
    'application/pdf',
    'application/rtf',
    'application/x-tex',
    'text/plain',
    'application/vnd.wordperfect',
    'application/vnd.ms-powerpoint',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'application/json',
];
