#!/usr/bin/env node

/**
 * Angular 21 Compatible Environment Variable Build Script
 *
 * This script loads environment variables from .env files and generates
 * environment-specific TypeScript files at build time.
 *
 * Usage: node scripts/build-env.js [environment]
 * Example: node scripts/build-env.js local
 */

const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

// Get environment from command line argument or default to 'local'
const environment = process.argv[2] || 'local';

console.log(`🔧 Building environment configuration for: ${environment}`);

// Map environments to .env files
const envFileMap = {
    'local': '.env.local',
    'stage': '.env.stage',
    'prod': '.env.prod',
    'test': '.env.electron', // Use electron for test builds (electron-giddh)
    'electron': '.env.electron' // Explicit electron environment
};

// SECURITY: Prioritize server environment variables over .env files
// This prevents credentials from being committed to public repositories
const isProduction = environment === 'prod';
const isCI = process.env.CI === 'true' || process.env.NODE_ENV === 'production';

if (isProduction || isCI) {
    console.log(`🔒 Production/CI environment detected - using server environment variables`);
    console.log(`🚫 Skipping .env file loading for security`);
} else {
    // Load .env file only for local development
    const envFile = envFileMap[environment] || '.env.local';
    const envPath = path.resolve(__dirname, '../', envFile);

    console.log(`📁 Development environment - loading from: ${envFile}`);

    // Load environment variables from .env file
    const envResult = dotenv.config({ path: envPath });

    if (envResult.error) {
        console.warn(`⚠️  Warning: Could not load ${envFile}. Using server environment variables as fallback.`);
        console.warn(`Error: ${envResult.error.message}`);
    } else {
        console.log(`✅ Successfully loaded ${envFile}`);
    }
}

// Get environment variables with fallbacks
const env = process.env;

// Generate environment-specific configuration
const envConfig = {
    // Build configuration
    BUILD_CONFIGURATION: environment,
    VERSION: require('../package.json').version,

    // Environment flags
    ENV: environment === 'prod' ? 'production' : 'development',
    PRODUCTION_ENV: environment === 'prod',
    STAGING_ENV: environment === 'stage',
    LOCAL_ENV: environment === 'local',
    TEST_ENV: environment === 'test',

    // Application configuration
    isElectron: env.IS_ELECTRON === 'true' || false,
    errlyticsNeeded: env.ERRLYTIC_NEEDED === 'true' || false,
    errlyticsKey: env.ERRLYTIC_KEY || '',
    APP_FOLDER: env.APP_FOLDER || '',

    // URLs based on environment
    AppUrl: getAppUrl(environment, env),
    ApiUrl: getApiUrl(environment, env),
    UkApiUrl: getUkApiUrl(environment, env),
    PORTAL_URL: getPortalUrl(environment, env),
    OFFLINE_API_URL: env.OFFLINE_API_URL || 'http://localhost:59448/',

    // Feature flags
    enableVoucherAdjustmentMultiCurrency: env.ENABLE_VOUCHER_ADJUSTMENT_MULTI_CURRENCY === 'true' || true,

    // External service keys
    GOOGLE_CLIENT_ID: env.GOOGLE_CLIENT_ID || '',
    GOOGLE_CLIENT_SECRET: env.GOOGLE_CLIENT_SECRET || '',
    RAZORPAY_KEY: env.RAZORPAY_KEY || '',
    OTP_WIDGET_ID: env.OTP_WIDGET_ID || '',
    OTP_TOKEN_AUTH: env.OTP_TOKEN_AUTH || '',
    TWITTER_CLIENT_ID: env.TWITTER_CLIENT_ID || '',
    TWITTER_SECRET_KEY: env.TWITTER_SECRET_KEY || '',
    LINKEDIN_CLIENT_ID: env.LINKEDIN_CLIENT_ID || '',
    LINKEDIN_SECRET_KEY: env.LINKEDIN_SECRET_KEY || ''
};

// Generate TypeScript environment file content - Angular 21 standard approach
const envFileContent = `/* tslint:disable */
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/build-env.js for environment: ${environment}
// Generated at: ${new Date().toISOString()}

import { ApplicationRef, NgModuleRef } from '@angular/core';
import { ${environment === 'prod' ? 'disableDebugTools' : 'enableDebugTools'} } from '@angular/platform-browser';
import { Environment } from './model';

${environment === 'prod' ? 'import { enableProdMode } from \'@angular/core\';\nenableProdMode();' : 'Error.stackTraceLimit = Infinity;'}

export const environment: Environment = {
    production: ${envConfig.PRODUCTION_ENV},
    showDevModule: ${!envConfig.PRODUCTION_ENV},
    AppUrl: '${envConfig.AppUrl}',
    ApiUrl: '${envConfig.ApiUrl}',
    UkApiUrl: '${envConfig.UkApiUrl}',
    isElectron: ${envConfig.isElectron},
    APP_FOLDER: '${envConfig.APP_FOLDER}',
    PORTAL_URL: '${envConfig.PORTAL_URL}',
    GOOGLE_CLIENT_ID: '${envConfig.GOOGLE_CLIENT_ID}',
    GOOGLE_CLIENT_SECRET: '${envConfig.GOOGLE_CLIENT_SECRET}',
    OTP_WIDGET_ID: '${envConfig.OTP_WIDGET_ID}',
    OTP_TOKEN_AUTH: '${envConfig.OTP_TOKEN_AUTH}',
    RAZORPAY_KEY: '${envConfig.RAZORPAY_KEY}',
    PRODUCTION_ENV: ${envConfig.PRODUCTION_ENV},
    STAGING_ENV: ${envConfig.STAGING_ENV},
    LOCAL_ENV: ${envConfig.LOCAL_ENV},
    TEST_ENV: ${envConfig.TEST_ENV},
    /** Angular debug tools in the dev console
     * https://github.com/angular/angular/blob/86405345b781a9dc2438c0fbe3e9409245647019/TOOLS_JS.md
     * @param modRef
     * @return {any}
     */
    decorateModuleRef(modRef: NgModuleRef<any>) {
        ${environment === 'prod' ?
            'disableDebugTools();\n        return modRef;' :
            'const appRef = modRef.injector.get(ApplicationRef);\n        const cmpRef = appRef.components[0];\n\n        let _ng = (<any>window).ng;\n        enableDebugTools(cmpRef);\n        (<any>window).ng.probe = _ng.probe;\n        (<any>window).ng.coreTokens = _ng.coreTokens;\n        return modRef;'
        }
    },
    ENV_PROVIDERS: []
};

// Set global variables for backward compatibility
(window as any).PRODUCTION_ENV = environment.production;
(window as any).STAGING_ENV = ${envConfig.STAGING_ENV};
(window as any).LOCAL_ENV = ${envConfig.LOCAL_ENV};
(window as any).TEST_ENV = ${envConfig.TEST_ENV};
(window as any).AppUrl = environment.AppUrl;
(window as any).ApiUrl = environment.ApiUrl;
(window as any).isElectron = environment.isElectron;
`;

// Write the generated environment file
const outputPath = path.resolve(__dirname, '../apps/web-giddh/src/environments/environment.generated.ts');
fs.writeFileSync(outputPath, envFileContent);

console.log(`📝 Generated environment file: ${outputPath}`);
console.log('🌍 Environment Configuration:');
console.log(`   Build: ${environment}`);
console.log(`   App URL: ${envConfig.AppUrl}`);
console.log(`   API URL: ${envConfig.ApiUrl}`);
console.log(`   Production: ${envConfig.PRODUCTION_ENV}`);
console.log('✅ Environment build completed successfully!');

/**
 * Get App URL based on environment
 */
function getAppUrl(config, env) {
    if (env.APP_URL) return env.APP_URL;

    switch (config) {
        case 'prod': return 'https://books.giddh.com';
        case 'stage': return 'https://stage.giddh.com';
        case 'local':
        case 'test':
        default: return 'http://localhost:3000/';
    }
}

/**
 * Get API URL based on environment
 */
function getApiUrl(config, env) {
    if (env.API_URL) return env.API_URL;

    switch (config) {
        case 'prod': return 'https://api.giddh.com/';
        case 'stage': return 'https://apistage.giddh.com/';
        case 'local':
        case 'test':
        default: return 'https://apitest.giddh.com/';
    }
}

/**
 * Get UK API URL based on environment
 */
function getUkApiUrl(config, env) {
    if (env.UK_API_URL) return env.UK_API_URL;

    switch (config) {
        case 'prod': return 'https://gbapi.giddh.com/';
        case 'stage': return 'https://gbapistage.giddh.com/';
        case 'local':
        case 'test':
        default: return 'https://gbapi.giddh.com/';
    }
}

/**
 * Get Portal URL based on environment
 */
function getPortalUrl(config, env) {
    if (env.PORTAL_URL) return env.PORTAL_URL;

    switch (config) {
        case 'prod': return 'https://portal.giddh.com/';
        case 'stage': return 'https://portal-stage.giddh.com/';
        case 'local':
        case 'test':
        default: return 'https://master.d2n1i21e52r793.amplifyapp.com/';
    }
}
