export const PERMISSION_ACTIONS = {
	GET_ROLES: 'GET_ROLES',
	GET_ROLES_RESPONSE: 'GET_ROLES_RESPONSE',
	CREATE_NEW_ROLE: 'CREATE_NEW_ROLE',
	CREATE_NEW_ROLE_RESPONSE: 'CREATE_NEW_ROLE_RESPONSE',
	CREATE_ROLE_FAILED: 'CREATE_ROLE_FAILED',
	PUSH_TEMP_ROLE_IN_STORE: 'PUSH_TEMP_ROLE_IN_STORE',
	DELETE_ROLE: 'DELETE_ROLE',
	ROLE_DELETED: 'ROLE_DELETED'
}