export const SETTINGS_TAG_ACTIONS = {
    GET_ALL_TAGS: 'GET_ALL_TAGS',
    GET_ALL_TAGS_RESPONSE: 'GET_ALL_TAGS_RESPONSE',
    CREATE_TAG: 'CREATE_TAG',
    CREATE_TAG_RESPONSE: 'CREATE_TAG_RESPONSE',
    UPDATE_TAG: 'UPDATE_TAG',
    UPDATE_TAG_RESPONSE: 'UPDATE_TAG_RESPONSE',
    DELETE_TAG: 'DELETE_TAG',
    DELETE_TAG_RESPONSE: 'DELETE_TAG_RESPONSE',
};
