export const SALES_ACTIONS = {
  GET_ACCOUNT_DETAILS: 'GET_ACCOUNT_DETAILS',
  GET_ACCOUNT_DETAILS_RESPONSE: 'GET_ACCOUNT_DETAILS_RESPONSE',
  GET_HIERARCHICAL_STOCK_GROUPS: 'GET_HIERARCHICAL_STOCK_GROUPS',
  GET_HIERARCHICAL_STOCK_GROUPS_RESPONSE: 'GET_HIERARCHICAL_STOCK_GROUPS_RESPONSE',
  GET_PURCHASE_AC_LIST: 'GET_PURCHASE_AC_LIST',
  GET_PURCHASE_AC_LIST_RESPONSE: 'GET_PURCHASE_AC_LIST_RESPONSE',
  GET_SALES_AC_LIST: 'GET_SALES_AC_LIST',
  GET_SALES_AC_LIST_RESPONSE: 'GET_SALES_AC_LIST_RESPONSE',
};
