export const GST_RECONCILE_ACTIONS = {
  GST_RECONCILE_OTP_REQUEST: 'GST_RECONCILE_OTP_REQUEST',
  GST_RECONCILE_OTP_RESPONSE: 'GST_RECONCILE_OTP_RESPONSE',
  GST_RECONCILE_INVOICE_PERIOD_REQUEST: 'GST_RECONCILE_INVOICE_PERIOD_REQUEST',
  GST_RECONCILE_INVOICE_PERIOD_RESPONSE: 'GST_RECONCILE_INVOICE_PERIOD_RESPONSE',
  GST_RECONCILE_VERIFY_OTP_REQUEST: 'GST_RECONCILE_VERIFY_OTP_REQUEST',
  GST_RECONCILE_VERIFY_OTP_RESPONSE: 'GST_RECONCILE_VERIFY_OTP_RESPONSE'
};
