export const GST_RECONCILE_ACTIONS = {
  GST_RECONCILE_OTP_REQUEST: 'GST_RECONCILE_OTP_REQUEST',
  GST_RECONCILE_OTP_RESPONSE: 'GST_RECONCILE_OTP_RESPONSE',
  GST_RECONCILE_INVOICE_REQUEST: 'GST_RECONCILE_INVOICE_REQUEST',
  GST_RECONCILE_INVOICE_RESPONSE: 'GST_RECONCILE_INVOICE_RESPONSE',
  GST_RECONCILE_VERIFY_OTP_REQUEST: 'GST_RECONCILE_VERIFY_OTP_REQUEST',
  GST_RECONCILE_VERIFY_OTP_RESPONSE: 'GST_RECONCILE_VERIFY_OTP_RESPONSE',
  RESET_GST_RECONCILE_STATE: 'RESET_GST_RECONCILE_STATE',
  PULL_FROM_GSTIN: 'PULL_FROM_GSTIN'
};

export const GSTR_ACTIONS = {
  GET_GSTR_OVERVIEW: 'GET_GSTR_OVERVIEW',
  GET_GSTR_OVERVIEW_RESPONSE: 'GET_GSTR_OVERVIEW_RESPONSE',
  GET_SUMMARY_TRANSACTIONS: 'GET_SUMMARY_TRANSACTIONS',
  GET_SUMMARY_TRANSACTIONS_RESPONSE: 'GET_SUMMARY_TRANSACTIONS_RESPONSE',
  SET_ACTIVE_COMPANY_GSTIN: 'SET_ACTIVE_COMPANY_GSTIN',
  GET_GST_RETURN_SUMMARY: 'GET_GST_RETURN_SUMMARY',
  GET_GST_RETURN_SUMMARY_RESPONSE: 'GET_GST_RETURN_SUMMARY_RESPONSE',
  GET_TRANSACTIONS_COUNT: 'GET_TRANSACTIONS_COUNT',
  GET_TRANSACTIONS_COUNT_RESPONSE: 'GET_TRANSACTIONS_COUNT_RESPONSE',
  GET_DOCUMENT_ISSUED: 'GET_DOCUMENT_ISSUED',
  GET_DOCUMENT_ISSUED_RESPONSE: 'GET_DOCUMENT_ISSUED_RESPONSE',
  REQUEST_TRANSACTIONS: 'REQUEST_TRANSACTIONS',
};
