export const SUBSCRIPTIONS_API = {
    SUBSCRIBED_COMPANIES: 'users/subscriptions',
    SUBSCRIBED_USER_TRANSACTIONS: 'subscriptions/:subscriptionId/all-transactions?from=:from&to=:to&interval=:interval',
    SUBSCRIBED_COMPANY_TRANSACTIONS: 'subscriptions/company/:company/transactions?from=:from&to=:to&interval=:interval',
    SUBSCRIBED_COMPANIES_LIST: 'subscriptions/:subscriptionId/companies',
};

export const SUBSCRIPTION_V2_API = {
    GET_ALL_PLANS: 'v2/subscription/plans/all?regionCode=:regionCode',
    GET_COUNTRY_LIST: 'country/country-list',
    CREATE_SUBSCRIPTION: 'v2/subscription',
    UPDATE_SUBSCRIPTION: 'v2/subscription?company=:company',
    APPLY_PROMOCODE: 'v2/subscription/promocode',
    GET_ALL_SUBSCRIPTIONS: 'v2/subscription/list?page=:page&count=:count',
    SUBSCRIPTION_BY_ID: 'v2/subscription/:subscriptionId',
    CANCEL_SUBSCRIPTION_BY_ID: 'v2/subscription/:subscriptionId/cancel',
    TRANSFER: 'v2/subscription/transfer/ownership?subscriptionId=:subscriptionId',
    VERIFY_OWNERSHIP: 'v2/subscription/verify/ownership?requestId=:requestId&reject=:reject',
    GET_BILLING_DETAILS: 'v2/subscription/billing-account/get?billingAccountUnqiueName=:billingAccountUnqiueName',
    UPDATE_BILLING_DETAILS: 'v2/subscription/billing-account/:billingAccountUnqiueName',
    GET_COMPANIES_LIST_BY_SUBSCRIPTION_ID: 'v2/subscription/company-list/:subscriptionId?sort=:sort&sortBy=:sortBy&page=:page&count=:count&q=:query',
    GENERATE_ORDER_BY_SUBSCRIPTION_ID: 'v2/subscription/:subscriptionId/generate-order?promocode=:promocode',
    GET_CHANGE_PLAN_DETAILS: 'v2/subscription/change-plan',
    UPDATE_PLAN: 'v2/subscription/update',
    BUY_PLAN_BY_GOCARDLESS: 'v2/subscription/buy-plan',
    GET_COMPANIES_BY_SUBSCRIPTION_ID: 'v2/subscription/:subscriptionId/company-list?page=:page&count=:count&q=:q',
    SET_DEFAULT_PAYMENT_METHOD: 'v2/subscription/payment-method/:paymentUniqueName',
    SAVE_PAYMENT_METHOD: 'v2/subscription/add-payment-method',
    GET_PAYMENT_METHODS: 'v2/subscription/:subscriptionId/payment-methods',
    DELETE_PAYMENT_METHOD: 'v2/subscription/payment-method/:paymentUniqueName',
    SET_ARCHIVE_UNARCHIVE_COMPANY: 'company/:companyUniqueName',
    ACTIVATE_PLAN: 'v2/subscription/:subscriptionId/activate?upgrade=true',
    CALCULATION_PLAN_AMOUNT: 'v2/subscription/get-amount',
    SAVE_RAZORPAY_TOKEN: 'v2/subscription/:subscriptionId/payment/:paymentId/save-razorpay-token',
};
