name: Auto PR Review

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: Garlic-Team/Auto-Review@1.0.5
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
