# This is a basic workflow to help you get started with Actions

name: UI build

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out Git repository
        uses: actions/checkout@v2

      # Runs a single command to install Node
      - name: Install Node.js & NPM
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Runs npm i
      - uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0
        with:
          useLockFile: false
          useRollingCache: true
          working-directory: .
      - name: Creating bundle
        run: npm run build-test
        env:
          NG_BUILD_IVY_LEGACY: 1
