export const VIDEOLINK = {
    VOUCHER_SALES: 'https://www.youtube.com/embed/TDEl-daOySU?si=NJovgqKIUEwxG54M&amp;start=82',
    VOUCHER_CASH: 'https://www.youtube.com/embed/TDEl-daOySU?si=NJovgqKIUEwxG54M',
    SALES_PREVIEW: 'https://www.youtube.com/embed/y9at0bOnHcw?si=FjqP45U0hWvIcFIM',
    INVENTORY_MASTER: "https://www.youtube.com/embed/SCymMiHtG30?si=7_jYkM8LBwFz_v3r",
    INVENTORY_MASTER_GROUP: "https://www.youtube.com/embed/SCymMiHtG30?si=xPtwoa7nD55bJg2C&amp;start=41",
    INVENTORY_CREATE_STOCK: "https://www.youtube.com/embed/BpQNwfVqvto?si=RMDls_K39f9gKp-7",
    ECOMM_INTEGRATION: "https://www.youtube.com/embed/VztCB0KeG70?si=5KnjTJbnQjEXFLhD",
    GST_FILLING_DASHBOARD: "https://www.youtube.com/embed/7NcUnWRlq6Q?si=yucjgvQ89N-nmuXa",
    GSTR3B: "https://www.youtube.com/embed/DMNqDuIqK0Q?si=a2uzS1Lgg14v4RJ1",
    GSTR1: "https://www.youtube.com/embed/WfdcKZs7VbU?si=foAEswap_4mxQhb5",
    GSTR2: "https://www.youtube.com/embed/atz0sTXoSWc?si=tTYYhT4DrhWIPZro",
    INVENTORY_REPORT_GROUPWISE: "https://www.youtube.com/embed/dQBlCaVWojU?si=v95vozCO4z0XrfJ7",
    INVENTORY_REPORT_ITEMWISE: "https://www.youtube.com/embed/B37yj_FruHA?si=b2gOl2OnGbYblBF2",
    INVENTORY_REPORT_VARIANTWISE: "https://www.youtube.com/embed/grOVnY9eXQE?si=a8_wl_USoWYUMs_F",
    IMPORT_ENTRIES: "https://www.youtube.com/embed/dkbVW_n24ug?si=GIoJ5qWkZZvJ06ml",
    IMPORT_INVENTORY: "https://www.youtube.com/embed/Xkf19YZqLbQ?si=O_VO5akBoekgtSdl",
    IMPORT_MASTER: "https://www.youtube.com/embed/Ij_kNKOzuqo?si=KLLx0XolqYBYB_U9",
    BARCODE: "https://www.youtube.com/embed/x1OJlwia3OY?si=1LBbTy-hxJI4bfKe",
    DAYBOOK: "https://www.youtube.com/embed/zYFouv7uaEo?si=34xOTDVT1-fC27H_",
};
