export const INVOICE_RECEIPT_ACTIONS = {
  DOWNLOAD_VOUCHER_REQUEST: 'DOWNLOAD_VOUCHER_REQUEST',
  DOWNLOAD_VOUCHER_RESPONSE: 'DOWNLOAD_VOUCHER_RESPONSE',
  INVOICE_RECEIPT_RESET: 'INVOICE_RECEIPT_RESET',
  UPDATE_INVOICE_RECEIPT: 'UPDATE_INVOICE_RECEIPT',
  UPDATE_INVOICE_RECEIPT_RESPONSE: 'UPDATE_INVOICE_RECEIPT_RESPONSE',
  UPDATE_GENERATED_INVOICE_RECEIPT: 'UPDATE_GENERATED_INVOICE_RECEIPT',
  GET_ALL_INVOICE_RECEIPT: 'GET_ALL_INVOICE_RECEIPT',
  GET_ALL_INVOICE_RECEIPT_RESPONSE: 'GET_ALL_INVOICE_RECEIPT_RESPONSE',
  DELETE_INVOICE_RECEIPT: 'DELETE_INVOICE_RECEIPT',
  DELETE_INVOICE_RECEIPT_RESPONSE: 'DELETE_INVOICE_RECEIPT_RESPONSE'

};
