export const INVOICE_RECEIPT_ACTIONS = {
  DOWNLOAD_VOUCHER_REQUEST: 'DOWNLOAD_VOUCHER_REQUEST',
  DOWNLOAD_VOUCHER_RESPONSE: 'DOWNLOAD_VOUCHER_RESPONSE',
  INVOICE_RECEIPT_RESET: 'INVOICE_RECEIPT_RESET'
};
